### ISSUE TITLE
Les livres supprimés dans Mistral ne le sont pas dans Drupal

### ISSUE THREAD

**Issue by zakxxi** [EditionsDuRouergue/lerouergue#135]
![image](https://cloud.githubusercontent.com/assets/1446617/10197241/e94671a6-6796-11e5-970a-c3d5733dd63b.png)

**Comment by jabberwooki** [comment]
La seule info que Drupal obtient de Mistral, c'est le fichier de dump sql.

Drupal n'a aucun moyen de savoir si les fichiers précédemment importés n'existent plus dans Mistral.
Si des fichiers importés dans Drupal ne sont plus mentionnés dans le dump suivant, est-ce parce qu'il n'ont pas été exportés de Mistral pour une raison x ou est-ce parce qu'il n'existent réellement plus dans Drupal ? Si la réponse est oui, alors il faut effectivement de Drupal ceux qui sont absents du dump.
Mais : 
1) il faut être sûr que cette règle est vraie.
2) il faut faire un développement supplémentaire consistant à comparer les livres Drupal et les livres du dump, puis supprimer les livres Drupal qui ne sont pas dans le dump. A chiffrer.
3) Attention, si ce mécanisme est mis en place, toute erreur d'extraction des données Rouergue depuis Mistral provoquera la suppression des livres non exportés alors qu'il ne fallait pas.

La bonne solution est que Drupal reçoive un fichier listant les livres à supprimer. Ainsi ce n'est pas le site web qui décide ce qu'il faut faire, mais le Rouergue qui sait dire quels sont les livres à supprimer.

A discuter plus en détails si nécessaire.

**Comment by zakxxi** [comment]
Ça marche, je viens de m'en rendre compte car il y'a eu un gros ménage Mistral côté Rouergue > surpression de nombreux livres interdits à la vente, donc je vais faire un rollback sur la prod avant de reimporter le nouveau dump.

**Comment by Rouergue** [comment]
Il faut supprimer manuellement dans drupal les fiches auteurs ou livres qui ont été créés au début dans drupal et supprimés depuis dans mistral.
