### ISSUE TITLE
on ne peut pas recadrer les petites vignettes à partir des grandes images ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#153]
exemple dans la fabrique (ou événements) où la tête de l'auteur peut se retrouver coupée !

![capture d ecran 2015-10-07 a 11 18 34](https://cloud.githubusercontent.com/assets/10072454/10333597/48d2a90c-6ce5-11e5-9dce-acdaa0bfee81.png)

**Comment by zakxxi** [comment]
Il faudrait rajouter un champ "vignette" sur le type de contenu, avec possibilité de recadrage.

**Comment by zakxxi** [comment]
https://www.drupal.org/project/imagefield_crop

**Comment by Fchallier** [comment]
C'est noté, j'utilise déjà ce module sur plusieurs de nos sites

**Comment by zakxxi** [comment]
J'ai créé le champ vignette, François je laisse le ticket ouvert si tu souhaites rajouter le imagefield_crop après livraison.
