### ISSUE TITLE
Affichage du feuilletage

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#157]
Est-il possible de faire s'ouvrir le feuilletage directement dans la page de la fabrique (et non pas dans une fenêtre pop-up), un peu comme pour les vidéos ? 
Par ailleurs, au niveau de la présentation des extraits, nous pensions que les pages pourraient être "tournées" une à une comme un catalogue que l'on feuillette (comme sur issuu) et non pas comme une succession de planches les unes en-dessous des autres avec tous les menus qui s'affichent au-dessus. Est-ce compliqué à faire ? 

![capture d ecran 2015-10-07 a 16 28 32](https://cloud.githubusercontent.com/assets/10072454/10340577/10be0fbc-6d11-11e5-9232-76b29d203283.png)

**Comment by zakxxi** [comment]
Alors on n'est pas possible d'ouvrir dans la page fabrique, par contre le pop-up doit encore être intégré pour coller aux dernières maquettes graphiques (fond noir).

Pour les doubles pages ce n'est pas simple.
cf : http://cms.about.com/od/drupal-modules/fl/How-to-Choose-a-PDF-Viewer-Module-for-Drupal-7-Part-4.htm

La seule solution viable est : https://www.drupal.org/project/flexpaper
mais assez complexe à mettre en place côté serveur (compilation et installation de plusieurs libraries) je n'ai pas les droits nécessaires.

À faire en dev sup si besoin.

Plan B > Faire de fausse "doube-pages" avant d'exporter en PDF.

**Comment by Rouergue** [comment]
Est-ce possible de rendre le bouton "feuilletage" réactif quand on passe la souris dessus (comme lorsqu'on passe sur le titre des autres articles de la fabrique et que ça devient orange) pour bien montrer que c'est un lien ''cliquable" ?

![capture d ecran 2015-10-08 a 16 32 54](https://cloud.githubusercontent.com/assets/10072454/10369418/719abbae-6dda-11e5-8e2c-9df9ac2a0891.png)

**Comment by Rouergue** [comment]
et mettre "feuilleter" tout en bas-de-casse, sans capitale à "F" ?

**Comment by zakxxi** [comment]
OK pour les modifs du bouton.

**Comment by Rouergue** [comment]
Je ne sais plus ce qu'on avait dit à ce sujet... Est-il possible d'intégrer directement le feuilletage dans le champ "citation presse" de la page livre, de manière à ce que le livre puisse se feuilleter à même la page de présentation, sans ouverture de fenêtre supplémentaire ou de pop-up ? Est-ce long et compliqué à mettre en place ?

**Comment by Fchallier** [comment]
Alors on avait dit il me semble : 
- Sur les fabriques ajouter directement la liseuse issuu à la place du bouton, même si celle-ci sera petite (260 px de large) 
- Et sur la fiche livre rajouter un champs qui sera au-dessus des citations presse, permettant d’intégrer directement une vidéo et/ou une liseuse

**Comment by Rouergue** [comment]
Oui, c'est ça pour les fiches livres. Est-ce que c'est long à mettre en place ?

Et au niveau de la fabrique, est-ce que ça ne va pas faire trop petit 260 px de large, finalement ? Qu'en penses-tu ?

**Comment by Fchallier** [comment]
Ben c'est un peu long oui, il y a plusieurs modification à faire.... 
Et pour la fabrique ça sera un peu petit oui... Mais si tu préfère je rajoute un champ pour les liseuses dessous des photos ? ça prendra la largeur de la page.

**Comment by Rouergue** [comment]
Oui, sous les photos, ça me paraît mieux pour la fabrique (= 550 px de large, c'est ça ?). 
Mais ça peut être dans un 2e temps. C'est moins pressé que pour les fiches livres. 
En attendant, je vais mettre les extraits à télécharger en pdf avec le système actuel. 
(d'ailleurs, à ce sujet : les pdf que j'aurai téléchargés le seront aussi pour la liseuse ou bien il faudra que je réimporte les fichiers une deuxième fois ?).

**Comment by Rouergue** [comment]
Euh... Je comprends comment il faut faire pour les vidéos, mais comment ça fonctionne pour la liseuse ? Et les pdf que j'ai déjà téléchargés le seront aussi pour la liseuse ou bien il faudra que je réimporte les fichiers une deuxième fois ?

**Comment by Fchallier** [comment]
Il faut que tu rajoutes tes PDF sur Issuu pour générer une liseuse et pouvoir récupérer l'embed code. 

Je te conseille de laisser les anciens extraits comme ils sont et pour les prochains générer les liseuses Issuu.

**Comment by Rouergue** [comment]
Ok, ça marche...
Merci !

**Comment by Fchallier** [comment]
Changer le type du champ. 

Adapter le code pour que la pop-up affiche le résultat de l'embed code.

**Comment by Rouergue** [comment]
J'ai l'impression que le champ "embed video-liseuse" ne fonctionne plus. Quand je colle le code d'intégration et que je re-clique ensuite sur "source", celui-ci disparaît. Est-ce parce que la fenêtre pop-up n'est pas encore opérationnelle ? 

![capture d ecran 2016-03-10 a 10 26 27](https://cloud.githubusercontent.com/assets/10072454/13665030/b774b604-e6aa-11e5-8856-b415df264541.png)

J'ai téléchargé quelques extraits sur issuu (en page à page) mais, si je mets le fichier pdf tel quel dans le site, du coup, celui-ci apparaît en page à page au niveau du feuilletage (au lieu de s'afficher en planches comme dans issuu). Je ne sais pas si je suis très claire !... :-)

**Comment by Rouergue** [comment]
Actuellement, je suis obligée de créer 2 pdf : un en page à page pour issuu (qui nous sert pour facebook, pagedeslibraires, etc.) et un autre en planches pour le système actuel de feuilletage du site. Est-ce que tu penses que tu pourras t'occuper assez rapidement de ce point-là ? Si tu as besoin d'exemple, tu peux partir sur : 

<div data-configid="5740857/34031311" style="width:525px; height:385px;" class="issuuembed"></div>
<script type="text/javascript" src="//e.issuu.com/embed.js" async="true"></script>

http://issuu.com/rouergue/docs/obia-extrait?e=5740857/34031311

**Comment by Rouergue** [comment]
<iframe width="525" height="385" src="//e.issuu.com/embed.html#5740857/34031311" frameborder="0" allowfullscreen></iframe>
