### ISSUE TITLE
tri dans la fabrique ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#169]
Peut-on trier l'ordre d'apparition des différents articles de la Fabrique ? (sachant que les derniers mis en forme ne correpondent pas forcément à des livres récents ou à des nouveautés) ?

![capture d ecran 2015-10-08 a 16 53 24](https://cloud.githubusercontent.com/assets/10072454/10369968/40c76c9a-6ddd-11e5-8fea-cad4e9c1d3d9.png)

**Comment by zakxxi** [comment]
Il faudrait utiliser le module draggable views comme pour les actus, non prévu au cahier des charges donc dev sup.

**Comment by Rouergue** [comment]
+ tri par mois (sous forme d'archivesà, en laissant les 6 derniers articles de la fabrique visibles, par exemple.
