### ISSUE TITLE
Version mobile du site

### ISSUE THREAD

**Issue by zakxxi** [EditionsDuRouergue/lerouergue#176]

**Comment by Rouergue** [comment]
Il me semblait que cela faisait partie du cahier des charges, que le site soit adaptable pour les tablettes et autres smartphones ? Cf. #55 ou #107

**Comment by zakxxi** [comment]
Sur le devis initial on est sur Ordianteur + Tablettes ce qui est le cas aujourd'hui la version mobile n'a pas été chiffrée.
