### ISSUE TITLE
Deux visuels de couvs différents pour un même gencod ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#197]
C'est bizarre, on n'a pas la même couv pour Rabanel, sur la page auteur et sur la page livre. Quid ?

![capture d ecran 2015-10-20 a 16 02 07](https://cloud.githubusercontent.com/assets/10072454/10609582/b073322a-7744-11e5-9e87-1f7706490153.png)

![capture d ecran 2015-10-20 a 16 01 53](https://cloud.githubusercontent.com/assets/10072454/10609584/b3442d6a-7744-11e5-8f5e-b8f935edebc9.png)

**Comment by Fchallier** [comment]
Les miniatures sont à jour, mais pas les couverture. 
Il faudra probablement vider le cache des Image. A voir demain aprés le passage du cron (mise à jour)

**Comment by zakxxi** [comment]
Tu peux faire après le cron hebdomadaire et le script des permissions
```drush image-flush --all```

ça regénère tous les styles d'images
