### ISSUE TITLE
Titre qui n'apparaît pas sur le visuel de couverture

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#198]
alors que le fichier est bon dans mistral...

![capture d ecran 2015-10-20 a 16 08 00](https://cloud.githubusercontent.com/assets/10072454/10609635/e0f1513e-7744-11e5-9da7-b4bce34fe489.png)

![capture d ecran 2015-10-20 a 16 08 26](https://cloud.githubusercontent.com/assets/10072454/10609639/e35200ae-7744-11e5-889a-812804b10eca.png)

**Comment by Fchallier** [comment]
Ce n'était pas la bonne couverture lors de l'envoie massif.
ça sera à jour dès demain matin.
