### ISSUE TITLE
Où est passé le contour blanc de la couv ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#199]
![capture d ecran 2015-10-20 a 16 09 50](https://cloud.githubusercontent.com/assets/10072454/10609666/09b7558c-7745-11e5-820f-5ed8d1d761fd.png)

sur mistral, c'est ok : 
![capture d ecran 2015-10-20 a 16 10 23](https://cloud.githubusercontent.com/assets/10072454/10609704/2b97b3ae-7745-11e5-9295-ee93b8aa68b3.png)

**Comment by Fchallier** [comment]
Le contour de la couv est de la même couleur que le fond du site. 
http://prod.lerouergue.com/sites/default/files/styles/article-cover/adaptive-image/public/catalog/cover-images/9782812609725.jpg
