### ISSUE TITLE
Pb de contributeur vide qui se rajoute au moment de la mise à jour du site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#200]
À nouveau, on a un champ directeur de coll. vide qui s'affiche et qui empêche l'enregistrement de la fiche.

![capture d ecran 2015-10-21 a 10 13 12](https://cloud.githubusercontent.com/assets/10072454/10632187/fe2a09fa-77e2-11e5-8d03-1dbf66b2ed41.png)

![capture d ecran 2015-10-21 a 10 13 18](https://cloud.githubusercontent.com/assets/10072454/10632189/0110309a-77e3-11e5-9f91-e84e721fcf15.png)

**Comment by Fchallier** [comment]
Je viens de regarder dans Mistral et Le directeur de coll n'est pas coché comme communicable. 
 Tu peux donc cliquer sur le bouton "Retirer"

**Comment by zakxxi** [comment]
C'était lié à "Olivier Douzou (point)" qui a été supprimé à la main dans Drupal, du coup le champ se retrouve vide, il faudrait gérer ça au moment du Dump.

**Comment by Rouergue** [comment]
Le problème se pose toujours pour les nouveaux albums (uniquement concernant les titres pour lesquels Olivier Douzou est le directeur de collection).

![capture d ecran 2016-01-06 a 11 23 32](https://cloud.githubusercontent.com/assets/10072454/12143849/10617b84-b484-11e5-8d77-85f856cb4854.png)
