### ISSUE TITLE
Configurer Google Analytics pour les statistiques

### ISSUE THREAD

**Issue by zakxxi** [EditionsDuRouergue/lerouergue#201]
/admin/config/system/googleanalytics

**Comment by zakxxi** [comment]
http://www.google.com/analytics/

**Comment by Fchallier** [comment]
Mathilde, il faudrait que tu me transmettes un adresse en Gmail pour vous ajouter à notre google analitycs.

**Comment by Rouergue** [comment]
il faut que je le retrouve… 
Je peux te donner ça début novembre ? 
(je pars en vacances ce soir :-)

**Comment by zakxxi** [comment]
Bonnes vacances !

**Comment by Fchallier** [comment]
Oui sans soucis pour moi. 

Bonnes vacances !

**Comment by Rouergue** [comment]
MERCI !

**Comment by Rouergue** [comment]
Et bon courage à vous...
