### ISSUE TITLE
L'ital et le bold ont semble-t-il disparu...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#202]
Ils n'apparaissent pas dans les résumés sur le site alors qu'ils sont bien dans mistral.

![capture d ecran 2015-10-21 a 12 52 29](https://cloud.githubusercontent.com/assets/10072454/10634554/e234a362-77f2-11e5-9309-3a3569fea435.png)

![capture d ecran 2015-10-21 a 12 53 46](https://cloud.githubusercontent.com/assets/10072454/10634550/defb9eb2-77f2-11e5-850e-0feaf119918e.png)

**Comment by zakxxi** [comment]
Effectivement on a pas mis la mécanique en place pour les contributeurs, je m'en occupe. Ce sera visible seulement après un nouvel import.

**Comment by zakxxi** [comment]
François pour info on utilise la fonction PHP strip_tags
http://fr.php.net/manual/fr/function.strip-tags.php

```$row->backcover = html_entity_decode(strip_tags($text, '<b><strong><i><em>'));```

**Comment by zakxxi** [comment]
C'est en place sur mon instance de dév
![image](https://cloud.githubusercontent.com/assets/1446617/10635751/4bfdadb8-77fb-11e5-8f39-60e0a25bf6a6.png)
