### ISSUE TITLE
Thèmes en doublon dans la recherche multi-critères

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#203]
![capture d ecran 2015-10-21 a 15 08 10](https://cloud.githubusercontent.com/assets/10072454/10637416/d5ad7368-7805-11e5-9d82-e540b50cde44.png)

**Comment by zakxxi** [comment]
On s'en occupe, le bug a déjà été rencontré.

**Comment by zakxxi** [comment]
Suppression des doublons dans un vocabulaire.
Le test est à adapter en fonction des cas.

$voc = taxonomy_vocabulary_machine_name_load('themes');
$terms = taxonomy_get_tree($voc->vid);

foreach ($terms as $term) {
 $alias = drupal_get_path_alias('taxonomy/term/'.$term->tid);
 dpm(substr($alias, -2));
 //if (substr($alias, -2) == '-0') {
 //  taxonomy_term_delete($term->tid);
 //}
}
