### ISSUE TITLE
Pb d'affichage sur la recherche multi-critères

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#204]
Avec un bandeau intempestif qui traverse toute la page !

![capture d ecran 2015-10-21 a 15 07 30](https://cloud.githubusercontent.com/assets/10072454/10637423/e62f6ee4-7805-11e5-8ec7-f8908748f69e.png)

**Comment by zakxxi** [comment]
Bug CSS, je le fixerai mercredi à mon retour.
