### ISSUE TITLE
Ne faire apparaître que les lectorats "rouergue"

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#205]
c'est-à-dire ceux contenu dans les fiches livres. Les lectorats "benjamin", "cadet" ne veulent rien dire pour nous... Est-il possible de faire disparaître leur affichage de la liste déroulante dans la recherche multi-critères ? 

![capture d ecran 2015-10-21 a 15 08 10](https://cloud.githubusercontent.com/assets/10072454/10637464/2311aac0-7806-11e5-9607-191611ab75ee.png)

**Comment by zakxxi** [comment]
Il faudrait les supprimer au moment du dump.

**Comment by Fchallier** [comment]
Ok sur le dump à vérifier à la prochaine mise jour
