### ISSUE TITLE
supprimer les epub de l'affichage du résultat des recherches

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#206]
![capture d ecran 2015-10-21 a 15 21 49](https://cloud.githubusercontent.com/assets/10072454/10637739/80550c08-7807-11e5-9775-87f7d66afcf1.png)

Idem que pour l'affichage du catalogue complet ou des bibio auteurs.

**Comment by zakxxi** [comment]
Hum, je ne sais pas si c'est possible d'exclure des choses des résultats de recherche… En tout cas ce n'est pas une vue (comme le catalogue), à fouiller si nécessaire.
