### ISSUE TITLE
Pourquoi l'image png (72 dpi et 550 px de large) est-elle floue dans la fabrique ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#208]
![capture d ecran 2015-10-21 a 17 14 46](https://cloud.githubusercontent.com/assets/10072454/10640976/7395d2d0-7817-11e5-9a50-3b39b71e562f.png)

Idem pour les bandeaux de la page accueil (1140 pixels x 300 pixels et 72 dpi)

![capture d ecran 2015-10-21 a 16 34 39](https://cloud.githubusercontent.com/assets/10072454/10640999/8b213b7e-7817-11e5-8b5c-94a99efef6b1.png)

**Comment by zakxxi** [comment]
Ça vient de la compression JPG, configurée à 75%
![image](https://cloud.githubusercontent.com/assets/1446617/10641360/4092b9d2-7819-11e5-8ecf-8b745f0ae397.png)

On peut essayer de monter à 90% voir si cela ne ralentit pas trop le site.

http://www.lerouergue.com/admin/config/media/image-toolkit
