### ISSUE TITLE
Titre qui n'apparaît pas dans les univers

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#210]
C'est le cas par exemple pour BAIES ET FRUITS SAUVAGES... (9782812604614) qu'on ne trouve pas sur le site dans la rubrique NATURE, ni dans la sous-rubrique BOTANIQUE, alors qu'il est bien classé dans mistral en sous-collection NATURE, série BOTANIQUE... 

![capture d ecran 2015-11-04 a 15 00 13](https://cloud.githubusercontent.com/assets/10072454/10939942/5dbc92ca-8305-11e5-9b92-45ace67b0d43.png)

![capture d ecran 2015-11-04 a 15 02 31](https://cloud.githubusercontent.com/assets/10072454/10939945/61dd4246-8305-11e5-97d9-73c7772ba188.png)

On rencontre le même problème pour les titres suivants :
- Graines et fruits
- Plantes des haies champêtres
- Guide des fleurs coupées et des feuillages

Ces trois titres devraient apparaître sur notre site en NATURE et en BOTANIQUE. 
Pourquoi n'apparaissent-ils pas ?

**Comment by Fchallier** [comment]
Je vais veriffier le mapping

**Comment by Fchallier** [comment]
Mapping était Ok. 
Base de donnée qui n'est pas à jour, à vérifier demain.

**Comment by Fchallier** [comment]
ok avec le dernier dump
