### ISSUE TITLE
Petit pb sur la barre de défilement (2 ronds oranges) en bas à droite, elle "saute" suivant la hauteur des titres. 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#212]
C'est visible sur la page d'accueil comme sur les pages livres ou auteur... Ne pourrait-on pas la fixer en pied ?

![capture d ecran 2015-11-04 a 16 14 05](https://cloud.githubusercontent.com/assets/10072454/10942217/5591bf58-830f-11e5-8328-e3f2572ab5f1.png)

![capture d ecran 2015-11-04 a 16 14 10](https://cloud.githubusercontent.com/assets/10072454/10942218/57c16bac-830f-11e5-8d53-33d6044a0d76.png)

**Comment by Rouergue** [comment]
Pb des couvertures qu'il faudrait aligner sur le bas.

**Comment by Fchallier** [comment]
Ajout d'une hauteur max
