### ISSUE TITLE
Réduction de l'interlignage dans le bandeau accueil de la fabrique

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#216]
Olivier Douzou demande s'il est possible de réduire l'interlignage de la phrase
sous la fabrique, lorsque celle-ci est sur deux lignes (la génèse etc...).

![unknown](https://cloud.githubusercontent.com/assets/10072454/11502863/8ed6fa4c-983d-11e5-8ea3-6520396fb0a9.png)

**Comment by Fchallier** [comment]
Oui sans soucis :)
