### ISSUE TITLE
ajout d'un cartouche vidéo dans la page livre ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#217]
Est-ce possible de faire en sorte que les vidéos (importées de vimeo) s'ouvrent directement dans une page livre (comme pour les articles de la Fabrique) au lieu de renvoyer vers une autre page qui ouvre vimeo ? 

exemple :
http://www.lerouergue.com/catalogue/les-autodafeurs-tome-1
![capture d ecran 2015-12-01 a 16 42 31](https://cloud.githubusercontent.com/assets/10072454/11505404/84e47962-984a-11e5-80a7-4e5aab0871da.png)

**Comment by Fchallier** [comment]
Il un nouveau champ sur la fiche livre  "Embed vidéo - liseuse". 

Il suffira de cliquer d'abord sur le petit bouton "Source" et coller le code d’intégration du style  : 

 <iframe width="560" height="315" src="https://www.youtube.com/embed/V0x9-FJpsxY?rel=0" frameborder="0" allowfullscreen></iframe>
