### ISSUE TITLE
auteur qui ne devrait pas apparaître

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#218]
Il s'agit de CAMPBELL CONNELLY FRANCE, pourtant décoché communicable dans mistral

![capture d ecran 2015-12-01 a 16 55 03](https://cloud.githubusercontent.com/assets/10072454/11505760/6222763e-984c-11e5-8254-fbc5178352da.png)

Cela correspond juste à l'illus. de couv d'un roman. Or la fiche contributeur apparaît sur le site et dans le repertoire auteurs. 

![capture d ecran 2015-12-01 a 16 55 18](https://cloud.githubusercontent.com/assets/10072454/11505815/912e658c-984c-11e5-8b7e-ea2edd5796d4.png)

Quid ?

**Comment by Fchallier** [comment]
#135
