### ISSUE TITLE
peut-on supprimer les fiches "collectif" de la rubrique auteurs ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#219]
![capture d ecran 2015-12-01 a 16 59 45](https://cloud.githubusercontent.com/assets/10072454/11506018/80f1fff2-984d-11e5-94e2-adebfd7ddbb1.png)

**Comment by Rouergue** [comment]
Voici la liste des liens qu'il faudrait supprimer (sans supprimer les livres qui en dépendent !) : 

• Ligue Pour La Protection Des Oiseaux
• SPECTA-FILM CEPEC Les Films De Mon Oncle
• Collectif
• Collectif D'Auteurs De La Ligue Protectrice Des Oiseaux Aveyron
• Moundarren
• Parc National Des Cévennes
• PLV (pourquoi ça remonte ?)
• Sols Et Civilisations

**Comment by Rouergue** [comment]
Ok, tous les auteurs "parasites" ont été supprimés sur le site (et décochés "communicables" sur mistral). Le seul pb subsiste pour le contributeur COLLECTIF. 
Comment fais-tu sur le site d'Actes Sud, François, pour que le terme apparaisse sans que le lien soit effectif (sachant qu'on ne peut pas décocher "communicable" sur mistral puisqu'il n'y a qu'un seul contributeur "collectif") ? 

![capture d ecran 2015-12-08 a 16 03 30](https://cloud.githubusercontent.com/assets/10072454/11658871/6bd08b34-9dc5-11e5-9c07-410aa38a2e46.png)

**Comment by Fchallier** [comment]
Exclusion de l'auteur 'Collectif" id n°13097 de la page auteurs

+ Il reste à faire la config pour les fiches livres

**Comment by Rouergue** [comment]
Bon. Pour ce problème, j'ai finalement supprimé simplement la fiche auteur COLLECTIF, comme ça, il n'y a plus de problème de bibliographie qui serait commune à tous les titres concernés et il n'y a plus de problème de bio. Le seul truc, c'est qu'il ne faut pas que la fiche COLLECTIF remonte à chaque mise à jour...
