### ISSUE TITLE
Pourquoi la PLV remonte sur le site ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#220]
![capture d ecran 2015-12-02 a 10 10 42](https://cloud.githubusercontent.com/assets/10072454/11527167/9478b038-98df-11e5-8da2-1aec762b2b16.png)

**Comment by Fchallier** [comment]
Car dans Mistral les catalogues sont renseigné comme type : Livre.... et non pas PLV.
Il faut faire la correction dans Mistral

**Comment by Rouergue** [comment]
Ok, je vais faire les corrections et je transmets l'info au service commercial pour les PLV à venir.
Merci !
