### ISSUE TITLE
Pourquoi la pagination n'apparaît pas ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#222]
... sur le site alors que la mention est correcte dans mistral ? 

![capture d ecran 2015-12-02 a 13 57 01](https://cloud.githubusercontent.com/assets/10072454/11531365/a3180e00-98fc-11e5-9386-6d1ab7c9633f.png)

![capture d ecran 2015-12-02 a 13 57 16](https://cloud.githubusercontent.com/assets/10072454/11531368/a6115b02-98fc-11e5-96c7-5f2bf74190c0.png)

Cela le fait pour plusieurs titres anciens...

**Comment by Fchallier** [comment]
![les beaux bruns rouergue](https://cloud.githubusercontent.com/assets/9974750/11561514/36a3de8a-99c8-11e5-89b9-b2395cabd35b.png)

C'était surement un problème au niveau de l'avant dernier dump ?

**Comment by Fchallier** [comment]
Ok en BDD
