### ISSUE TITLE
Impossibilité d'aller au-delà de la page 82 du catalogue

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#223]
![capture d ecran 2015-12-02 a 14 15 17](https://cloud.githubusercontent.com/assets/10072454/11531710/23ce8252-98ff-11e5-80f0-e88adeccc803.png)

**Comment by Fchallier** [comment]
![catalogue](https://cloud.githubusercontent.com/assets/9974750/11561464/e0358a12-99c7-11e5-82c9-2a19bb281996.png)
