### ISSUE TITLE
Livre(s) lié(s) page événement:  Afficher les couvertures

### ISSUE THREAD

**Issue by Fchallier** [EditionsDuRouergue/lerouergue#224]
110px de large // Supprimer le label

**Comment by Rouergue** [comment]
Est-il possible de rapprocher les auteurs des livres liés (si possible avec la couv du visuel) et de dissocier ces infos des champs site web + programmes ? 
Mise en page selon ce schéma :.

![photo du 02-02-16 a 14 41](https://cloud.githubusercontent.com/assets/10072454/12751064/443fcbd0-c9bb-11e5-9c38-d92f91fe4317.jpg)

**Comment by Rouergue** [comment]
Hello François,
Est-ce que c'est long à mettre en place ? 
Ce serait vraiment chouette que les visuels des titres liés puissent apparaître au niveau des événements dans l'agenda. Tu me dis ce qui est possible ?
Merci.

![capture d ecran 2016-09-13 a 10 32 23](https://cloud.githubusercontent.com/assets/10072454/18466956/42ad0128-799e-11e6-912b-709bd515da7f.png)

**Comment by Fchallier** [comment]
![test](https://cloud.githubusercontent.com/assets/9974750/18477725/faebfb4c-79ce-11e6-9b6a-f80685867673.jpg)
Je suis arrivé à le mettre en place sur ma version locale.
Mais dès que je veux faire l'intégration sur la version en ligne ça ne fonctionne pas... je doit ratter quelque chose... Il faut que je trouve la raison...

**Comment by Fchallier** [comment]
C'est ok j'ai fait la mise à jour sur le site :+1:

**Comment by Fchallier** [comment]
Tu en pense quoi de supprimer la mention  "livre(s) lié(s)  ?

**Comment by Rouergue** [comment]
Ça va être super ; merci pour ton boulot !

La mention "livre(s) liés" ne me gêne pas. Ça permet d'enfoncer le clou et d'expliquer ce que les couvs font-là. Ce qui me gêne plus (tu vas me maudire...), ce sont les intitulés en-dessous des couvertures. Lorsqu'ils sont longs, cela fait un grand écart entre les visuels et ça disperse les couvs dans la page ; ce n'est pas génial. 

![capture d ecran 2016-09-15 a 15 44 33](https://cloud.githubusercontent.com/assets/10072454/18552261/f5f72434-7b5b-11e6-881e-4c52f4249003.png)

Peut-être serait-il mieux de les supprimer ou bien de mettre les titres en plus petit, bien en-dessous des couvs (sur 2 lignes si besoin est), de manière à ce qu'il n'y ait pas plus de 50 pixels de large entre 2 couvs. Qu'en penses-tu ? 

Autre solution : garder le système de titres mentionnés à la suite (idem auteurs) et faire apparaître les couvs alignées juste en-dessous. Quelque-chose comme ça :

![exemplelivreslies](https://cloud.githubusercontent.com/assets/10072454/18552637/8d8874c8-7b5d-11e6-9aaf-2b4a89e97569.png)

Et serait-il possible de faire un lien vers la page du livre à partir de la couv' et pas seulement du titre ?

**Comment by Rouergue** [comment]
Et apparemment, il y a des petits bugs au niveau de l'affichage de l'adresse (sous les couvs). Cf. ci-dessous.

![capture d ecran 2016-09-15 a 15 43 45](https://cloud.githubusercontent.com/assets/10072454/18552684/cb9f228e-7b5d-11e6-8f33-45c3cefa6ba3.png)

**Comment by Rouergue** [comment]
Et dernière chose (après, j'arrête, promis !) : serait-il possible d'agrandir un peu l'espace entre SITE WEB et AUTEUR(S) et de rapprocher AUTEUR(S) de LIVRE(S) LIÉ(S). En gros, au lieu de ça :

![capture d ecran 2016-09-15 a 16 02 57](https://cloud.githubusercontent.com/assets/10072454/18552746/17af749e-7b5e-11e6-835b-a1763d8ca942.png)

ça donnerait plutôt ça :

![capture d ecran 2016-09-15 a 16 02 57bis](https://cloud.githubusercontent.com/assets/10072454/18552783/3c8f1850-7b5e-11e6-8f1e-528d4f74bd4a.png)

**Comment by Fchallier** [comment]
alors normalement tout est bon  :)

**Comment by Rouergue** [comment]
L'écart entre les couvertures semble effectivement un peu aléatoire...

![capture d ecran 2016-09-20 a 14 28 47](https://cloud.githubusercontent.com/assets/10072454/18670135/ae93aca2-7f3e-11e6-8eb4-3543e18753eb.png)

**Comment by Fchallier** [comment]
Rajouter une max width à .field-name-title .field-type-ds

Comit prévu semaine prochaine

**Comment by Fchallier** [comment]
Faudra vérifier mais normalement c'est bon

**Comment by Rouergue** [comment]
C'est bizarre, il n'y a pas tout à fait le même écart entre les couvertures, suivant les événements. Exemples ci-dessous : 
![capture d ecran 2016-10-20 a 14 28 02](https://cloud.githubusercontent.com/assets/10072454/19559753/a862be04-96d1-11e6-8a47-d3c719c3e96c.png)

![capture d ecran 2016-10-20 a 14 28 19](https://cloud.githubusercontent.com/assets/10072454/19559763/b4488258-96d1-11e6-9521-1bd225cacad7.png)

Je préfère la première version (avec les couvs rapprochées). Est-il possible de garder cet écart entre les couvs de manière homogène partout ?

**Comment by Rouergue** [comment]
C'est bizarre, il n'y a pas tout à fait le même écart entre les couvertures, suivant les événements. Exemples ci-dessous : 
![capture d ecran 2016-10-20 a 14 28 02](https://cloud.githubusercontent.com/assets/10072454/19559753/a862be04-96d1-11e6-8a47-d3c719c3e96c.png)

![capture d ecran 2016-10-20 a 14 28 19](https://cloud.githubusercontent.com/assets/10072454/19559763/b4488258-96d1-11e6-9521-1bd225cacad7.png)

Je préfère la première version (avec les couvs rapprochées). Est-il possible de garder cet écart entre les couvs de manière homogène partout ?

**Comment by Rouergue** [comment]
Est-il possible d'homogénéiser l'écart entre les couvertures de manière à ne pas avoir plus de 50 pixels entre deux couvertures et ce, de façon régulière. Actuellement, l'écart semble être calculé par rapport à la largeur du titre et non pas des couverture. Lorsqu'il y a bcp de titres (exemple pour le Salon de Montreuil), cela donne un affichage disparate et trop lâche.

Dans l'exemple ci-dessous, l'écart entre "fugueuses" et "buffalo belle" est parfait ! En outre, cela laisse la place pour mettre 4 couvertures sur la même ligne. Est-ce possible ? 

![capture d ecran 2016-11-15 a 11 52 42](https://cloud.githubusercontent.com/assets/10072454/20303211/b796d8fc-ab2a-11e6-9891-5dbd17bb002b.png)

**Comment by Fchallier** [comment]
Je viens de faire une petite modification, tu pourras tester  ?

**Comment by Rouergue** [comment]
Euh... oui, c'est pas mal comme ça, avec 4 couvs sur une même ligne. Mais c'est juste qu'il y a des blancs avec des couvs qui se retrouvent toutes seules sur une ligne. Bizarre...

![capture d ecran 2016-11-15 a 14 17 03](https://cloud.githubusercontent.com/assets/10072454/20307132/599e47b2-ab3e-11e6-9849-6eb8704b02ee.png)

**Comment by Fchallier** [comment]
C'est ok ;)
