### ISSUE TITLE
Suppression du "x" correspondant au format de pages pour les epub

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#226]
![capture d ecran 2015-12-03 a 15 45 52](https://cloud.githubusercontent.com/assets/10072454/11563573/f7af8690-99d4-11e5-8569-27230399985c.png)

**Comment by Rouergue** [comment]
Est-il possible de supprimer aussi le nombre de pages pour le numérique puisqu'il est mentionné "0 pages" ?

![capture d ecran 2016-01-28 a 14 42 32](https://cloud.githubusercontent.com/assets/10072454/12645928/7811bf14-c5cd-11e5-996f-73208acc180c.png)

**Comment by Fchallier** [comment]
Oui je pense que c'est possible.
