### ISSUE TITLE
Création d'un champ pour l'import des vidéos dans la page livre (ou auteur)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#229]
Est-ce ce type de code qu'il faut que je rentre : 
![capture d ecran 2015-12-08 a 10 48 29](https://cloud.githubusercontent.com/assets/10072454/11652643/2fe9aabe-9d99-11e5-84c8-5b78ce389765.png)

**Comment by Rouergue** [comment]
<iframe src="http://www.wat.tv/embedframe/199165chuPP3r12929733" frameborder="0" style="width: 320px; height: 240px;"></iframe>

**Comment by Fchallier** [comment]
Oui ça sera ce type de code qu'il faudra renseigner.

**Comment by Rouergue** [comment]
Ok, pour faire des essais, il y a donc un exemple de vidéo à mettre sur cette page : http://www.lerouergue.com/catalogue/un-cafe-la-campagne

**Comment by Rouergue** [comment]
Est-il possible de faire ouvrir une fenêtre pop-up à la taille de la vidéo, dans l'emplacement prévu sous le texte, mais qui se déclenche à partir d'un lien (ici "voir le teaser") et non pas comme un grand cadre qui s'affiche d'emblée et qui fusille un peu la couverture...

![capture d ecran 2016-03-10 a 11 30 38](https://cloud.githubusercontent.com/assets/10072454/13667031/e173d124-e6b4-11e5-814c-d6b9c839e668.png)

![capture d ecran 2016-03-10 a 11 33 31](https://cloud.githubusercontent.com/assets/10072454/13667037/e7c05aa2-e6b4-11e5-87d4-5266bcac8095.png)

L'idéal, ce serait ça :

![capture d ecran 2016-03-10 a 11 33 01](https://cloud.githubusercontent.com/assets/10072454/13667049/f348b8e2-e6b4-11e5-99bb-807711f20fd9.png)
