### ISSUE TITLE
Je ne peux plus glisser facilement une image de mon bureau vers l'interface admin. du site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#230]
Auparavant, je pouvais juste glisser rapidement une image du bureau vers le champ "photo" et cela prenait l'image en compte. Maintenant, je suis obligée de cliquer sur "choisissez un fichier", d'aller chercher l'image sur le bureau et de faire ensuite "transférer". Comme si la surface de "prise en compte" de l'image avait été réduite. C'est pas très grave, mais c'est beaucoup moins pratique et plus long !

![capture d ecran 2015-12-08 a 10 21 42](https://cloud.githubusercontent.com/assets/10072454/11652758/dd6fa274-9d99-11e5-9736-e6c715b87f9a.png)

**Comment by Fchallier** [comment]
Moi cela fonctionne sur l'ensemble des navigateur...
