### ISSUE TITLE
La pagination n'apparaît toujours pas (malgré la mise à jour du serveur)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#232]
Exemple pour DANSE LA VIGNE (pagination bien notée dans mistral mais pas sur le site).

![capture d ecran 2015-12-09 a 15 34 48](https://cloud.githubusercontent.com/assets/10072454/11688222/8c9ba4b8-9e8b-11e5-8d13-4d3abd8d8112.png)

![capture d ecran 2015-12-09 a 15 34 56](https://cloud.githubusercontent.com/assets/10072454/11688232/9e9dba84-9e8b-11e5-957a-a954a3319526.png)

**Comment by Fchallier** [comment]
Je pense qu'il y a eu une petite confusion lors du dev.... car dans le module de migration c'est le champ "finalnbpage" de la table fabrication plan qui est récupérée... Il faudra que change ça pas le champ "Nbpage" de la table "Book"
