### ISSUE TITLE
Pourquoi la galerie de la FABRIQUE n'accepte-t-elle pas d'images ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#233]
![capture d ecran 2015-12-17 a 14 26 33](https://cloud.githubusercontent.com/assets/10072454/11870689/482ce720-a4ca-11e5-98a0-b405329944b3.png)
 
Les images sont pourtant en png et font moins de 2 Mo.
Est-ce pcq elle est trop longue ? elle fait 260 px de large par 2367 px de haut. Avec le scroll bar ça devrait aller, non ?

**Comment by Rouergue** [comment]
Décidément, c'est la grosse galère pour l'intégration d'images dans la fabrique. Ça ne marche qu'une fois sur 5 (pour le même type de fichier). La plupart du temps, voici ce qui s'affiche :

![capture d ecran 2015-12-17 a 15 14 11](https://cloud.githubusercontent.com/assets/10072454/11871603/f6d479fe-a4d0-11e5-8182-24d7ac4ebed1.png)

**Comment by Fchallier** [comment]
Je viens de faire des tests et c'était bel et bien à cause de notre débit ici à Arles
