### ISSUE TITLE
Pb de vignette au niveau de la Fabrique

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#238]
La même image qui sert pour la page d'accueil du site en bas à droite et la page de récap' de la rubrique FABRIQUE ne s'affiche pas dans des cadres de taille identique. Du coup, soit l'image est rognée d'un côté, soit elle l'est de l'autre !

![capture d ecran 2016-01-14 a 11 13 19](https://cloud.githubusercontent.com/assets/10072454/12321780/4a2c4ba0-bab0-11e5-9d5a-5f889d250540.png)

![capture d ecran 2016-01-14 a 11 13 40](https://cloud.githubusercontent.com/assets/10072454/12321778/450cc172-bab0-11e5-9c9e-4e2fd8271138.png)

**Comment by Fchallier** [comment]
Oui car l'image est n'est pas de la même taille sur les deux pages...et le recadrage se fait au centre.

Pour corriger le problème il faudrait soit créer un nouveau champ image dédié uniquement à la page récap' soit faire en sorte que le cadrage se fasse uniquement d'un côté...

**Comment by Rouergue** [comment]
Pb de format non homothétique aussi pour la colonne récap' avec les vignettes des autres fabriques (à gauche).

![capture d ecran 2016-01-27 a 09 30 44](https://cloud.githubusercontent.com/assets/10072454/12617753/5eba08a8-c511-11e5-88c3-8eb5ecaae438.png)
