### ISSUE TITLE
L'un des titres prévus le 2 mars n'apparaît pas sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#240]
Alors que les deux autres titres prévus au même office remontent bien (y compris d'ailleurs, certains titres qui paraissent plus tard). Quid ? Est-ce c'est parce que le prix déf' n'a pas été validé dans mistral ? 
![capture d ecran 2016-01-21 a 10 23 38](https://cloud.githubusercontent.com/assets/10072454/12476359/0eafa7a6-c029-11e5-8c25-db0f54440da8.png)

**Comment by Fchallier** [comment]
Et oui il me semble bien que cela vient du fait que le prix def n'a pas été renseigné...

**Comment by Fchallier** [comment]
Faire la modif dans mistral et vérifier la semaine prochaine.

**Comment by Rouergue** [comment]
Ok. C'est effectivement parce qu'Alzira n'a pas encore confirmé le tirage et le prix. 
Affaire à suivre, donc...
