### ISSUE TITLE
Pourquoi certaines photos auteurs ne s'affichent pas correctement ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#241]
Il y a un petit logo qui indique que l'image est pourtant bien présente et, en ré-ouvrant l'image dans photoshop, je vois que celle-ci est aux bonnes dimensions et en RVB. Quid ?

![capture d ecran 2016-01-27 a 12 17 00](https://cloud.githubusercontent.com/assets/10072454/12617647/ea3257e2-c510-11e5-9dd2-5c6223b0994a.png)
![13286](https://cloud.githubusercontent.com/assets/10072454/12617666/f7caeaea-c510-11e5-82af-fcd46dd20ed8.jpg)

**Comment by Fchallier** [comment]
Je ne vois pas trop d'où vient le problème... J'ai rajouté à la main la photo... 

Je laisse ouvert le ticket si le cas se reproduit

**Comment by Rouergue** [comment]
Euh... tu n'as pas mis la bonne photo ! Pour Suzy Lee, c'est la photo 13286 (jpeg ci-joint) et non pas 13268 (photo qui correspond à Fabienne Juhel). Comment fais-tu pour la rajouter à la main ? Car j'ai eu le pb aussi pour d'autres auteurs...

**Comment by Rouergue** [comment]
La photo de Suzy Lee n'apparaît toujours pas sur le site, malgré le ré-enregistrement du fichier en format web. Quid ? Voici le cartouche qui s'affiche au moment de l'enregistrement
![capture d ecran 2016-02-03 a 10 04 55](https://cloud.githubusercontent.com/assets/10072454/12777516/dbdaa13e-ca5d-11e5-8aba-0a636c3af4a1.png)
Le problème peut-il venir de là ?

**Comment by Rouergue** [comment]
il s'agit de l'auteur ID 13286

**Comment by Fchallier** [comment]
Impossible pour moi d'ouvrir le visuel présent sur le serveur...  tu peux m'envoyer le fichier source  ?

**Comment by Fchallier** [comment]
ça sera ok à la prochaine mise à jour
