### ISSUE TITLE
Dans "à lire aussi", les images ne se mettent pas dans l'ordre demandé

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#242]
![capture d ecran 2016-01-27 a 14 54 29](https://cloud.githubusercontent.com/assets/10072454/12617705/1ab87ffe-c511-11e5-9211-1d20718fcc7a.png)

![capture d ecran 2016-01-27 a 14 54 38](https://cloud.githubusercontent.com/assets/10072454/12617714/21c6c972-c511-11e5-8fde-d4b21045a2b3.png)

**Comment by Fchallier** [comment]
Tu peux me donner le titre du livre en question  ?

**Comment by Rouergue** [comment]
C'était sur le titre L'ILE DES CHASSEURS D'OISEAUX mais, voyant que les couvs ne se mettaient pas dans l'ordre souhaité, je n'ai finalement laissé que le livre illustré et l'intégral des 3 titres.
http://www.lerouergue.com/catalogue/lile-des-chasseurs-doiseaux

**Comment by Fchallier** [comment]
Je viens de faire quelques tests et ça fonctionne chez moi... 

Pense  à cliquer sur le petit logo en haut à droite pour faire du drag & drop.
![dragg](https://cloud.githubusercontent.com/assets/9974750/12641389/9746cba4-c5af-11e5-8e31-b9adb7b78229.jpg)

**Comment by Fchallier** [comment]
Par contre l'ordre est inversé, c'est le dernier livre ajouté qui s'affiche en premier
