### ISSUE TITLE
Quelles sont les références de la couleur du fond gris du site, stp ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#244]
J'étais partie sur #f2f2f2 mais ça m'a l'air d'être un gris un peu plus clair...

**Comment by Fchallier** [comment]
Non non le fond du site est bien #F2F2F2

**Comment by Rouergue** [comment]
quand je mets ce fond sous les pages issuu, ça fait un petit décalage pourtant.
Enfin, ce n'est pas si moche ! 

![capture d ecran 2016-01-28 a 16 12 27](https://cloud.githubusercontent.com/assets/10072454/12648378/00827fd0-c5da-11e5-9844-38f31c3faee7.png)
