### ISSUE TITLE
Mention du lien vers la version numérique

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#245]
Lorsque l'on met un lien pour renvoyer vers la version numérique, est-il possible de supprimer la mention "Version numérique" dans la colonne de droite sur la fiche livre, sachant qu'il y a déjà la mention en rouge "disponible aussi en numérique". Ça fait un peu double emploi.

![capture d ecran 2016-01-28 a 16 35 49](https://cloud.githubusercontent.com/assets/10072454/12649089/64b138e0-c5dd-11e5-9d8c-51bd6129bccb.png)
![capture d ecran 2016-01-28 a 15 47 35](https://cloud.githubusercontent.com/assets/10072454/12649094/67bcb41a-c5dd-11e5-8b57-27306f65259a.png)

**Comment by Fchallier** [comment]
Oui sans soucis
