### ISSUE TITLE
Pb de mise à jour qui ne prend pas en compte les bonnes couvs

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#246]
c'est le cas pour les trois couvs suivantes

9782812601323.jpg
9782812602092.jpg
9782812607530.jpg

Ce ne sont pas les bonnes qui s'affichent à l'écran sur le site alors que les bons fichiers sont bien sur le serveur. 

![capture d ecran 2016-01-28 a 14 28 38](https://cloud.githubusercontent.com/assets/10072454/12777320/77ffecba-ca5c-11e5-960b-f864829d96f0.png)

![capture d ecran 2016-02-03 a 09 57 14](https://cloud.githubusercontent.com/assets/10072454/12777336/872321da-ca5c-11e5-8c0f-61e9ad3d6e84.png)

Peut-être que pour ces 3 couvs-là, j'ai fait une mise à jour directe du visuel via l'admin. du site sans faire gaffe (comme quand je mets des photos auteurs à la place d'une case vide) ? Je ne sais pas... Peut-on corriger le tir sans attendre la mise à jour de mercredi prochain ?

**Comment by Fchallier** [comment]
je viens de vider le cache des image, et j'ai l’impression que ça corrigé le problème
