### ISSUE TITLE
Pb d'affichage du texte (mots collés)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#248]
À nouveau, on retrouve ce problème de mots collés au niveau du texte de présentation de l'auteur alors que c'est nickel dans mistral. Quid ?

![capture d ecran 2016-02-24 a 15 50 27](https://cloud.githubusercontent.com/assets/10072454/13289050/de6d78d8-db0e-11e5-9258-d13b1b0abac9.png)

**Comment by Fchallier** [comment]
Je viens de faire une petite modification dans la code. A vérifier à la prochaine mise à jour. 

Mais dans Mistral le texte n'est pas vraiment nickel.... Il y a une multitude de sauts de lignes... Notamment aux endroits où les mots sont collés.
