### ISSUE TITLE
Pb de taille d'image pour l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#249]
Dans la partie administrateur, la taille minimum requise est 550 x 380

![capture d ecran 2016-03-01 a 11 08 38](https://cloud.githubusercontent.com/assets/10072454/13423912/21a2c606-df9e-11e5-962c-ef47a886caf0.png)

Or, l'affichages des vignettes sur le site correspond à 265 x 170 (ce qui n'est pas proportionnel au format imposé). Du coup, les vignettes sont un peu massicotées à l'affichage. 

![capture d ecran 2016-03-01 a 11 11 16](https://cloud.githubusercontent.com/assets/10072454/13423968/56455d7e-df9e-11e5-9140-676c01f3c3c0.png)
![capture d ecran 2016-03-01 a 11 10 57](https://cloud.githubusercontent.com/assets/10072454/13423973/5aa55720-df9e-11e5-9511-00f8c8e8e8db.png)

**Comment by Fchallier** [comment]
Je viens de configurer le redimensionnement d'image à  265*183 pour les visuels d'agenda. 
Et ça me semble bien fonctionner.

**Comment by Rouergue** [comment]
Sauf que quand je veux télécharger une image au niveau de l'interface administrateur, cela me la refuse (le téléchargement est bloqué pcq l'image est trop petite). 

![capture d ecran 2016-03-02 a 12 06 33](https://cloud.githubusercontent.com/assets/10072454/13458745/6627f522-e06f-11e5-839c-8982bd5b1abf.png)

**Comment by Fchallier** [comment]
Oui mais il ne faut pas changer le format lors de l'envoi.  il faut toujours envoyer une image en 550x380 et le site se charge du redimensionnement.
