### ISSUE TITLE
Pourquoi un titre interdit à la vente remonte-t-il sur le site ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#250]
![capture d ecran 2016-03-02 a 11 05 40](https://cloud.githubusercontent.com/assets/10072454/13457135/c9e36c80-e066-11e5-877d-5ced5aaf5010.png)
![capture d ecran 2016-03-02 a 11 05 47](https://cloud.githubusercontent.com/assets/10072454/13457140/cbe2ea2e-e066-11e5-91cf-cee9e2cc74c2.png)

**Comment by Fchallier** [comment]
#135
