### ISSUE TITLE
Nouveau pb d'affichage sur un nom auteur

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#253]
Pourtant, il me semble que le nom s'affichait correctement avant la mise à jour de la photo...

![capture d ecran 2016-03-09 a 10 53 17](https://cloud.githubusercontent.com/assets/10072454/13631487/3c0ee964-e5e5-11e5-9d8a-a1e0e976c505.png)

**Comment by Fchallier** [comment]
C'était à cause de ma correction que j'avais réaliser pour le "OE".
