### ISSUE TITLE
AGENDA : pb de taille des images

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#254]
Pourquoi les logos que je souhaite importer dans le corps du message d'un événement à 100 pixels de large s'affichent plein pot (550 px) sur la page des événements de l'agenda ?

![capture d ecran 2016-03-09 a 14 08 20](https://cloud.githubusercontent.com/assets/10072454/13636189/d3b56aa2-e600-11e5-82c3-0167e9df0035.png)

![capture d ecran 2016-03-09 a 14 08 09](https://cloud.githubusercontent.com/assets/10072454/13636187/d04678e8-e600-11e5-8bcb-bc72a764cdbc.png)

**Comment by Fchallier** [comment]
C'est vraiment space, car lors de l'ajout de l'image ça renseigne bien les dimensions, mais lorsque tu enregistres ça semble disparaitre.... 

Il y a une petite parade cela, quand tu es dans l’explorateur de fichier tu peux cliquer sur le bouton "Redimensionner"  et créer une nouvelle image à partir de celle que tu as envoyée.

![rouergue_redim](https://cloud.githubusercontent.com/assets/9974750/13637579/5eef78a4-e608-11e5-958f-4e1b69c44643.jpg)

**Comment by Rouergue** [comment]
Ok. Ça fait une manip' de plus mais bon ! S'il n'y a pas d'autres solutions... ;-)
