### ISSUE TITLE
Le retour à la ligne dans mistral

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#255]
Est-ce que, si je fais un retour à la ligne dans mistral comme ci-dessous, celui-ci sera pris en compte sur le site ? 

![capture d ecran 2016-03-10 a 12 22 37](https://cloud.githubusercontent.com/assets/10072454/13668120/e0199a38-e6ba-11e5-89a6-3f2d656bcc95.png)

**Comment by Fchallier** [comment]
Donc comme dit au tel c'est un oui  :)

**Comment by Rouergue** [comment]
Apparemment, ça n'a pas marché.
Le saut de ligne ne s'affiche pas sur le site...

![capture d ecran 2016-03-16 a 11 33 36](https://cloud.githubusercontent.com/assets/10072454/13809452/41300e92-eb6b-11e5-9283-9fbcaeca9653.png)

![capture d ecran 2016-03-16 a 11 34 45](https://cloud.githubusercontent.com/assets/10072454/13809456/45a065b2-eb6b-11e5-97d6-502ca52c374d.png)

**Comment by Fchallier** [comment]
Le saut de ligne est bel et bien respecté. 
Mais si tu veux que cela ressemble à un nouveau paragraphe il faut rajouté un saut de ligne supplémentaire.
