### ISSUE TITLE
Texte qui disparaît

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#257]
Sur plusieurs titres, le texte disparaît, malgré les fiches mistral bien complètes et mon rajout de texte à la main dans drupal. Quid ?
C'est le cas au moins pour les titres suivants :

- Environnement mortel
- Depuis le temps de nos pères
- Promenade du crime
- Les hamacs de carton
- La vengeance de Laura

![capture d ecran 2016-03-16 a 11 00 09](https://cloud.githubusercontent.com/assets/10072454/13808563/0231077c-eb67-11e5-9dd3-303471162e86.png)
![capture d ecran 2016-03-16 a 11 00 51](https://cloud.githubusercontent.com/assets/10072454/13808567/055e59b8-eb67-11e5-8ba5-15e58e43c877.png)
![capture d ecran 2016-03-16 a 11 00 33](https://cloud.githubusercontent.com/assets/10072454/13808569/07bc7adc-eb67-11e5-81ce-77ef732bf195.png)

> texte sur mistral ok
![capture d ecran 2016-03-16 a 11 06 46](https://cloud.githubusercontent.com/assets/10072454/13808601/3717cd90-eb67-11e5-8389-27c672eb6a54.png)

> rajouté à la main la semaine dernière
![capture d ecran 2016-03-10 a 14 13 53](https://cloud.githubusercontent.com/assets/10072454/13808572/0f991eea-eb67-11e5-95a7-782a0edfe6b3.png)

**Comment by Fchallier** [comment]
Pour rappel la règle est la suivante : Si le champ 4 de couv est vide dans mistral, alors c'est la petite phrase qui est affichée.  Et si le champ n'est pas vide, alors c'est celui-ci qui est affiché.

Et pour les titres que tu viens de m'envoyer, Il y a des balises cachées dans les 4 de couv dans Mistral... faut faire attention au copier-coller... 


![bug_backcover_rouergue](https://cloud.githubusercontent.com/assets/9974750/13809652/07301146-eb6c-11e5-8ff0-bb35c3658304.jpg)
