### ISSUE TITLE
pourquoi un epub apparaît-il au milieu des livres papier de littérature ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#258]
![capture d ecran 2016-03-23 a 09 39 25](https://cloud.githubusercontent.com/assets/10072454/13979807/3208eda6-f0db-11e5-9482-1bd2d5e65c65.png)

idem au niveau de la coll. la brune, du coup

![capture d ecran 2016-03-23 a 09 43 46](https://cloud.githubusercontent.com/assets/10072454/13979910/c8eebde0-f0db-11e5-9d76-c49963ea2360.png)

**Comment by Fchallier** [comment]
Alors le pourquoi je ne sais pas... mais en dans tous les cas je vais supprimer cette fiche, l'epub est en interdit à la vente dans Mistral.

**Comment by Rouergue** [comment]
Ok, j'ai vu avec Diane d'où ça venait (suppression, après coup, d'un titre déjà remonté). 
T'embête pas pour la suppression de fiche, je vais le faire.
Merci.
