### ISSUE TITLE
AGENDA : je ne peux plus enregistrer d'événements

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#259]
Est-ce parce que tu es en train de faire la mise à jour ? 
À chaque fois que je veux enregistrer mes données, cela me met ça : 

![capture d ecran 2016-03-30 a 10 41 36](https://cloud.githubusercontent.com/assets/10072454/14136650/33c17968-f664-11e5-9276-c2e33a7f93c9.png)

**Comment by Fchallier** [comment]
Heu ben j'ai lancé la mise à jour ce matin... vers 9h45... 
Mais si tu tentes d'envoyer une image ça peu générer une erreur... étant donné notre connexion internet ultra-rapide depuis ce matin... (joke)

**Comment by Rouergue** [comment]
Ok. Apparemment, ça s'est débloqué !

**Comment by Rouergue** [comment]
Pourras-tu me prévenir quand la mise à jour du serveur sera terminée, stp ?
Parce que ça bogue à nouveau (et, effectivement, ça rame beaucoup, d'une manière générale !).
Fais-tu finalement les mises à jour du serveur le mercredi matin ? C'est juste pour savoir, pour que j'organise mon travail en fonction. 
Thanks !
