### ISSUE TITLE
NOUVEAUTÉS : pb d'ordre des images

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#260]
Les livres ne se mettent pas dans l'ordre désiré sur la page d'accueil.

J'aimerais que ce soit comme ça

![capture d ecran 2016-03-30 a 13 25 47](https://cloud.githubusercontent.com/assets/10072454/14145186/328ac58e-f693-11e5-90ea-5ec79b6cf630.png)

Et ça me donne ça

![capture d ecran 2016-03-30 a 15 14 59](https://cloud.githubusercontent.com/assets/10072454/14145198/3ff505fe-f693-11e5-9b08-3b822d2eede1.png)
![capture d ecran 2016-03-30 a 15 15 03](https://cloud.githubusercontent.com/assets/10072454/14145197/3ff463ce-f693-11e5-9fcd-ee194971ed4e.png)
![capture d ecran 2016-03-30 a 15 15 09](https://cloud.githubusercontent.com/assets/10072454/14145199/3ff9a320-f693-11e5-8c58-bd0b148f861b.png)

**Comment by Rouergue** [comment]
Pourquoi, alors que je souhaite que TROOOMMMPFF apparaisse après LE MENSONGE et que cet ordre est bien enregistré dans la partie admin, cela n'apparaît pas à l'écran ?

![capture d ecran 2016-04-06 a 09 32 37](https://cloud.githubusercontent.com/assets/10072454/14309125/ad6c9fba-fbda-11e5-85f0-54acf7415055.png)

![capture d ecran 2016-04-06 a 09 34 05](https://cloud.githubusercontent.com/assets/10072454/14309136/c5a211dc-fbda-11e5-844d-60bcbf53838e.png)

**Comment by Fchallier** [comment]
J'ai fait une petite correction et normalement ça ne devrait plus poser de problèmes.
