### ISSUE TITLE
AGENDA : ajout d'un pays

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#262]
Comment puis-je faire pour ajouter un (ou des) pay(s) au menu déroulant des adresses ? Dans l'immédiat, j'ai besoin de rajouter ALLEMAGNE.

**Comment by Rouergue** [comment]
Help ! Aurais-tu le temps de rajouter (ou de me dire comment faire), le pays Allemagne à la liste des pays dans l'agenda, stp ? Parce que, pour l'instant, München s'affiche en Belgique... ça la fout mal ! 
Merci beaucoup,

![capture d ecran 2016-05-03 a 12 18 07](https://cloud.githubusercontent.com/assets/10072454/14982266/7b189f62-1135-11e6-98b4-372cbabde929.png)

**Comment by Fchallier** [comment]
C'est ok je viens de faire la mise à jour. 
Malheureusement tu ne peux pas faire la manipulation sur le site, car ce type d'information ne peut être modifié uniquement en local sur mon ordinateur, puis upload sur la version en ligne.

Il faudra à chaque fois ouvrir un ticket.... 

Désolé pour les autres Tickets je n'ai pas encore eu le temps de les traiter, je suis surchargé avec le développement de Payot & Rivages...
