### ISSUE TITLE
Pb d'affichage multiple d'événements dans l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#265]
Et ils sont impossible à supprimer. Quid ? 

![capture d ecran 2016-05-23 a 10 29 10](https://cloud.githubusercontent.com/assets/10072454/15465366/768ccf00-20d4-11e6-85d4-862a3881c3f9.png)

![capture d ecran 2016-05-23 a 10 29 06](https://cloud.githubusercontent.com/assets/10072454/15465371/796a5288-20d4-11e6-8a38-75495da7dd47.png)

**Comment by Fchallier** [comment]
Il y a eu probablement un petit problème lors de la création de l'événement.. Si tu as cliqué plusieurs fois sur "Enregistré" par exemple, en grande partie à cause de notre connexion internet qui est dans les choux.... 

J'ai supprimé les doublons dans la partie Admin
