### ISSUE TITLE
THÈMES : affichage des thèmes en double

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#267]
Quid ?

![capture d ecran 2016-06-08 a 14 07 55](https://cloud.githubusercontent.com/assets/10072454/15893883/ccb95eec-2d82-11e6-80c7-c73deb125bba.png)

**Comment by Fchallier** [comment]
Il me semble que cela vient du lectorat... Quand il y a un double lectorat j'ai l'impression que cela double les Themes.... je regarde sur ma version en local si je peux corriger cela...

**Comment by Fchallier** [comment]
Humm... le fait d'uniquement réenregistrer la fiche du livre sans rien modifier fait disparaître les doublons... alors là...

**Comment by Rouergue** [comment]
Sauf que ça revient ensuite... 
Car à nouveau ce matin, il y avait les thèmes en double. J'ai réenregistré la fiche du livre sans rien modifier et, effectivement, les thèmes ne sont plus doublés. Par contre, c'est un peu contraignant s'il faut y revenir tous les jours :-)
Affaire à suivre...

**Comment by Fchallier** [comment]
Oui j'avais remarqué également, à chaque mise à jour cela revient...... Mais le gros le problème c'est que sur ma version locale je n'arrive pas à reproduire le bug... Je cherche toujours... désolé

**Comment by Fchallier** [comment]
Je viens de faire quelques configuration sur le site, il me faut attendre demain aprés la mise à jour pour vérifier si l'ensemble fonctionne bien.

**Comment by Fchallier** [comment]
Oui la méthode que j'ai utilisé n'a pas fonctionné... Je cherche encore...
