### ISSUE TITLE
Livre qui disparaît de la bibliographie d'un auteur, par endroit...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#268]
Sur la fiche de José Parrondo, on retrouve bien le livre NATIONALE 0 dans sa bibliographie. Par contre, lorsqu'on va sur le livre MIROLIOUBOV (de José Parrondo), le livre NATIONALE 0 disparaît de la bibliographie qui défile en bas de page (http://www.lerouergue.com/catalogue/mirolioubov). Quid ?

![capture d ecran 2016-06-14 a 09 35 43](https://cloud.githubusercontent.com/assets/10072454/16034748/bde3b1b6-3213-11e6-83bb-a4154f4b66bf.png)

![capture d ecran 2016-06-14 a 09 36 22](https://cloud.githubusercontent.com/assets/10072454/16034754/c2de2160-3213-11e6-97aa-cc78f2222368.png)

**Comment by Fchallier** [comment]
C'est Ok je viens de corriger cela. 
En fait le filtre n'afficher uniquement les livre dont l'auteur était principal.
