### ISSUE TITLE
Illustrateur non communicable qui apparaît sur l'un des cartouches

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#271]
Pour l'album LE GRAND SPECTACLE, seule Claire Franek doit apparaître (Marc Daniau étant mentionné "non communicable" sur mistral). Or, sur le cartouche noir surgissant au niveau de la page CATALOGUE, les 2 noms apparaissent. Quid ? 

![capture d ecran 2016-07-12 a 10 03 49](https://cloud.githubusercontent.com/assets/10072454/16759900/8444c8f2-4819-11e6-999f-b25dfd7bd45d.png)

![capture d ecran 2016-07-12 a 10 04 04](https://cloud.githubusercontent.com/assets/10072454/16759902/87837d9c-4819-11e6-9b30-2df5a9b129cf.png)

**Comment by Fchallier** [comment]
Hummm il doit y avoir un problème au niveau du dump et / ou au niveau du module de migration. 

Il faut que je regarde cela... ( big stuff)
