### ISSUE TITLE
Bio auteur qui n'a pas été prise en compte sur le site malgré la mise à jour dans mistral

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#272]
Hello ! 
La mise à jour du site a-t-elle été faite ce matin ? 
Car la bio de Didier Aussibal, pourtant renseignée hier sur mistral n'apparaît pas sur le site. Pour être plus exacte, elle a même disparu pcq j'avais également rentré la bio sur le site, parallèlement à mistral. Cela a-t-il fait interférence comme pour les photos auteurs ? Je croyais qu'on pouvait faire des changements directement dans les cartouches de l'admin du site, en attendant la mise à jour hebdomadaire du serveur...

![capture d ecran 2016-08-24 a 10 29 27](https://cloud.githubusercontent.com/assets/10072454/17923918/98fa8c48-69e6-11e6-8a38-d2e547ae245f.png)

![capture d ecran 2016-08-24 a 10 29 24](https://cloud.githubusercontent.com/assets/10072454/17923923/9d89a776-69e6-11e6-8e21-03615a5114dd.png)

**Comment by Fchallier** [comment]
Hello  ! 
La mise à jour c'est bien lancer, mais je viens de me rendre compte que j'ai fait une erreur sur le nom du fichier du dump... Je relance tout de suite la mise à jour.  Ça sera donc corrigé d'ici quelque minutes
