### ISSUE TITLE
Auteurs qui apparaissent en double

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#273]
Pourquoi les auteurs apparaissent-ils deux fois (en auteur et en illustrateur) alors que seules les mentions "auteur" sont spécifiées sur mistral ?

![capture d ecran 2016-08-24 a 12 02 12](https://cloud.githubusercontent.com/assets/10072454/17926745/b642e654-69f2-11e6-8de2-adc995497c8b.png)

![capture d ecran 2016-08-24 a 12 02 08](https://cloud.githubusercontent.com/assets/10072454/17926748/b819bb06-69f2-11e6-950a-8c3bfc2531f9.png)

**Comment by Fchallier** [comment]
Pour ce genre de problème, Drupal ne peut  pas supprimer automatiquement les auteurs qui ont changé de fonction. C'est pour cela qu'il y avait encore les deux noms d'auteur en illustrateur. 

Quand tu rencontre se genre de probablement il faut malheureusement retirer sur la fiche du livre dans Drupal les deux auteurs qui ne conviennent pas.

**Comment by Rouergue** [comment]
ok, c'est noté !
