### ISSUE TITLE
URGENT : ajout d'un pays dans la liste disponible sur l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#274]
Il faudrait rajouter l'ITALIE, stp.
Merci !

![capture d ecran 2016-09-13 a 09 36 42](https://cloud.githubusercontent.com/assets/10072454/18465174/ab5d8552-7995-11e6-9a26-f38f368825d0.png)

**Comment by Fchallier** [comment]
C'est normalement ok

**Comment by Rouergue** [comment]
C'est super, merci.
Juste un petit truc : le nom de la province (qu'il faut obligatoirement renseigner après la ville, dans le formulaire), est coupé à l'affichage... Il faudrait agrandir un peu le bloc, stp.

![capture d ecran 2016-09-13 a 11 14 00](https://cloud.githubusercontent.com/assets/10072454/18468237/45df34b0-79a3-11e6-912b-68cbf6a510df.png)

**Comment by Fchallier** [comment]
Je viens de regarder il n'y pas moyen de changer cette option....c'est le site qui a généré l'abréviation 

Mais en même temps il me semble que c'est normal : https://fr.wikipedia.org/wiki/Liste_des_provinces_et_villes_m%C3%A9tropolitaines_italiennes_par_r%C3%A9gion

**Comment by Rouergue** [comment]
Ah ? Bah ok, alors. 
Ça fait bizarre, mais si c'est normal, alors je m'incline !
