### ISSUE TITLE
Titre manquant dans la collection ASSASSINS SANS VISAGES

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#275]
Pourquoi le titre "La trace du sang" n'apparaît pas dans la coll. "Assassins sans visages" alors qu'il est bien mentionné dans la série correspondante sur mistral ?

![capture d ecran 2016-09-14 a 16 48 53](https://cloud.githubusercontent.com/assets/10072454/18517128/9194eeec-7a9b-11e6-80f8-2e356f42b9dc.png)

![capture d ecran 2016-09-14 a 16 49 13](https://cloud.githubusercontent.com/assets/10072454/18517132/94b4f4dc-7a9b-11e6-96d2-63d6d3bfee82.png)

**Comment by Rouergue** [comment]
(pour _L'île au rébus_, c'est normal car il est à paraître en avril 2017).

**Comment by Fchallier** [comment]
humm... je ne sais pas trop pourquoi il avait sauté... J'ai rajouté à la main son univers et lancé la mise à jour du site. 

ça semble fonctionner.
