### ISSUE TITLE
Pourquoi le photographe n'apparaît pas ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#277]
Alors qu'il est bien coché communicable dans mistral ? 

![capture d ecran 2016-09-21 a 15 24 18](https://cloud.githubusercontent.com/assets/10072454/18712613/91d1cfaa-800f-11e6-9f5a-b5bca8b935b3.png)

![capture d ecran 2016-09-21 a 15 23 27](https://cloud.githubusercontent.com/assets/10072454/18712618/9511fae6-800f-11e6-849c-b04371040460.png)

C'est pour le titre BRAGUETTES

**Comment by Fchallier** [comment]
La requête utilisé pour l'import des données mistral est bien la bonne... 
![rqt-sql](https://cloud.githubusercontent.com/assets/9974750/18744518/ab512b4c-80be-11e6-9c77-b7cd5becaf6d.jpg)

Il faut que je regarde pourquoi il ne l'affiche pas....
