### ISSUE TITLE
Est-il possible de mettre en place un système de duplicata de fiche événement ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#280]
Ce serait super utile lorsqu'il y a plusieurs rencontres d'une auteur, sur le même modèle, à des dates et des endroits différents. Il n'y aurait plus que 2,3 infos à changer sur une fiche "pré-remplie" !

![capture d ecran 2016-10-10 a 11 01 43](https://cloud.githubusercontent.com/assets/10072454/19231191/f24a017c-8ed8-11e6-8ada-0b43feaf7bb5.png)

**Comment by Rouergue** [comment]
Hello ! Peux-tu me rajouter le petit bouton magique de duplication d'une fiche, stp ?
Thanks a lot !

![capture d ecran 2016-11-03 a 15 45 36](https://cloud.githubusercontent.com/assets/10072454/19970638/e870edd4-a1dc-11e6-8e31-e25c686d01fd.png)

**Comment by Fchallier** [comment]
C'est ok pour le duplicata de contenu.  Tu a maintenant un lien "Clone content" pour cloner le contenu que tu souhaites.

**Comment by Rouergue** [comment]
Merci beaucoup ! Mais euh... À quel niveau exactement se trouve le lien ? Je ne le vois pas...

**Comment by Fchallier** [comment]
Je viens de regarder tu n'avais pas les droits en fait... C'est corrigé. 
Il apparait juste en dessous de "Voir Modifier"
