### ISSUE TITLE
Affichage des résultats de la recherche

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#281]
sous forme de vignette-image (avec une ligne en-dessous d'intitulé) ?

![capture d ecran 2016-10-11 a 15 53 24](https://cloud.githubusercontent.com/assets/10072454/19272960/f47f8956-8fca-11e6-8bbc-538605c47691.png)

Présentation sur 2 colonnes : image à gauche et titre + description à droite.

**Comment by Rouergue** [comment]
Les vignettes pourraient faire 45 pixels de haut, pas plus, juste pour permettre de dissocier, d'un coup d'œil, les pages livres, des pages auteurs, des événements...

![recherche-vignettes](https://cloud.githubusercontent.com/assets/10072454/21106170/57b04aa4-c08d-11e6-8826-087d29f5f59f.png)
 
L'idéal serait l'ordre d'apparition suivant : PAGE AUTEUR puis PAGES LIVRES puis FABRIQUE puis ÉVENEMENTS (agenda).

**Comment by Fchallier** [comment]
Doublon avec #295
