### ISSUE TITLE
La recherche ne fonctionne plus...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#282]
Mais peut-être est-ce parce que tu es justement en train de travailler dessus ? 

![capture d ecran 2016-10-12 a 16 06 57](https://cloud.githubusercontent.com/assets/10072454/19313229/10de9cec-9096-11e6-81f7-840d6454abe7.png)

**Comment by Fchallier** [comment]
Oui j'ai ajouté le seul module qui existe pour faire des recherche partielles en Français... mais celui-ci ne semble pas fonctionné...

**Comment by Fchallier** [comment]
J'ai désactivé le module les recherches fonctionnent à nouveau
