### ISSUE TITLE
Le nom des auteurs est passé sous le texte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#283]
quid ?

![capture d ecran 2016-10-13 a 10 51 56](https://cloud.githubusercontent.com/assets/10072454/19342703/341bb576-9133-11e6-8360-9f42aac7df9d.png)

**Comment by Fchallier** [comment]
Hum je n'ai rien chez moi.... 
![bugrouergue](https://cloud.githubusercontent.com/assets/9974750/19342874/ffde563c-9133-11e6-9b67-ddefb0b3ddd3.jpg)

**Comment by Rouergue** [comment]
C'est bizarre, ça le fait encore chez moi (même après avoir vidé le cache) mais pas sur tous les titres. Très étrange...

![capture d ecran 2016-10-13 a 12 03 06](https://cloud.githubusercontent.com/assets/10072454/19345082/2bb425d0-913d-11e6-94cc-fb21629fb575.png)

![capture d ecran 2016-10-13 a 12 02 59](https://cloud.githubusercontent.com/assets/10072454/19345087/342852c2-913d-11e6-8de7-86253ac6a713.png)

Je vais essayer de redémarrer le navigateur pour voir si ça change quelque chose...

**Comment by Fchallier** [comment]
C'est ok je viens de corrigé le bug, ça devrait aitre bon sur l'ensemble du site maintenant :)
