### ISSUE TITLE
Au secooooours !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#285]
Pb d'affichage du texte dans la partie CITATION PRESSE.

![capture d ecran 2016-10-17 a 09 23 11](https://cloud.githubusercontent.com/assets/10072454/19428638/7727fe2c-944b-11e6-9e07-a3da7ff1790f.png)

![capture d ecran 2016-10-17 a 09 23 35](https://cloud.githubusercontent.com/assets/10072454/19428640/7c5979a2-944b-11e6-89e5-c7bb5519087f.png)

**Comment by Fchallier** [comment]
Le problème est corrigé non  ? C'était un mauvais copié/collé  ?

**Comment by Rouergue** [comment]
Non, c'est un bug d'affichage car le texte apparaissait bien à l'origine. Mais, même en vidant le cache, ça n'a rien changé. Il a fallu que je redémarre le navigateur pour que le pb disparaisse. Apparemment, c'est rentré dans l'ordre…

**Comment by Rouergue** [comment]
À nouveau ce matin, je suis confrontée au problème : ça fait ça apparemment dès qu'il y a du bold. 

![capture d ecran 2016-10-18 a 11 35 21](https://cloud.githubusercontent.com/assets/10072454/19472311/0979b3ca-9527-11e6-9c52-4812d7cf89f8.png)
![capture d ecran 2016-10-18 a 11 06 28](https://cloud.githubusercontent.com/assets/10072454/19472315/0d008d98-9527-11e6-8980-4797584eacc7.png)

**Comment by Fchallier** [comment]
Tu peux me donner le titre  ? sinon je ne peux pas vérifier le bug

**Comment by Rouergue** [comment]
ça le fait à peu près sur tout, dès qu'il y a du bold (alors qu'il n'y a aucun pb d'affichage quand c'est du bold + ital !). Je suis en train de mettre à jour les pages statiques et c'est le même cirque ! Ça complique sacrement la partie admin' !

![capture d ecran 2016-10-18 a 11 47 39](https://cloud.githubusercontent.com/assets/10072454/19473023/05e15706-952a-11e6-85dd-639c29341939.png)

**Comment by Fchallier** [comment]
Je n'arrive pas a avoir le même bug... 
![screen_bug_rouergue](https://cloud.githubusercontent.com/assets/9974750/19475949/e8e2e3d8-9536-11e6-8d28-ab4c9d6c107e.jpg)

je peux passer cet après-midi pour voir cela ensemble si tu veux
