### ISSUE TITLE
Pb d'homothétie entre les différents affichages des vignettes de l'Agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#287]
Le format des vignettes sur les pages récap' est 265 x 183 pixels alors que cette même vignette affichée en grand dans chaque page événement fait 555 x 370. Les proportions n'étant pas les mêmes, cela massicote les images qui s'affichent en grand.

![capture d ecran 2016-11-16 a 09 57 00](https://cloud.githubusercontent.com/assets/10072454/20340962/69adf0d4-abe4-11e6-9baa-17e48b213d96.png)

![capture d ecran 2016-11-16 a 09 56 11](https://cloud.githubusercontent.com/assets/10072454/20340965/6c501574-abe4-11e6-946a-eaf0fbf5aaa1.png)

Il faudrait que l'affichage en grand sur les pages événements fasse 555 x 383,45 pour que ce soit équivalent.

**Comment by Rouergue** [comment]
ou 550 x 380 pour un compte juste !

**Comment by Fchallier** [comment]
C'est ok  550 x 383  pour avoir les bonnes proportions
