### ISSUE TITLE
Affichage de la mention "disponible en numérique"

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#288]
Lorsqu'un EPUB est rattaché à un livre "papier", la mention "disponible en numérique" ne s'affiche-t-elle pas automatiquement sur la fiche du livre ? 

![capture d ecran 2016-11-21 a 10 26 39](https://cloud.githubusercontent.com/assets/10072454/20477271/2a3dedd8-afd5-11e6-950a-5cb0170355b0.png)

![capture d ecran 2016-11-21 a 10 26 24](https://cloud.githubusercontent.com/assets/10072454/20477280/2f136df6-afd5-11e6-9407-c2625195996a.png)

**Comment by Fchallier** [comment]
Si justement, mais il faut renseigner le champ "Version numérique" dans la fiche livre....
