### ISSUE TITLE
Création d'une série supplémentaire pour les poches

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#289]
Au niveau des équivalences drupal-mistral, il faudrait associer les titres dont la sous-collection est (dans mistral) ROUERGUE EN POCHE **et** la série est ASSASSINS SANS VISAGES aux deux univers :

- littérature > polars > assassins sans visages
- littérature > romans > rouergue en poche

Cela concerne trois titres pour le moment : _La trace du sang, Terreur dans les vignes_ et _Le mort aux quatre tombeaux_ (les fiches ont bien été mises à jour dans mistral avec la création de série).

![capture d ecran 2016-11-21 a 14 41 16](https://cloud.githubusercontent.com/assets/10072454/20484798/329b911e-aff9-11e6-89f7-1dda8d59e28c.png)

**Comment by Fchallier** [comment]
Mapping modifié, il faudra vérifier à la prochaine mise à jour

**Comment by Rouergue** [comment]
Apparemment, ça n'a pas fonctionné car rien n'a changé depuis la mise à jour du serveur. Les poches "polars" n'apparaissent pas davantage dans la rubrique "assassins sans visages". 

![capture d ecran 2016-11-23 a 09 40 29](https://cloud.githubusercontent.com/assets/10072454/20569895/ef133442-b1a1-11e6-91d3-6e4524a83c89.png)

**Comment by Fchallier** [comment]
C'est ok ! Les titres sont présent dans  : 

    littérature > polars > assassins sans visages
    littérature > romans > rouergue en poche

"La trace du sang" ne s’affiche pas car dans mistral  la date est à avril  2017
