### ISSUE TITLE
Affichage de la coll. Rouergue Noir au premier niveau du menu du site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#290]
Il faudrait "remonter" la collection "Rouergue Noir" au premier niveau du menu du site, juste sous la rubrique "La brune". En mettant une capitale à "R", si possible. 

![capture d ecran 2016-11-21 a 14 48 36](https://cloud.githubusercontent.com/assets/10072454/20485129/7d59233c-affa-11e6-8ec8-25867c1a90a5.png)

Cet affichage ne serait qu'un "duplicata" de la rubrique qui, elle, reste bien dans le menu : 
Littérature > polars > rouergue noir

![capture d ecran 2016-11-21 a 14 48 51](https://cloud.githubusercontent.com/assets/10072454/20485185/b9b99b7c-affa-11e6-89b0-afcb8be95edb.png)

**Comment by Fchallier** [comment]
Je vais faire la mise à jour sur le site.  Et le livres s'afficheront à partir de demain matin

**Comment by Rouergue** [comment]
C'est super, François. Juste, est-ce que tu peux passer "Rouergue Noir" SOUS "La brune", stp, comme sur le modèle ci-dessus. Sinon on risque d'avoir des conflits diplomatiques...
Merci beaucoup !

**Comment by Rouergue** [comment]
En fait, je vais décaler la rubrique moi-même, via le menu STRUCTURE (j'avais oublié que j'avais la main à ce niveau-là !). J'espère qu'au niveau du mapping, ça ne va pas créer de problème si je le déplace. Tu me dis ?

**Comment by Fchallier** [comment]
Non ça ne change rien au niveau du mapping  ;)
