### ISSUE TITLE
Connexion à FileZilla

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#292]
À chaque nouvelle connexion, je suis obligée de remettre le mot de passe et celui-ci n'est pas gardé en mémoire à la fin de chaque session. Comment faire pour que ce soit enregistré automatiquement ? 

![capture d ecran 2016-11-22 a 13 59 52](https://cloud.githubusercontent.com/assets/10072454/20524723/1caa1c18-b0bc-11e6-860f-2f47bd7e55d9.png)

**Comment by Fchallier** [comment]
Il te faut aller dans le menu : Fichier -> Gestionnaire de Sites... -> (Le site Rouergue ) -> Et au niveau de "Type d'authantification" -> Selectionner "Normal"
Puis renseigner le mot de passe dans le champs prévu à cet effet. 

![filezilla](https://cloud.githubusercontent.com/assets/9974750/20526336/e626aa50-b0c3-11e6-8ae2-f9cf61e59ff3.png)

**Comment by Rouergue** [comment]
Ça ne marche paaaaaas ! Apparemment la sauvegarde des mots de passe est désactivée et j'ai cherché dans les paramètres de FileZilla pour la réactiver, mais je n'ai pas trouvé à quel niveau ça se situe. 

![capture d ecran 2016-11-23 a 09 59 25](https://cloud.githubusercontent.com/assets/10072454/20555734/cb138bb6-b163-11e6-89fd-d668cde3d583.png)

**Comment by Fchallier** [comment]
Et si tu va dans Édition -> Paramètres.. -> Interface -> Et tu décoche la case "Ne pas sauvegarder les mots de passe" ?

**Comment by Rouergue** [comment]
Oui, ça marche ! Merci beaucoup :-)
