### ISSUE TITLE
Rubrique qui n'englobe pas tous les titres

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#293]
La rubrique POLARS (dans LITTÉRATURE) ne présente que 3 titres. Or elle devrait reprendre le contenu de la rubrique ASSASSINS SANS VISAGES + les titres de la rubrique ROUERGUE NOIR, non ? 

![capture d ecran 2016-11-23 a 09 40 29](https://cloud.githubusercontent.com/assets/10072454/20555244/4669e3bc-b161-11e6-86f0-b7cbd9453c95.png)

Par ailleurs, il faudrait rajouter un "S" à "visage" dans le nom de la coll. "Assassins sans visages", stp.

**Comment by Rouergue** [comment]
Pour le "s" à rajouter, j'ai vu que je pouvais le faire moi-même via le menu Structure. C'est donc fait !

**Comment by Fchallier** [comment]
Il y avait une petite erreur dans la mapping , ça me semble ok
