### ISSUE TITLE
Suppression d'un sous-univers

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#294]
Dans le menu du site, au niveau de l'univers RÉGION, il faudrait supprimer l'affichage du sous-univers ROMANS (avec les sous-catégories : estive / témoignages / rouergue en poche). Sachant que cet univers ROMANS se trouve également et doit rester dans la LITTÉRATURE. 

![capture d ecran 2016-11-29 a 14 32 59](https://cloud.githubusercontent.com/assets/10072454/20711620/febfe928-b640-11e6-8910-a41c4be7806c.png)

![capture d ecran 2016-11-29 a 14 26 57](https://cloud.githubusercontent.com/assets/10072454/20711616/f9586d70-b640-11e6-8aac-afe33fed956c.png)

J'ai essayé de le faire moi-même via la taxonomie dans Structure, mais je n'ai pas la main pour supprimer des rubriques. 

Ce changement ne devrait pas avoir d'incidence sur l'arborescence des coll. et sous-coll. dans mistral puisque cet affichage dans l'univers RÉGION était un "dupli" de rubriques présentes par ailleurs en Litté.

**Comment by Rouergue** [comment]
François, est-ce possible de supprimer la partie "ROMANS" de l'univers "RÉGIONS" comme spécifié ci-dessus ?

**Comment by Fchallier** [comment]
Univers dépublié sur le site.

**Comment by Rouergue** [comment]
Merci François. Je vois que le menu a bien été supprimé mais, par contre, quand on clique sur le premier niveau RÉGION, les vignettes des romans s'affichent toujours dans la page récap' de la rubrique. Quid ? Peux-tu supprimer cet affichage aussi, stp ?

![capture d ecran 2017-01-23 a 13 54 07](https://cloud.githubusercontent.com/assets/10072454/22204721/bfda0e38-e173-11e6-919b-1fc8aa9e4d36.png)

**Comment by Fchallier** [comment]
Il me semble que c'est bon  :)

**Comment by Rouergue** [comment]
Les livres ont bien été supprimés de la sous-rubrique "romans" dans RÉGIONS, mais les intitulés et les menus apparaissent toujours dans le déroulé. Peux-tu le supprimer, stp ? 

![Capture d’écran 2019-11-27 à 15 30 54](https://user-images.githubusercontent.com/10072454/69732809-97b9f080-112c-11ea-9427-0654aafa4624.png)

Pour récapituler, il ne doit y avoir que les sous-rubriques RÉGIONS DE FRANCE / AVEYRON / VOYAGES dans la rubrique RÉGIONS. La sous-rubrique ROMANS ne doit plus y apparaître.

**Comment by Fchallier** [comment]
Je viens de désactiver la taxonomie dans le menu. 
Donc l’univers  Roman (+les sous-rubrique)  dans RÉGIONS
