### ISSUE TITLE
RECHERCHE : ne prendre en compte que le début du mot

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#295]
Est-il possible de faire la recherche sur quelques lettres et non pas sur le mot entier ? Par exemple, si qqn tape "autodafeur" sans "s" dans le champ RECHERCHE, le site ne donne aucun résultat, ce qui est fort ennuyeux ! Seule la mention "autodafeurs" avec l'orthographe complète (et au pluriel) permet d'accéder aux différents résultats. 

![capture d ecran 2016-12-01 a 11 18 48](https://cloud.githubusercontent.com/assets/10072454/20791227/429f58b4-b7bc-11e6-823a-41cb96e49f52.png)

![capture d ecran 2016-12-01 a 11 49 05](https://cloud.githubusercontent.com/assets/10072454/20791236/498c2896-b7bc-11e6-858d-facbf5be509b.png)

Cf. "Recherche sur un mot partiel #114"

**Comment by Fchallier** [comment]
Bon j'ai cherché des modules de recherche partielle mais ça ne fonctionne pas vraiment... 

Mais j'ai trouvé un module plutôt intéressant. Ça utilise le système d’auto-complétion, c'est-à-dire que dès que tu va commencer à taper les premières lettres de ta recherche, ça va te proposer plusieurs résultats. ( voir la capture) 
![autocomplet_rouergue](https://cloud.githubusercontent.com/assets/9974750/22212624/b2302416-e191-11e6-9fa1-490538f824fe.jpg)

Si cette idée te convient je peux continuer mes recherches pour  améliorer les résultats de ce module ( affiche les couverture etc... )

**Comment by Rouergue** [comment]
Ah oui, c'est bien ça ; ça fait un bon compromis...
On y va comme ça ! Merci !
(et tu crois qu'on pourrait avoir les types de résultats en français : "author, anonymous", etc. ?)

**Comment by Fchallier** [comment]
Oui oui, il faut que je configure et traduise le module. Car là c'est la version de base.

**Comment by Fchallier** [comment]
Ok je viens de mettre en place le module, j'ai rajouté un petit visuel pour afficher la couverture + les 90 premiers caractères de la petite phrase. 

Je peux rajouter un filtre pour afficher uniquement les livres et les auteurs ?

**Comment by Rouergue** [comment]
Merci pour ces améliorations, c'est chouette ! 

Pour la fenêtre surgissante en haut à droite, je mettrais peut-être la typo des titres (en noir) dans un corps un peu plus petit et en supprimant (à cet endroit) les premiers caractères de la petite phrase. Parce que, du coup, je trouve que ça fait très imposant pour une fenêtre-extension-de-la-recherche. Je ne garderais que la petite vignette de couv' (ou photo auteur) à gauche et le titre à droite, justifié sur le haut de l'image + le type d'article, en orange par exemple (fiche livre, auteur, événement, fabrique, etc.). Comme ça :

![cartouche-extension-recherche](https://cloud.githubusercontent.com/assets/10072454/22252931/16bb6dd2-e250-11e6-9ed8-42d72f0e14a8.png)

Ensuite, quand on ne clique pas sur les propositions qui s'affichent mais sur "voir tous les résultats" en bas, cela ne donne aucun résultat. Peux-tu corriger ce bug, stp ? 

![capture d ecran 2017-01-24 a 16 01 53](https://cloud.githubusercontent.com/assets/10072454/22253028/6ae00a3a-e250-11e6-9bf9-4ab2f30eba58.png)

![capture d ecran 2017-01-24 a 16 00 13](https://cloud.githubusercontent.com/assets/10072454/22253033/6de41a5a-e250-11e6-8dd6-f98970265531.png)

Enfin, pour en venir à la page de recherche "grand écran", je trouve que c'est effectivement bien ici de mettre les 90 premiers caractères de la petite phrase. Peut-on aussi rajouter l'image de la vignette (livre, auteur ou événement) à côté ? 

![capture d ecran 2017-01-24 a 16 00 36](https://cloud.githubusercontent.com/assets/10072454/22253104/a4c926be-e250-11e6-96f6-bf9eb39ee76a.png)

ça pourrait donner qqch comme ça : 

![57b04aa4-c08d-11e6-8826-087d29f5f59f](https://cloud.githubusercontent.com/assets/10072454/22253180/e670e458-e250-11e6-93dd-a44bc8a8a08a.png)

L'idéal serait l'ordre d'apparition suivant : PAGE AUTEUR puis PAGES LIVRES puis FABRIQUE puis ÉVENEMENTS (agenda). Cf. #281 

Je suis à ta dispo pour discuter de tout ça de vive voix si tu préfères.
Merci et à plus tard !

**Comment by Rouergue** [comment]
Et pour répondre à ta question sur le filtre pour afficher uniquement les livres et les auteurs, j'ai peur que ça alourdisse encore un peu la recherche rapide ("fenêtre-extension" en haut à droite) mais pourquoi pas proposer le filtre livres-auteurs-évenements au niveau de la "grande page" de recherche. Il faudrait voir ce que ça peut donner...

**Comment by Rouergue** [comment]
La recherche ne semble plus prendre en compte les premières lettres seulement et ne fait pas de propositions (avec vignettes des livres) comme avant. Est-ce dû au changement de serveur ?

![Capture d’écran 2020-11-12 à 15 57 26](https://user-images.githubusercontent.com/10072454/98956014-d7c1e100-24ff-11eb-96a2-557a3fcc82a1.png)

**Comment by Fchallier** [comment]
le ticket est un peu vieux mais, la recherche semble bien fonctionner.
Bien à toi,
