### ISSUE TITLE
Pb d'affichage du texte dans les pages auteurs 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#296]
Lorsqu'une bio, copiée dans mistral, n'a pas été "nettoyée" auparavant avec la suppression des styles, des bandes blanches apparaissent ensuite sur le site. Est-il possible de prévoir un "ménage" automatique dans le dump pour que le texte soit homogénéisé à chaque fois, sans que j'ai besoin de retourner dans mistral pour faire les corrections ? 

![capture d ecran 2016-12-08 a 09 42 33](https://cloud.githubusercontent.com/assets/10072454/21004400/6c94f70e-bd30-11e6-934d-b1940f9d477e.png)

**Comment by Fchallier** [comment]
Okay ça semble fonctionner  :)
