### ISSUE TITLE
Résumé différent pour les titres papier et les epub

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#297]
Pour les fiches livres, le résumé correspond à la 4e de couverture par défaut et à la petite phrase mistral le cas échéant. Apparemment, seule la petite phrase mistral est prise en compte pour les versions epub. Est-ce possible d'harmoniser (4e pour les deux versions) ? 
Merci beaucoup ! 

![capture d ecran 2017-01-16 a 16 15 08](https://cloud.githubusercontent.com/assets/10072454/21989102/fbc151aa-dc09-11e6-9ff2-76ab131c3d54.png)

![capture d ecran 2017-01-16 a 16 15 01](https://cloud.githubusercontent.com/assets/10072454/21989112/03451fa6-dc0a-11e6-9172-7718c5fd99f6.png)

**Comment by Fchallier** [comment]
Ben c'est déjà le cas en fait... C'est juste que sur la fiche E-pub la 4e de couv n'est pas renseignée dans Mistral... Donc ça affiche la petite phrase.
