### ISSUE TITLE
Nouvelle édition qui ne remonte pas sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#298]
La nouvelle édition de BENJAMIN ET SES COPAINS (9782812611957) ne remonte pas sur le site (alors que le prix déf' est bien confirmé dans mistral). Par contre, il y a toujours l'ancienne version (9782812605772) qui, elle, est épuisée. 

![capture d ecran 2017-01-18 a 12 07 33](https://cloud.githubusercontent.com/assets/10072454/22061897/52b388d4-dd77-11e6-9f7d-f0fe18a57540.png)

![capture d ecran 2017-01-18 a 12 08 26](https://cloud.githubusercontent.com/assets/10072454/22061900/562c340c-dd77-11e6-9507-2e98cb8cd49f.png)

**Comment by Fchallier** [comment]
Ok après plusieurs  recherche je viens de trouver. 

Il y a avait plusieurs erreur dans notre base de données... Je viens de faire le ménage et fiche livre c’est bien intégré sur le site.

```
****** Partie technique ***********
-Message lors du : drush mi article --update -> Incoming node ID (id) no longer exists

-Recherche dans la base de données drupal les tables contenant le node ID en question, puis suppression de toutes les écritures comportant ce node. 

-Lancer à nouveau le cron pour l'import des données Mistral. 
```
