### ISSUE TITLE
ACTUALISATION DES FICHES

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#300]
La mise à jour du serveur a-t-elle eu lieu ? Car j'ai fait des modif' sur mistral la semaine dernière qui n'apparaissent pas sur le fiche livre. Quid ?

![capture d ecran 2017-02-08 a 15 43 32](https://cloud.githubusercontent.com/assets/10072454/22741987/821ae532-ee15-11e6-9948-c79774b87cf4.png)

![capture d ecran 2017-02-08 a 15 43 02](https://cloud.githubusercontent.com/assets/10072454/22741999/84eefe56-ee15-11e6-8518-4156e736a5ed.png)

**Comment by Fchallier** [comment]
Non non elle c'est normalement bien lancé... Dans ce cas je vais en lancer une nouvelle dans quelque minutes et vérifier que les donnée sont à jour.
