### ISSUE TITLE
Illustrateur qui n'apparaît pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#301]
Alors qu'il est bien coché "communicable" dans mistral. Pourquoi ne remonte-t-il pas sur la fiche livre du site ? 

![capture d ecran 2017-02-20 a 11 08 32](https://cloud.githubusercontent.com/assets/10072454/23120546/0dbe7036-f75d-11e6-9f6b-e7e660cfacf3.png)

![capture d ecran 2017-02-20 a 11 08 49](https://cloud.githubusercontent.com/assets/10072454/23120552/13487a56-f75d-11e6-8a36-27dfcf3ace25.png)

**Comment by Rouergue** [comment]
Et, du coup, je ne peux pas faire de lien de l'agenda vers l'illustrateur !

**Comment by Fchallier** [comment]
OK ay
