### ISSUE TITLE
URGENT : ajout du nom des traducteurs et préfaciers

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#302]
Sur la fiche livre du CHARDON ET LE BLEUET, il faudrait rajouter finalement les préfaciers et traducteurs cochés communicables dans mistral. Je les avais supprimés car je pensais que ce n'était pas indispensable de tous les mettre mais l'éditrice souhaite tout de même qu'ils apparaissent dans la colonne de droite (même s'il n'y a pas de liens vers leurs bios). Peut-on les réintégrer dans le prochain dump ? Comment faire ? 
Merci par avance pour ton aide précieuse ! 

![capture d ecran 2017-02-21 a 16 26 51](https://cloud.githubusercontent.com/assets/10072454/23171474/df887c60-f852-11e6-9021-85a0b84d210f.png)

![capture d ecran 2017-02-21 a 16 24 33](https://cloud.githubusercontent.com/assets/10072454/23171482/e2bf046c-f852-11e6-954c-73caf1996d80.png)

**Comment by Fchallier** [comment]
Je suis dessus depuis ce matin... j'ai testé les requêtes de l'import des données et tout est bon.... 

Il doit y avoir un conflit avec les élément liées... je continue mes recherches.

**Comment by Fchallier** [comment]
Je viens de corriger le problème  !!!  Ainsi que du bug où il y avait les contributeurs liés vides...

Je me note un petit pense bête si le problème réapparaît : 

Lors du passage du cron, vérifier l'ensemble des erreurs de type "Incoming node ID no longer exists", regarder l'id Mistral du contributeur qui pose problème.   Puis faire un rollback pour supprimer les données précédemment insérés et relancer le cron
`
/* teste si ce sont bien les id qui posent problème */ 

drush mi contributor --update --idlist=3617,4773,6375,6821,11350,11351,11462,11504,12610,12703,12704,13044,13097,13393,13783,13790,13795,13801,13803,13805,13808,13811,13812,13816,13819,13823,13825,13830,13831,13833,13835,13838,13839,13843,13847,13853,13859,14697,14698,14699,15135,15392,20675,20708,20811,21224,22253,22878,23142,23143,23167,23174,23289,23295,23457,23480



/* Faire le rollback */

drush mr contributor --idlist=3617,4773,6375,6821,11350,11351,11462,11504,12610,12703,12704,13044,13097,13393,13783,13790,13795,13801,13803,13805,13808,13811,13812,13816,13819,13823,13825,13830,13831,13833,13835,13838,13839,13843,13847,13853,13859,14697,14698,14699,15135,15392,20675,20708,20811,21224,22253,22878,23142,23143,23167,23174,23289,23295,23457,23480

`

**Comment by Rouergue** [comment]
Ok, merci.
Juste une petite question à ce sujet : Penses-tu qu'il soit possible de faire apparaître le nom des traducteurs et préfaciers comme actuellement, en colonne de droite, sans que cela créé pour autant les fiches auteurs correspondantes ? Il me semblait qu'on avait décidé de faire apparaître les noms des traducteurs, photographes & co à droite mais sans rendre les noms "cliquables", sans qu'il y ait de lien en fait, vers les pages auteurs. Tu me dis ?

![capture d ecran 2017-02-23 a 09 37 14](https://cloud.githubusercontent.com/assets/10072454/23251024/ee4ad496-f9ab-11e6-874b-9fff8d0c7685.png)

![capture d ecran 2017-02-23 a 09 36 52](https://cloud.githubusercontent.com/assets/10072454/23251028/f2feab02-f9ab-11e6-9cdf-c78b2228e97b.png)

**Comment by Fchallier** [comment]
Ce n'est pas cliquable chez moi...

**Comment by Rouergue** [comment]
Oui, effectivement, ce n'est pas directement cliquable. Mais si on fait une recherche sur le nom du photographe, celui-ci apparaît dans la base de données et la fiche auteur s'affiche. On ne peut pas faire autrement, c'est bien ça ?
