### ISSUE TITLE
Pb d'affichage au niveau du © pour les photos auteurs

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#303]
Alors que le champ est bien renseigné dans la partie admin, cela ne s'affiche pas correctement sur la page auteur. Quid ?

![capture d ecran 2017-02-22 a 12 07 59](https://cloud.githubusercontent.com/assets/10072454/23209020/b1e76f28-f8f7-11e6-96b3-9dc497472484.png)
![capture d ecran 2017-02-22 a 12 08 07](https://cloud.githubusercontent.com/assets/10072454/23209021/b20c7f20-f8f7-11e6-9b7f-3f9fd36b6533.png)

**Comment by Fchallier** [comment]
Je n'arrive pas à avoir le même bug...

**Comment by Fchallier** [comment]
Je viens de vérifier sur plusieurs auteurs, et je n'arrive pas à reproduire le même bug... N'hésites pas à ré ouvrir le ticket si cela se reproduit.
