### ISSUE TITLE
Mise à jour de visuel de couverture non prise en compte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#304]
J'ai mis à jour 2 couvertures hier sur le site (+ fichiers basculés sur le serveur via FileZilla) et, ce matin, elles ont disparu ! Quid ? J'ai pourtant vidé les caches & co.

![capture d ecran 2017-03-02 a 12 15 11](https://cloud.githubusercontent.com/assets/10072454/23505007/28a04888-ff42-11e6-9d3f-eaef53400b82.png)

![capture d ecran 2017-03-02 a 12 17 23](https://cloud.githubusercontent.com/assets/10072454/23505020/372af948-ff42-11e6-9a30-f3e1d8d79be4.png)

**Comment by Fchallier** [comment]
En fait il faut déposer les couv le mardi soir, car la mise à jour se lance le mercredi matin.

Je viens de lancer une nouvelle mise à jour  ;)
