### ISSUE TITLE
Suppression des fiches auteurs "parasites"

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#307]
Je viens de faire un grand ménage sur le site, en supprimant toutes les fiches d'auteurs secondaires et/ou non rattachées aux livres. Peux-tu me confirmer que les fiches ne vont pas remonter à la prochaine mise à jour du serveur, stp ? (sachant que les auteurs ne sont pas cochés "communicables" dans mitral). Car j'ai l'impression avoir déjà fait ce boulot de nettoyage et que les fiches sont quand même remontées après-coup !
Merci pour cette précision. 

Petite question subsidiaire : peut-on supprimer une fiche auteur sans que cela supprime la mention dudit auteur sur la fiche d'un livre (dans la colonne de droite). Exemple pour les photographes, par exemple ?

**Comment by Fchallier** [comment]
J'ai fait une petite mise à jour au niveau du code et lancé une mise à jour des données. 

Tu pourra me donner certain exemples ?
