### ISSUE TITLE
Illustrateur de couv' qui apparaît sur l'encadré surgissant d'un livre de littérature

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#310]
Alors qu'il ne devrait y avoir que le nom de l'auteur. Quid ? 
Cf. #306 

![capture d ecran 2017-06-14 a 11 25 12](https://user-images.githubusercontent.com/10072454/27125308-2a96dfc2-50f4-11e7-9ee3-fe16b0475f28.png)

![capture d ecran 2017-06-14 a 11 25 17](https://user-images.githubusercontent.com/10072454/27125307-2a9501f2-50f4-11e7-99d4-169d18343deb.png)

**Comment by Rouergue** [comment]
C'est bizarre, j'ai toujours les deux auteurs qui s'affichent sur le cartouche. J'ai pourtant bien vidé tous les caches... Est-ce juste un bug d'affichage de mon côté ?

**Comment by Fchallier** [comment]
C'est ok.  Maintenant l'illustrateur s'affiche uniquement s'il est communicable
