### ISSUE TITLE
Texte incomplet au niveau de l'importation

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#311]
cf.  #308 
![capture d ecran 2017-04-06 a 16 48 10](https://user-images.githubusercontent.com/10072454/27125405-70d4d35e-50f4-11e7-9190-a8f1c3b12596.png)

**Comment by Fchallier** [comment]
Fonction preg_replace mal configuré et coupure du texte au niveau du mot style...
