### ISSUE TITLE
Pourquoi les pnb pdf web remontent au niveau du catalogue ? 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#312]
Normalement ils ne doivent apparaître que dans la rubrique NUMÉRIQUE, non ?

![capture d ecran 2017-06-28 a 10 47 54](https://user-images.githubusercontent.com/10072454/27628458-5f914aea-5bef-11e7-9ebc-ba57ecc265c2.png)

**Comment by Fchallier** [comment]
Ah... C'est un nouveau format qui vient d’être crée dans Mistral et il n'est pas pris en compte par nos requêtes... Je vais devoir faire la modification sur l'ensemble de nos site... 

Je clos le ticket quand c'est corrigé.
