### ISSUE TITLE
URGENT : pb de livre qui ne remonte pas sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#313]
Il s'agit de MA BOISSON PROBIOTIQUE MAISON (9782812612619). Pourtant, le prix a bien été validé par Alzira dans Mistral. Quid ? 

![capture d ecran 2017-08-02 a 15 00 16](https://user-images.githubusercontent.com/10072454/28874760-7a97bb16-7793-11e7-8518-a6df1f4cf40a.png)

**Comment by Fchallier** [comment]
C'est ok aprés une nouvelle mise à jour
