### ISSUE TITLE
Seul 1 des 2 auteurs apparaît sur le cartouche dans les pages récap'

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#314]
Au niveau de la rubrique CATALOGUE. Pourtant l'auteur ET l'illustrateur apparaissent bien sur la fiche livre. Quid ? 

![capture d ecran 2017-08-01 a 11 46 53](https://user-images.githubusercontent.com/10072454/28877234-1076a838-779c-11e7-9f56-0d2a5d9166bd.png)

![capture d ecran 2017-08-01 a 11 46 58](https://user-images.githubusercontent.com/10072454/28877235-13346d08-779c-11e7-9627-1df3cbcc88aa.png)

**Comment by Fchallier** [comment]
On s'est peut-être mal compris  ? => #310

**Comment by Rouergue** [comment]
Non, non, ce sont deux situations différentes.
Pour L'OISEAU BLANC (qui est un album jeunesse), il faut bien que l'auteur & l'illustrateur apparaissent sur le cartouche gris alors que pour le cas traité en #310, il s'agit d'un titre de littérature dans La brune sur lequel le nom de l'illustrateur de couverture ne doit pas apparaître (tout comme sur la fiche livre où il ne s'affiche pas). 
N'hésite-pas à me rappeler si ce n'est pas clair !

![27125307-2a9501f2-50f4-11e7-99d4-169d18343deb](https://user-images.githubusercontent.com/10072454/28880853-8ea5e73c-77a6-11e7-9222-7343d21ec41b.png)

**Comment by Fchallier** [comment]
C'est ok et même pour le #310
