### ISSUE TITLE
Nouveau pb de livre qui ne remonte pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#315]
Il s'agit maintenant de QUAND LES VÊTEMENTS RACONTENT (9782812612121). Pourtant bien validé par Alzira. Est-ce le même problème qu'hier ? Peux-tu y jeter un coup d'œil, stp ?
(et me préciser éventuellement les infos impératives qui doivent être validées dans mistral pour que le livre remonte, quand le prix déf' est vérifié).
Merci !

![document](https://user-images.githubusercontent.com/10072454/28912761-ddfa2994-7835-11e7-84f2-d4fad0182760.jpg)

**Comment by Fchallier** [comment]
Oui il faut que le prix soit vérifié.  Dans la requête il est bien mentionné :  iscurrentprice='1'

Et pour ce titre la modification a été réalisé aujourd'hui.  J'envoie donc un nouveau Dump et lance une Maj.

**Comment by Rouergue** [comment]
Je vois bien la fiche livre (en faisant une recherche globale) mais celui-ci n'apparaît pas dans la rubrique CATALOGUE. Est-ce normal ?

![capture d ecran 2017-08-03 a 15 19 29](https://user-images.githubusercontent.com/10072454/28923772-6d4628a4-785f-11e7-969d-7acdfb0f3785.png)

![capture d ecran 2017-08-03 a 15 21 37](https://user-images.githubusercontent.com/10072454/28923782-7643a2f6-785f-11e7-9712-124b6917df84.png)

**Comment by Fchallier** [comment]
![sans-titre-1](https://user-images.githubusercontent.com/9974750/28958818-21ab3a08-78f8-11e7-90cb-1ac4879ce839.png)
