### ISSUE TITLE
Ajout d'un format d'image dans l'admin de l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#316]
Serait-il possible de rajouter le format .jpg pour l'ajout des fichiers dans la rubrique "PROGRAMME" de l'interface des événements ? La plupart des affiches (et certains programmes) que je récupère sont en jpg ou png et cela me prend du temps de les convertir en pdf pour que le transfère puisse fonctionner. Tu me dis ?
Merci beaucoup !

![capture d ecran 2017-08-28 a 15 10 40](https://user-images.githubusercontent.com/10072454/29775735-9af13a0e-8c06-11e7-80d0-6f5777f6b14e.png)

**Comment by Fchallier** [comment]
Ajout du format jpg, png et jpeg
