### ISSUE TITLE
Un même auteur apparaît deux fois

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#319]
> sur la fiche livre, alors que, dans mistral, il n'est mentionné qu'une seul fois. Quid ?

![capture d ecran 2017-09-12 a 09 13 03](https://user-images.githubusercontent.com/10072454/30312790-50684af4-979b-11e7-8275-6c6591012456.png)

![capture d ecran 2017-09-12 a 09 13 27](https://user-images.githubusercontent.com/10072454/30312792-52337e80-979b-11e7-994c-a7107bfd2a40.png)

**Comment by Fchallier** [comment]
Je viens de regarder, c'est étrange car son statut à changer et au lieu de la mettre à jour sur le site ça l'a rajouté. 

J'ai fait une petite modification on verra si cela fonctionne bien demain après la mise à jour.
