### ISSUE TITLE
Rubrique manquante

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#321]
Pourquoi la rubrique "du même auteur" n'apparaît pas sur cette fiche livre ?

![capture d ecran 2017-09-18 a 15 31 53](https://user-images.githubusercontent.com/10072454/30586690-1a4a72c6-9d31-11e7-851b-c8d703fe9214.png)

**Comment by Fchallier** [comment]
Surement dû au problème des auteurs de la semaine dernière
