### ISSUE TITLE
Peut-on ajouter une vidéo sur une page auteur ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#322]
J'ai essayé sur la page d'Irène Cohen-Janca en me mettant en mode html et en l'insérant sous la bio. Mais, comme c'était prévisible, la vidéo a disparu à la mise à jour hebdomadaire ! Comment faire ? Certaines vidéos sont rattachées à un auteur plus qu'à un titre. Peut-on rajouter un champ média sur la fiche auteur ?

**Comment by Rouergue** [comment]
J'ai pas mal d'auteur avec des vidéos-interview que j'aimerais pouvoir mettre sur leur page. Penses-tu que ce soit compliqué (et/ou long) de rajouter un champ "embed video - liseuse" sur les pages auteurs ? Merci par avance !

**Comment by Fchallier** [comment]
Hello, je m'occupe de ça dès maintenant, normalement ça ne devrait pas trop me prendre de temps.

**Comment by Fchallier** [comment]
Je viens de rajouter le champ, sur les fiches auteurs. Donc même principe que pour les livres, Cliquer sur "source" puis copier/coller le code embed et cliquer à nouveau sur "source". Puis enregistrer la fiche contributor.

![screenshot-2017-11-13 gornet thomas rouergue](https://user-images.githubusercontent.com/9974750/32729881-959411c4-c885-11e7-9abd-0e1c50d6c385.png)
