### ISSUE TITLE
URGENT : pb de mise en forme d'un nouvel intitulé d'événement

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#324]
J'ai créé l'intitulé "spectacle" pour les événements mais celui-ci ne s'affiche pas comme d'habitude. Comment faire pour lui attribuer une couleur et qu'il soit dans la même taille et polices que les autres types d'événements ? 

![capture d ecran 2017-10-19 a 11 28 19](https://user-images.githubusercontent.com/10072454/31764250-e7b2b88a-b4c0-11e7-9745-377e47da1058.png)

**Comment by Fchallier** [comment]
C'est dans le code du site...Une couleur est attribuée pour chaque  type d’événement.. 

Je viens d'appliquer une correction et ça devrait être bon.
