### ISSUE TITLE
auteur qui apparaît en double

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#325]
Quid ?

![capture d ecran 2017-11-07 a 16 31 44](https://user-images.githubusercontent.com/10072454/32501792-42abe992-c3d9-11e7-9cf7-c78ca259e57a.png)

**Comment by Fchallier** [comment]
Un rollback vient d’être réaliser... 

Je lance une mise à jour pour vérifier que toutes les informations sont bien à jour. 

S'il y a encore des doublons, une mise à jour du Module Migrate sera réalisé

Work in progress

**Comment by Fchallier** [comment]
Il n'y a plus de doublon sur le site et je n'ai pas eu besoin de faire une mise à du module. 

Je ne vois pas d'anomalie lors de la mise à jour... donc je ne comprends pas trop l'origine des doublons. 

Par si tu as renseigné une fois un auteur sur une fiche livre à la main, cela expliquerait les doublons. J'ai supprimé l'obligation que l'auteur sur la fiche d'un livre, pour éviter le message d'erreur quand tu enregistres une fiche livre. 

Bien à toi,
