### ISSUE TITLE
Image qui ne s'est pas mise à jour correctement

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#327]
Il s'agit de LES HÉROÏNES DE CINÉMA SONT PLUS COURAGEUSES QUE MOI (9782812615146). La bonne couv' a été remplacée dans FileZilla la semaine dernière mais la mise à jour ne s'affiche pas sur le site.

![capture d ecran 2017-11-15 a 12 11 10](https://user-images.githubusercontent.com/10072454/32833115-18e53aa2-c9fe-11e7-985d-909a870e6dbc.png)

![capture d ecran 2017-11-15 a 12 08 55](https://user-images.githubusercontent.com/10072454/32833100-07eb5d44-c9fe-11e7-8e36-8fc8aea36092.png)

**Comment by Fchallier** [comment]
Ajout de la commande "Image-flush" après la mise à jour hebdomadaire. 

Vide toutes les images misent en cache.
