### ISSUE TITLE
Automatisation de la mention "disponible aussi en numérique"

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#329]
Pourrait-il y avoir un système d'automatisation de la mention "disponible aussi en numérique" sur les pages livres dont les versions numériques remontent sur le site ? 
Actuellement, je dois le faire manuellement à chaque fois.

**Comment by Fchallier** [comment]
En fait il n'y a pas grand intérêt à ce que les Epub remontent sur le site non  ?

Pourquoi ne pas supprimer définitivement les Epub du site, et remplacer cela par un lien automatique sur la fiche papier vers la fiche numérique d'Eden  ?  C'est ce que j'ai fait pour Payot et Rivages... 

N'hésites pas à m'appeler quand tu as 5 minutes pour voir cela ensemble.

**Comment by Fchallier** [comment]
Suppression des univers numérique -> ok
Suppression définitive des fiches de type ebook -> ok 
Ajout d'un lien automatique vers la fiche Numérique Eden -> ok

Mémo : 
Numérique - cdf5215e-8b85-4f0c-9f68-9ee517392c16
- doado - faaf7a44-b11c-478a-b05f-e2ca1892f5b7
- doado noir - 4269d4f5-45c0-4629-abab-b5d15e824200
- epik - 8c1782e1-88a6-4aac-87d7-4d29ed483c9b
- la brune - ce61d6fc-faa2-47f8-a6e9-976257d809d8
- dacodac - 0af3c4aa-630d-48a0-98ca-51752eba0778
- polars - 2796300b-4322-4e79-8dcf-f3d7447c31dd
- romans - 13c26811-5ade-4018-b8bb-5642b42fc1da
