### ISSUE TITLE
Impossible d'enregistrer une fiche sans supprimer le champ contributeur vide

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#336]
à nouveau, le pb s'est posé avec la fiche ci-dessous :

![capture d ecran 2017-12-13 a 14 10 39](https://user-images.githubusercontent.com/10072454/33941067-93ea0060-e011-11e7-8aeb-302f4cd3ee0a.png)

J'ai été obligée de supprimer le champ pour pouvoir enregistrer les modifs apportées à la fiche.

**Comment by Fchallier** [comment]
J'avais changé le condition pour tester une fonctionnalité.
