### ISSUE TITLE
Ajout d'une mention dans l'affichage de l'agenda sur les pages auteurs

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#337]
Serait-il possible de rajouter l'affichage du type d'événement sur les pages auteurs (dans la même couleur et typo que sur le récap' de l'agenda) ? Cf. exemple ci-dessous.

![capture d ecran 2017-12-13 a 11 34 55](https://user-images.githubusercontent.com/10072454/33941291-6f4ed540-e012-11e7-9999-dd20b510c02a.png)

![capture d ecran 2017-12-13 a 11 34 33](https://user-images.githubusercontent.com/10072454/33941293-7080a614-e012-11e7-91de-92bc0a52cc02.png)

Car si je le rajoute moi-même dans le titre (exple "rencontre avec A. Seurat"), cela fait doublon au niveau de l'affichage dans l'agenda ("RENCONTRE" et en dessous "Rencontre avec A. Seurat"). Et si je ne mets que le nom de l'auteur dans l'agenda, ça fait bizarre au niveau du récap' des dates sur la page auteur... 

![capture d ecran 2017-12-13 a 14 34 15](https://user-images.githubusercontent.com/10072454/33941383-b725de2c-e012-11e7-9fea-a3dd1d44580a.png)

N'hésite-pas à m'appeler si ce n'est pas clair !

**Comment by Fchallier** [comment]
Je viens de faire un Update :)
