### ISSUE TITLE
Un événement dans l'agenda ne s'affiche pas (code erreur)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#338]
Je pensais que c'était une histoire de cache qui de doit se vider mais le pb subsiste depuis hier. Pourtant, j'ai fait comme d'habitude... D'où cela peut-il venir ? 

![capture d ecran 2017-12-14 a 09 45 21](https://user-images.githubusercontent.com/10072454/33983280-d9a7ccd4-e0b3-11e7-8d94-cf0b3e717ea6.png)

![capture d ecran 2017-12-14 a 09 46 37](https://user-images.githubusercontent.com/10072454/33983276-d873252a-e0b3-11e7-812a-51322fe033f4.png)

**Comment by Rouergue** [comment]
Je viens de refaire toute la manip' et de réenregistrer la fiche et cela fonctionne. Bizarre, bizarre...

**Comment by Fchallier** [comment]
Oui cela peut venir du cache... j'ai vidé le cache et ça semble fonctionner. 

J'en ai profité pour le réduire à une durée de vie de 15 minutes au lieu de 5 heures...

**Comment by Rouergue** [comment]
Ah oui, c'est pas mal comme réduction de temps !
(en fait, ça sert à quoi le cache ?)
