### ISSUE TITLE
Lien FB pour partager nos pages Agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#342]
Il est possible de partager les pages livres ou auteurs de notre site (avec le bouton "share") mais pas les pages « agenda ». Est-ce que tu peux le rajouter pour que les personnes puissent rapidement partager un événement de notre site vers leurs pages FB ?

![capture d ecran 2018-02-01 a 09 15 58](https://user-images.githubusercontent.com/10072454/35683202-80858fca-0763-11e8-8c06-b9b3a3a73d78.png)

![capture d ecran 2018-02-01 a 09 16 10](https://user-images.githubusercontent.com/10072454/35683203-80c12c42-0763-11e8-887c-ce90221d1684.png)

**Comment by Fchallier** [comment]
Fonctionnalité ajouté aux fiches Événements.

( Module : Service Link + Ajout du lien dans l'affichage du  contenu complet )
