### ISSUE TITLE
Bibliographie incomplète sur la page livre

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#343]
Alors que la page auteur reprend bien l'ensemble de la biblio. Quid ?

![capture d ecran 2018-02-14 a 09 04 15](https://user-images.githubusercontent.com/10072454/36193434-2dc3a026-1166-11e8-9756-8f0a5639387f.png)

![capture d ecran 2018-02-14 a 09 04 30](https://user-images.githubusercontent.com/10072454/36193435-2de22f46-1166-11e8-91f8-362276b24d75.png)

**Comment by Fchallier** [comment]
En fait je pense que c'est le titre  "De la taille à la conduite des arbres fruitiers" qui pose problème. 

Dans Mistral l'auteur n'est pas en Principal. C'est le directeur d'ouvrage est renseigné comme principal...

**Comment by Fchallier** [comment]
J'ai fait une modification à ma mais sur le site et ça semble corrigé le problème quand je passe l'auteur en principal

**Comment by Fchallier** [comment]
C'est ok problème corrigé au niveau de la vue. Pas de modification à faire dans Mistral

**Comment by Rouergue** [comment]
À nouveau, le même problème se pose avec les albums de Natali Fortier ; ils apparaissent tous dans la biblio auteur mais pas au niveau des livres "du même auteur" sur les pages livres. Quid ? Est-ce un problème qui viendrait de mistral ? 
Merci pour ton aide.
![Capture d’écran 2019-10-03 à 15 34 51](https://user-images.githubusercontent.com/10072454/66292122-cdd4b400-e8e3-11e9-9a2a-a47179aab288.png)
![Capture d’écran 2019-10-03 à 15 34 59](https://user-images.githubusercontent.com/10072454/66292123-ce6d4a80-e8e3-11e9-8b7c-5925203fe71f.png)

**Comment by Fchallier** [comment]
Je viens de rajouter une condition pour inclure les illustrateurs dans la vue "Du même auteur". 

Le problème semble donc être corrigé.

**Comment by Rouergue** [comment]
Ok, merci. Il reste tout de même un album qui n'apparaît pas dans les biblios sur chaque page par 
titre. Il s'agit de MERCI. Est-ce parce que c'est un titre épuisé ? 


![Capture d’écran 2019-10-07 à 15 33 39](https://user-images.githubusercontent.com/10072454/66316547-2756d600-e918-11e9-9c77-252699481029.png)
![Capture d’écran 2019-10-07 à 15 33 53](https://user-images.githubusercontent.com/10072454/66316548-2756d600-e918-11e9-93ca-4cdd5e8380dc.png)

**Comment by Fchallier** [comment]
J'ai supprimé supprimé le paramètre de si l'auteur était principal ou non... ça semble bien fonctionner. 

J'ai regardé aussi sur d'autres titres, ça semble bien correspondre.
