### ISSUE TITLE
Titre à paraître qui n'apparait pas dans le récap' CATALOGUE

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#344]
Alors qu'il est bien dans le récap' de la collection LITTÉRATURE

![capture d ecran 2018-02-14 a 09 06 58](https://user-images.githubusercontent.com/10072454/36193517-86296020-1166-11e8-82ad-0f17abb89711.png)

![capture d ecran 2018-02-14 a 09 06 42](https://user-images.githubusercontent.com/10072454/36193516-860e42b8-1166-11e8-83af-6dbf3e7a4dc5.png)

**Comment by Rouergue** [comment]
Il s'agit du titre AU PLUS CHER DE NOS VIES

**Comment by Fchallier** [comment]
Je viens de vérifier et il est tout simplement en page 2 dans le recap catalogue
