### ISSUE TITLE
 Auteur qui n'apparaît pas sur la fiche livre (bis)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#345]
Comment se fait-il que les auteurs n'apparaissent pas au moment où la fiche livre remonte ? Ce n'est pas la première fois que cela se produit...

![capture d ecran 2018-03-15 a 09 26 36](https://user-images.githubusercontent.com/10072454/37451929-6d508efa-2833-11e8-874d-60901883e5dd.png)

**Comment by Fchallier** [comment]
Effectivement c'est un bug que je rencontre aussi sur le site Payot et Rivages... 

Je suis en train de faire des tests en local pour identifier la source du problème. 

D'ici vendredi je vais faire une mise à jour du cœur de Drupal et du module de migration en espérant que cela corrige définitivement cette erreur.

Je te tiens au courant

**Comment by Fchallier** [comment]
Je viens d'appliquer la mise à jour du module et  j'ai l'impression que cela a corrigé le problème.

Je surveille ça de près lors des prochaines mise à jours.

**Comment by Rouergue** [comment]
Hello François,
Le problème se pose à nouveau avec un titre de juin qui remonte sans le nom de l'auteur...

![capture d ecran 2018-05-02 a 11 10 15](https://user-images.githubusercontent.com/10072454/39515934-cca57fc6-4dfb-11e8-9ead-d31738864451.png)

![capture d ecran 2018-05-02 a 11 10 22](https://user-images.githubusercontent.com/10072454/39515937-cf009242-4dfb-11e8-93bf-21aa4ae08ff9.png)

**Comment by Fchallier** [comment]
J'ai lancé à nouveau la mise à jour et c'est passé.

**Comment by Rouergue** [comment]
À nouveau, le même pb (pour les titres "à paraître" :

![capture d ecran 2018-12-03 a 10 40 09](https://user-images.githubusercontent.com/10072454/49365741-d4a10200-f6e7-11e8-94c8-c5e5ea7d8b65.png)

**Comment by Rouergue** [comment]
idem

![capture d ecran 2018-12-03 a 10 42 43](https://user-images.githubusercontent.com/10072454/49365886-39f4f300-f6e8-11e8-98ca-d3eaf2823db6.png)

![capture d ecran 2018-12-03 a 10 42 51](https://user-images.githubusercontent.com/10072454/49365893-3d887a00-f6e8-11e8-8575-aa81eee7ce54.png)
