### ISSUE TITLE
URL de site non reconnue

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#347]
Impossible de valider une adresse URL de site libraire sur une page événement. Pourtant, le lien est bien valide. Quid ?

![capture d ecran 2018-03-20 a 09 34 23](https://user-images.githubusercontent.com/10072454/37643850-29b4081e-2c22-11e8-8c24-6741c7bae175.png)

![capture d ecran 2018-03-20 a 09 34 18](https://user-images.githubusercontent.com/10072454/37643860-2f957d30-2c22-11e8-9bae-73de18d832cf.png)

![capture d ecran 2018-03-20 a 09 34 33](https://user-images.githubusercontent.com/10072454/37643857-2db7c25c-2c22-11e8-8e07-4dedc6ba4735.png)

**Comment by Fchallier** [comment]
C'est le ".paris" qui pose problème... ce n'est pas une extension très populaire comparée aux ".fr", ".com" etc... 

Donc par mesure de sécurité le module de lien n'accepte pas le lien. 

Pour corriger cela, tu peux raccourcir le lien en utilisant le site https://lc.cx/ ou Bitly.

**Comment by Rouergue** [comment]
Merci pour le tuyau, mais ça ne marche pas plus ! 

![capture d ecran 2018-03-20 a 09 55 20](https://user-images.githubusercontent.com/10072454/37644683-df837f06-2c24-11e8-8e8d-97ddb7453394.png)

![capture d ecran 2018-03-20 a 09 55 26](https://user-images.githubusercontent.com/10072454/37644687-e1eaa904-2c24-11e8-879d-1eddb8c1d871.png)

**Comment by Fchallier** [comment]
Il fallait enlever le dernier slash et ajouter le http.

J'ai mis à jour ton actualité avec le lien court 👍
