### ISSUE TITLE
vidéo qui ne s'affiche pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#349]
Au niveau de la fabrique. J'ai pourtant fait comme d'hab' > coller l'url vimeo dans le champ WEB, mais ça ne s'affiche pas quand j'enregistre ensuite. Est-ce parce que vimeo n'a pas encore "digéré" la vidéo que j'ai téléchargée ?

![capture d ecran 2018-03-29 a 14 35 39](https://user-images.githubusercontent.com/10072454/38089093-84f38b8a-335e-11e8-996a-76db010a03c4.png)

![capture d ecran 2018-03-29 a 14 35 32](https://user-images.githubusercontent.com/10072454/38089094-8514651c-335e-11e8-9e0d-74c60f9a409d.png)

![capture d ecran 2018-03-29 a 14 35 18](https://user-images.githubusercontent.com/10072454/38089095-852e515c-335e-11e8-954a-ae7f86428a86.png)

**Comment by Rouergue** [comment]
La vignette apparaît mais la vidéo n'est pas visible et le lien semble mort

![Capture d’écran 2020-10-05 à 14 53 39](https://user-images.githubusercontent.com/10072454/95081946-9bd67780-071a-11eb-8550-fa02eba1f58d.png)

**Comment by Rouergue** [comment]
C'est toujours d'actualité : aucun média ne fonctionne au niveau de la Fabrique.

![Capture d’écran 2020-11-12 à 15 45 04](https://user-images.githubusercontent.com/10072454/98954505-23738b00-24fe-11eb-8a11-376d4b2de6af.png)

**Comment by Fchallier** [comment]
Je viens de corriger cela, la vidéo est directement affiché en haut à droite. 

View modifié : views/view/workshops/edit/workshop_media_block

Et affichage "accroche" dans admin/structure/types/manage/workshops/display/block

**Comment by Rouergue** [comment]
Merci pour la correction de bug. Les vidéos présentes s'affichent à nouveau.
Par contre, je n'arrive pas à télécharger de nouvelles vidéos. Voici le message qui s'affiche :

![Capture d’écran 2021-01-28 à 17 27 33](https://user-images.githubusercontent.com/10072454/106168672-d7e08d00-618e-11eb-9cd6-47abf1593f28.png)

**Comment by Rouergue** [comment]
(j'ai essayé d'en uploader une au niveau de la Fabrique)

**Comment by Fchallier** [comment]
Dans le type de contenu Worshops, il y avait un soucis avec l'option **Library**
C'est corrigé. 

![screenshot-www lerouergue com-2021 02 09-11_36_53](https://user-images.githubusercontent.com/9974750/107351811-5d3b3a00-6acb-11eb-87e5-ff69348eef21.png)
