### ISSUE TITLE
Les auteurs des nouveautés ne remontent pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#350]
C'est le cas pour la dizaine de titres mis à jour cette nuit. Quid ?

![capture d ecran 2018-07-04 a 09 12 47](https://user-images.githubusercontent.com/10072454/42262282-208f1fd4-7f6b-11e8-9b9e-81337880a196.png)

![capture d ecran 2018-07-04 a 09 12 58](https://user-images.githubusercontent.com/10072454/42262283-20abd750-7f6b-11e8-9eb4-be60054e79da.png)

**Comment by Fchallier** [comment]
Je viens de relancé une mise à jour, et ça semble fonctionner. 

J'ai aussi les éléments qui lancent automatiquement la mise à jour, ça devrait être bon.
