### ISSUE TITLE
Titres qui ne remontent pas sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#351]
Est-ce normal que les titres d'octobre (dont les prix ont été validés dans mistral) ne remontent pas sur le site ? En principe, on doit avoir l'affichage des titres d'août, sept. et octobre, non ? 
Exple pour SUR LE CIEL EFFONDRÉ (9782812616587) ou encore MESSAGÈRE DE L'OMBRE (9782812616686) qui ne s'affichent pas.

![capture d ecran 2018-08-02 a 16 08 17](https://user-images.githubusercontent.com/10072454/43589274-a4962772-966e-11e8-9158-b22b6312f808.png)

**Comment by Fchallier** [comment]
Hier le serveur est tombé à cause des migrations lancées sur notre serveur... J'ai tout vérifié aujourd'hui avant de lancer à nouveaux les migrations. 

Pour le Rouergue tout semble en ordre maintenant.
