### ISSUE TITLE
Affichage "erreur" après chaque enregistrement d'un événement (agenda)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#352]
...de manière systématique (ce qui fait que je ne peux pas vérifier rapidement la saisie). Quid ?

![capture d ecran 2018-09-13 a 15 02 01](https://user-images.githubusercontent.com/10072454/45489959-216ae180-b766-11e8-863b-5e5009f3b8a4.png)

**Comment by Rouergue** [comment]
ça le fait toujouuuuuuurs ! ;-(

![capture d ecran 2018-09-17 a 15 49 11](https://user-images.githubusercontent.com/10072454/45627054-50989000-ba91-11e8-94ba-03f1f2e03556.png)

**Comment by Fchallier** [comment]
Désolé, ça m'a pris un peu de temps pour trouver la source du problème.... 

J'ai fait quelques tests et le problème semble corrigé.
