### ISSUE TITLE
Décalage des blocs extraits ou vidéo

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#354]
Il y a, semble-t-il, un décalage des blocs extraits ou vidéo (encadrés qui s'affichent suite à l'importation de codes embed). Ils ne sont plus justifiés à gauche sur le bord du résumé (et débordent un peu dans la marge à droite). Peux-tu voir ce qu'il en est, stp ?
Merci.

![capture d ecran 2018-10-09 a 09 55 52](https://user-images.githubusercontent.com/10072454/46656057-72c39080-cbad-11e8-8577-9c675e38c821.png)

**Comment by Fchallier** [comment]
Je t'ai peut-être indiqué la mauvaise marche à suivre. 

Mais lorsque tu ajoute un <embed> sur le site, il faudrait sélectionner l'option Responsive. ça devrait corriger le problème.

Exemple sur Viémo et ISSUU

![Screenshot_2021-02-09 Issuu - Publication](https://user-images.githubusercontent.com/9974750/107351142-8effd100-6aca-11eb-8522-4dd3b282d6c4.png)
![Screenshot_2021-02-09 Who are you - Portrait of a photographer](https://user-images.githubusercontent.com/9974750/107351151-90c99480-6aca-11eb-9f8c-c7cf9edd3646.png)
