### ISSUE TITLE
Réintégrer un titre sur le site qui a été supprimé 

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#357]
Comment réintégrer un titre sur le site qui a été supprimé ?
Il s'agit de titres qui étaient initialement prévus pour Ventes Privées (= en arrêt de commercialisation) mais qui ont été finalement réintégrés au stock dispo. Sauf que j'avais déjà supprimé la page correspondante sur le site ;-)
Comment faire ?

(exemple pour LE CHAPEAU DE PHILIBERT)

**Comment by Fchallier** [comment]
Je vois que dans Mistral il est en interdit à la vente (Gencode:9782812602047)... 

Tant qu'il sera en interdit à la vente il ne pourra pas être intégré au site. Il faut donc le passer en actif  et je lancerai une mise à jour.

**Comment by Rouergue** [comment]
Ok. L'isbn ayant changé, ce titre est remonté comme une nouveauté, du coup.
