### ISSUE TITLE
URGENT : le catalogue et la liste des auteurs ne s'affichent plus !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#359]
Est-ce momentané, dû à la mise à jour du serveur ou est-ce un bug ? 

![capture d ecran 2018-12-19 a 10 19 03](https://user-images.githubusercontent.com/10072454/50210923-a4a85e80-0377-11e9-8808-8372c1a80803.png)

![capture d ecran 2018-12-19 a 10 19 08](https://user-images.githubusercontent.com/10072454/50210932-a96d1280-0377-11e9-81be-2827b280d111.png)

**Comment by Fchallier** [comment]
oh !  Non c'est pas normal du tout ! 

Je vais mettre le site en mode maintenance pour le moment et regarder ce qu'il s'est passé...

**Comment by Fchallier** [comment]
Il y a eu une erreur au niveau du dump cette nuit, ce qui a causé de gros dégâts sur la Base de données du site.

J'ai donc été dans l'obligation de réimporté toutes les données du site d'hier à 21h.

Tout semble fonctionner à nouveau.
