### ISSUE TITLE
Supprimer les encadrés "exposition" du bandeau d'accueil

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#362]
Est-il possible de faire apparaître les 4 prochaines dates à venir dans l'agenda sur la page d'accueil, à l'exception des EXPOSITIONS ? En effet, lorsqu'une expo dure 4 mois, elle monopolise la place sur la page d'accueil et on ne voit pas apparaître les autres dates importantes et ponctuelles.
Merci !

![Capture d’écran 2019-03-14 à 09 46 48](https://user-images.githubusercontent.com/10072454/54343148-79fc3800-463e-11e9-9760-a5fcebb51fe9.png)

**Comment by Fchallier** [comment]
J'ai rajouté une condition à la vue, pour que la date de début soit supérieure ou égale à la date du jour....
Le résultat te semble plus cohérent  ?

**Comment by Rouergue** [comment]
Perfecto !
Merci.
