### ISSUE TITLE
Auteur qui n'apparaît pas !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#364]
Idem # 335 # 326 # 339 # 345... c'est un problème récurrent apparemment !
Ce matin, il manque l'auteur pour une fiche livre sur les trois qui sont remontés. Quid ? 
Merci pour ton aide !

![Capture d’écran 2019-06-05 à 09 53 12](https://user-images.githubusercontent.com/10072454/58939762-2f3f1780-8778-11e9-8ff7-5b6e97d18095.png)

**Comment by Rouergue** [comment]
À nouveau, les auteurs ne remontent pas sur les deux derniers titres qui se sont affichés ce matin. J'ai l'impression que c'est maintenant systématique. Peux-tu voir pour que les auteurs remontent en même temps que les titres systématiquement, stp ? 
Merci beaucoup,

![Capture d’écran 2019-07-17 à 10 54 06](https://user-images.githubusercontent.com/10072454/61361902-9379ee80-a881-11e9-895d-b0299ae929b8.png)

![Capture d’écran 2019-07-17 à 10 55 08](https://user-images.githubusercontent.com/10072454/61361911-9674df00-a881-11e9-855f-e4b9bc53090f.png)

**Comment by Fchallier** [comment]
J'ai lancé plusieurs fois la mise à jour ce matin et rien y fait... je viens de renvoyer un dump de la base et ça semble fonctionner... 

Je vais donc prendre l'habitude de faire un dump chaque matin... Alors qu'il est fait chaque soir...

**Comment by Rouergue** [comment]
Idem # 335 # 326 # 339 # 345... c'est un problème récurrent apparemment !
Ce matin il manque les auteurs pour 2 fiches sur toutes celles qui sont remontées.

![Capture d’écran 2019-12-05 à 11 52 20](https://user-images.githubusercontent.com/10072454/70229876-5c847680-1757-11ea-9532-000cf3eeca77.png)

![Capture d’écran 2019-12-05 à 12 04 23](https://user-images.githubusercontent.com/10072454/70229896-64dcb180-1757-11ea-8d4a-b6348b3dc3da.png)

**Comment by Rouergue** [comment]
Toujours le même problème...

![Capture d’écran 2020-01-29 à 14 14 07](https://user-images.githubusercontent.com/10072454/73359664-abefaa80-42a1-11ea-8b31-4deca5bdf4ea.png)

**Comment by Fchallier** [comment]
Alors oui mais il y a eu clairement une mise à jour dans Mistral entre ce matin et ce début d'après midi...

La condition dans la requête SQL pour l'import vérifier si le prix est bien validé.  

```
SELECT a.articleid, bc.contributorid, bc.functionid, bc.ismain, bc.iscommunicable 
FROM bookcontributor bc 
JOIN article a ON a.bookid=bc.bookid 
WHERE bc.bookid IN ( 
SELECT a.bookid FROM `article` a 
JOIN book b ON b.bookid=a.bookid 
JOIN fabricationplan fp ON fp.articleid=a.articleid 
JOIN priceandtirage pt ON pt.articleid=a.articleid 
**JOIN realprice rp ON rp.articleid=a.articleid and rp.iscurrentprice='1'** 
WHERE a.statusid <> 1 
AND b.projecttype <> 'PLV'
 GROUP BY a.articleid) 
```

Je vais peut-être supprimer cette condition au niveau cette requête.

**Comment by Rouergue** [comment]
Again !

![Capture d’écran 2020-02-12 à 11 33 22](https://user-images.githubusercontent.com/10072454/74326931-92fbf480-4d8b-11ea-937f-38eae5aa59b2.png)
