### ISSUE TITLE
Titre qui ne remonte pas...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#365]
Alors que le prix et tirage sont bien validés dans mistral et qu'un autre roman, _Vorace_, prévu au même office (21/08) est lui remonté depuis plusieurs semaines déjà...
Quid ?

![Capture d’écran 2019-07-15 à 11 01 29](https://user-images.githubusercontent.com/10072454/61205448-5b8f7180-a6f0-11e9-818b-f08b86b86ebd.png)

**Comment by Fchallier** [comment]
Je viens de vérifier le code et de lancer aujourd'hui une nouvelle mise à jour. 

ça semble avoir bien fonctionné... bien à toi.

**Comment by Rouergue** [comment]
Ok, merci. Est-ce que tu sais à quoi c'est dû ? Car ce n'est pas la première fois que cela arrive...
Y a-t-il autre chose à valider en plus du tirage et prix pour que ça remonte en temps et en heures ?

**Comment by Rouergue** [comment]
Ok, merci. Est-ce que tu sais à quoi c'est dû ? Car ce n'est pas la première fois que cela arrive...
Y a-t-il autre chose à valider en plus du tirage et prix pour que ça remonte en temps et en heures ?

**Comment by Fchallier** [comment]
Comme pour les auteurs qui ne remontent pas, j'ai l'impression qu'il est nécessaire que je  fasse le dump chaque matin pour la mise jour.... Alors qu'il est fait la veille... 

J'ai pas trop d'explication car le fonctionnement est exactement le même dans la nuit lors de la mise à jour et le matin si je la lance manuellement...

**Comment by Rouergue** [comment]
À nouveau, je remarque qu'un autre titre d'octobre ne remonte pas non plus sur le site ; il s'agit de L'HOMME QUI CHAUSSAIT DU 62 (9782812618673) :
![Capture d’écran 2019-08-27 à 15 14 50](https://user-images.githubusercontent.com/10072454/63774574-d1851c00-c8dd-11e9-9729-2b38d6bf9556.png)
