### ISSUE TITLE
Liens à partir des bandeaux actu

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#366]
Est-il possible que les liens situés en bas à droite des bandeaux actu sur le site s'ouvrent dans une nouvelle fenêtre et non pas à la place de la page accueil du site ?

![Capture d’écran 2019-07-30 à 15 35 48](https://user-images.githubusercontent.com/10072454/62133881-e15e1000-b2df-11e9-9a0b-29b130374bba.png)

**Comment by Fchallier** [comment]
Pas de soucis, c'est en place sur le site. 

-> modification de la vue "Actualités"
-> Réécriture du résultat "Contenu : Url"
 

Bien à toi,
