### ISSUE TITLE
Titres de la coll. épik à intégrer dans la rubrique Romans jeunesse

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#367]
J'ai oublié de te demander une chose !
Les romans de la coll. Epik ne se retrouvent pas dans le récap' de tous les romans ados. Peux-tu les rajouter, stp ?
Merci et à plus tard.

**Comment by Fchallier** [comment]
Je viens de réaliser la modification dans le module de migration. 

Et après avoir lancé une mise à jour ça semble fonctionné. 
Donc les titres qui ont comme collection Epik sont maintenant aussi dans l'univers Rayon Jeunesse -> Romans ados
