### ISSUE TITLE
bandeau agenda sur la page d'accueil qui ne se met pas à jour

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#368]
Nous sommes le 25/11, normalement, les 4 premiers posts de l'agenda qui apparaissent sur la page d'accueil ne devraient pas concerner des dates antérieures, non ?

![Capture d’écran 2019-11-25 à 09 20 31](https://user-images.githubusercontent.com/10072454/69528964-968f9480-0f6f-11ea-916a-5e51392c95e3.png)

**Comment by Fchallier** [comment]
Je ne sais pas si tu as modifié quelques chose mais je n'arrive pas à reproduire le bug...

**Comment by Rouergue** [comment]
Non, je n'ai touché à rien. Mais j'ai vu effectivement que le bandeau s'était mis à jour dans la matinée ; j'ai cru que c'était toi qui avais fait des modifs !
