### ISSUE TITLE
Problème d'affichage menu dans la rubrique Catalogue

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#369]
L'affichage des menus dans la colonne de gauche met tout au même niveau à la suite alors que les sous-rubriques se retrouvaient dans les rubriques à ce niveau-là auparavant.

![Capture d’écran 2019-11-27 à 09 38 22](https://user-images.githubusercontent.com/10072454/69707562-4b55bd00-10fa-11ea-8796-4fe488686b38.png)

**Comment by Fchallier** [comment]
Je viens de vider les caches du site, ça semble avoir fonctionné.

**Comment by Rouergue** [comment]
À nouveau, le même problème réapparaît. C'est bizarre, c'est comme si les nouvelles mises à jour aplatissaient les corrections de bug qu'il y a eu précédemment...

![Capture d’écran 2019-12-05 à 12 06 38](https://user-images.githubusercontent.com/10072454/70230088-e0d6f980-1757-11ea-8c7d-c018c6a35f15.png)

**Comment by Fchallier** [comment]
Oui j'ai l'impression qu'après chaque mise à jour le menu ne respecte plus la hiérarchie... 

Ce qui est étrange c'est que le simple fait de vider la cache corrige le problème. Il faut que je regarde ça de plus près.

**Comment by Rouergue** [comment]
Rrrrhaa... ça recommence !

![Capture d’écran 2019-12-09 à 10 23 58](https://user-images.githubusercontent.com/10072454/70423604-1a687700-1a6e-11ea-84a6-85e6092d59ff.png)
