### ISSUE TITLE
URGENT : ajout d'un pays dans la liste déroulante de l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#370]
Il faudrait ajouter le MAROC, stp (car Casablanca n'est pas du tout en Allemagne !)
Serait-il possible d'avoir la main pour pouvoir rajouter des pays moi-même ? 
Et, question subsidiaire (j'en profite !), comment se fait-il que la map ne s'affiche plus sur le site ?
Merci !

![Capture d’écran 2019-12-02 à 17 47 24](https://user-images.githubusercontent.com/10072454/69977857-d1736880-152b-11ea-9aa6-a125d551b8e6.png)

![Capture d’écran 2019-12-02 à 17 45 06](https://user-images.githubusercontent.com/10072454/69977781-b56fc700-152b-11ea-8eef-8aef98ce6092.png)

**Comment by Fchallier** [comment]
Je viens de faire la mise à jour pour le Pays. 
Le truc c'est que si je te donne la main sur ce type de configuration, et que tu réalise cette modification sur le site en production ça risque de générer des problèmes... 

Pour le map il faut que je regarde ça. 

( Je te répond demain à ton mail concernant les univers )

**Comment by Rouergue** [comment]
Ok, merci pour le Maroc ! 
Et pas de souci, je te laisse la main ;-) 
Bonne soirée.
