### ISSUE TITLE
Impossible d'intégrer des images png dans le bandeau actu

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#371]
Les images png que je tente d'importer ne semblent pas être acceptées... Pourtant, elles sont au format habituel, en png - RVB - 78 ko.
Quid ?

![Capture d’écran 2019-12-19 à 16 42 06](https://user-images.githubusercontent.com/10072454/71187061-9e94d880-227e-11ea-9493-d019e45ae28e.png)

![actu quatre desirs](https://user-images.githubusercontent.com/10072454/71187127-bcfad400-227e-11ea-9ccd-3ec8a08b3150.png)

**Comment by Fchallier** [comment]
Il y a eu pas mal de changement sur le serveur depuis le début de la semaine. 
Et il a eu malheureusement des dommages collatéraux, je suis actuellement en train d'avancer sur ce point pour pour que les configurations soient identiques à ce que nous avions avant. 

Je clôture le ticket dès que tout sera ok.
