### ISSUE TITLE
URGENT : impossible d'intégrer de nouveaux bandeaux actu !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#372]
Tout d'abord, BONNE ANNÉE !!!

En ce retour de congés, je n'arrive pas à intégrer les images png pour le bandeau actu du site. Cf. ci-joint le fichier en question. Peux-tu me dire ce qui ne va pas, stp ? Je n'ai pourtant rien changé par rapport à d'habitude...
Merci !

![actu-brune 2020](https://user-images.githubusercontent.com/10072454/71806908-59d4b400-306a-11ea-82ee-9ebf3da34e50.png)

**Comment by Rouergue** [comment]
![Capture d’écran 2020-01-06 à 09 54 01](https://user-images.githubusercontent.com/10072454/71806964-7b35a000-306a-11ea-8b3d-407377cdf3da.png)

**Comment by Rouergue** [comment]
C'est vraiment urgent car il faut que je mette à jour les bandeaux actu ce matin ! 
Merci !!!

**Comment by Fchallier** [comment]
Bonjour Mathilde et bonne année  ! 

Il y a eu quelques modifications sur le serveur, je regarde ça tout de suite pour corriger le problème.

**Comment by Fchallier** [comment]
Je viens d'appliquer une correction concernant le poids max autorisé.
Peux-tu me confirmer que cela fonctionne bien à nouveau  ?

**Comment by Rouergue** [comment]
Euh... Je n'ai plus rien du tout ! 

![Capture d’écran 2020-01-06 à 10 48 46](https://user-images.githubusercontent.com/10072454/71810255-3ada2000-3072-11ea-9a3b-f2a04c728851.png)

![Capture d’écran 2020-01-06 à 10 48 51](https://user-images.githubusercontent.com/10072454/71810259-3dd51080-3072-11ea-89bb-5024abc50e87.png)

**Comment by Rouergue** [comment]
![Capture d’écran 2020-01-06 à 11 06 22](https://user-images.githubusercontent.com/10072454/71811291-973e3f00-3074-11ea-92e3-f1895c4f9f64.png)

**Comment by Rouergue** [comment]
J'ai récupéré l'interface du site mais les fichiers png n'arrivent toujours pas à se télécharger (pourtant, il ne fait que 220 ko).

![Capture d’écran 2020-01-06 à 11 13 04](https://user-images.githubusercontent.com/10072454/71811668-98bc3700-3075-11ea-886e-570b9ad4d474.png)
