### ISSUE TITLE
Impossible d'intégrer une vignette dans l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#374]
Help ! Je ne peux pas non plus intégrer une vignette au niveau des post Agenda...
Cela devient vraiment handicapant ! J'ai l'impression que je ne peux plus importer aucune nouvelle image sur le site...

![Capture d’écran 2020-01-06 à 13 45 18](https://user-images.githubusercontent.com/10072454/71819012-ea22f100-308a-11ea-9b71-edbd38c25848.png)

**Comment by Rouergue** [comment]
(cette fois-ci, l'image est en jpeg et non pas en png... mais le résultat est le même !)

**Comment by Rouergue** [comment]
En fait, je ne peux plus rien enregistrer...

![Capture d’écran 2020-01-06 à 13 50 45](https://user-images.githubusercontent.com/10072454/71819298-c7dda300-308b-11ea-86c3-5da7fc962080.png)

**Comment by Fchallier** [comment]
Désolé Mathilde il y a un conflit entre deux modules et l'upload d'un fichier ne peut pas se réaliser... Je suis dessus, je tente de trouver une solution au plus vite !

**Comment by Fchallier** [comment]
Et il faudrait éviter de réaliser des modifications sur le site car cela pourrait entrainer des complications...

**Comment by Rouergue** [comment]
Ok, je ne touche plus à rien et j'attends ton feu vert...
Merci !

**Comment by Fchallier** [comment]
Une nouvelle configuration vient d’être mis en place sur le serveur, tu ne devrais plus avoir de problème avec l'upload des fichiers. 

Une mise à jour complète du cœur de Drupal et des modules a été réalisé.
