### ISSUE TITLE
Ordre des menus modifié à la verticale

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#375]
Pourquoi la liste des rubriques en colonne ne suit pas l'ordre des rubriques à l'horizontale qui est sur la page d'accueil, comme précédemment ? 

![Capture d’écran 2020-01-07 à 10 42 07](https://user-images.githubusercontent.com/10072454/71885407-996ad100-313a-11ea-92de-c7d662cb6f9a.png)

![Capture d’écran 2020-01-07 à 09 51 05](https://user-images.githubusercontent.com/10072454/71885410-9a9bfe00-313a-11ea-891d-bd0182aa77ad.png)

**Comment by Fchallier** [comment]
Étrange effectivement... je viens d'enregistrer la taxonomie ça semble avoir fonctionné. 

N'hésites pas à ouvrir d'autre ticket si tu rencontres le moindre soucis,  la mise à jour de certains module à probablement généré des coquilles comme celle-ci.
