### ISSUE TITLE
Thèmes qui n'apparaissent pas sur le site...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#378]
...sous les couvertures, comme prévu initialement.
Alors que les thèmes sont bien mentionnés dans Mistral. 

![Capture d’écran 2020-01-08 à 15 34 39](https://user-images.githubusercontent.com/10072454/71986321-93edb380-322c-11ea-813d-457875ec3623.png)

![Capture d’écran 2020-01-08 à 15 25 06](https://user-images.githubusercontent.com/10072454/71986329-96e8a400-322c-11ea-87bc-4590ec4df0c6.png)

**Comment by Fchallier** [comment]
Vérifier la vue concernant les thèmes.  (vérifier la condition du lectorat)

**Comment by Rouergue** [comment]
Problème toujours d'actualité...

**Comment by Fchallier** [comment]
Supression du critère de filtrage dans la view "structure/views/view/theme_book/"

![screenshot-www lerouergue com-2021 02 09-11_21_32](https://user-images.githubusercontent.com/9974750/107349937-19dfcc00-6ac9-11eb-831a-0ae8133c8731.png)
