### ISSUE TITLE
Livres de début février qui ne remontent pas !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#379]
Pourquoi les titres de février ne remontent pas sur le site alors que les prix déf sont bien validés dans mistral ? C'est le cas pour LA PETITE RÉPUBLIQUE DE SAILLANS (9782812619366) ou encore IL ÉTAIT UNE BERGÈRE (9782812619403). En principe les livres doivent remonter au moins 2 mois avant, non ? 

![Capture d’écran 2020-01-13 à 11 44 49](https://user-images.githubusercontent.com/10072454/72249772-5ad18c80-35fa-11ea-96fa-2943f0a0778c.png)

**Comment by Fchallier** [comment]
La mise à jour du serveur a changé le nom des commandes pour lancer les scriptes de mise à jour. Je corrige cela tout de suite !

**Comment by Rouergue** [comment]
Toutes les dernières couvs sont remontées du coup, merci !
Par contre, pour les nouveaux auteurs, ils n'apparaissent toujours pas...

![Capture d’écran 2020-01-13 à 17 33 16](https://user-images.githubusercontent.com/10072454/72273607-e9f69880-362a-11ea-9d02-7d38572aec78.png)

![Capture d’écran 2020-01-13 à 17 33 10](https://user-images.githubusercontent.com/10072454/72273611-ee22b600-362a-11ea-961d-bdec766aaeec.png)

![Capture d’écran 2020-01-13 à 17 31 23](https://user-images.githubusercontent.com/10072454/72273621-f11da680-362a-11ea-958e-b8b200f4d591.png)

**Comment by Fchallier** [comment]
La mise à jour est en cour ça ne devrait pas tarder à apparaître
