### ISSUE TITLE
Erreur de chargement sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#380]
Quand je clique sur un événement que je souhaite modifier dans l'agenda, voici ce que ça donne :

![Capture d’écran 2020-01-13 à 11 47 34](https://user-images.githubusercontent.com/10072454/72249872-9d936480-35fa-11ea-8beb-72080688670d.png)

**Comment by Fchallier** [comment]
Étrange... Je ne vois rien dans les logs du site... Quand c'est comme ça passes par la partie admin -> contenu -> Choisir l'action "Modifier" pour l'actu qui bug.

**Comment by Rouergue** [comment]
ok, c'est noté !
