### ISSUE TITLE
Problème d'affichage agenda (en colonne)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#381]
![Capture d’écran 2020-01-13 à 11 50 56](https://user-images.githubusercontent.com/10072454/72250045-04b11900-35fb-11ea-81eb-eb079219ae32.png)

**Comment by Fchallier** [comment]
Je viens de faire une correction, tu me confirmes que c'est ok de ton côté  ? Il faut bien vider le Cache de ton naviguer ( Ctrl + F5)

**Comment by Rouergue** [comment]
Oui, c'est bon, merci !
J'ai l'impression que le site a eu un peu de mal à démarrer, ce matin ;-) !
