### ISSUE TITLE
Faille de sécurité potentielle

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#382]
C'est le message qui s'est affiché quand j'ai ouvert FileZilla pour y basculer les nouvelles couvs. Je ne sais pas si c'est important ou non ?!

![Capture d’écran 2020-01-13 à 17 35 44](https://user-images.githubusercontent.com/10072454/72274042-bcf6b580-362b-11ea-8aa6-9b42ae0aa409.png)

**Comment by Fchallier** [comment]
Je pense que c'est normal étant donnée que des modifications ont été réalisé sur le serveur.
