### ISSUE TITLE
Pb affichage agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#383]
À nouveau il se met en colonne (même quand l'écran est assez large).

![Capture d’écran 2020-01-20 à 12 12 34](https://user-images.githubusercontent.com/10072454/72722298-45221100-3b7e-11ea-81c8-2a2c2b5b10f3.png)

**Comment by Rouergue** [comment]
Et toujours pas d'amélioration de ce côté...

![Capture d’écran 2020-01-29 à 10 04 25](https://user-images.githubusercontent.com/10072454/73342402-c6645c80-427e-11ea-9705-c14f6568f18d.png)

**Comment by Rouergue** [comment]
Ce qui est étrange c'est que ça ne le fait pas tout le temps ! Mais c'est le cas actuellement (et je viens de vider les caches).

**Comment by Fchallier** [comment]
Je n'arrive pas à reproduire le problème... j'ai testé plusieurs navigateurs et ça s'affiche correctement.... 

Tu n'as pas un zoom activé sur ton navigateur ? tu utilises lequel ?

**Comment by Rouergue** [comment]
Je suis sur Firefox et je n'ai pas de zoom (je me suis mise en "normal") mais, effectivement, Nathalie m'a dit qu'elle n'avait pas ce problème... Ce qui est bizarre, c'est que ça ne le fait pas tout le temps et que ça n'a pas l'air d'être fonction de la largeur de la fenêtre ! Bon, ce n'est pas forcément le plus gênant (surtout si ça ne le fait que chez moi !). Je voulais surtout m'assurer qu'il n'y avait pas de bug général au niveau de l'affichage.

**Comment by Fchallier** [comment]
Après le mise  à jour du serveur j'ai été obligé de reprendre la plupart des views qui composent votre site.  Et celle de l'Agenda a bien été pris en compte. 

Je pense que ça peut venir de ton poste. Car de mon coté j'ai testé sur plusieurs postes et l'affichage est bon. 

Si tu peux tester avec un autre navigateur au cas où...
