### ISSUE TITLE
URGENT : pb d'enregistrement des posts dans l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#384]
![Capture d’écran 2020-01-29 à 10 01 12](https://user-images.githubusercontent.com/10072454/73342193-58b83080-427e-11ea-8fb5-760c8479c1f4.png)

La plupart du temps, quand je veux enregistrer un post, j'ai ce message d'erreur qui s'affiche. Je sais que je peux aller sur CONTENU pour retrouver le post et le modifier et le visualiser mais c'est très fastidieux et c'est long ; j'ai beaucoup de posts à rentrer et j'aimerais pouvoir vérifier d'un coup d'œil que l'affichage est correct et qu'il n'y a pas d'erreurs !

**Comment by Rouergue** [comment]
Idem quand je clique sur un post déjà créé (que je veux modifier), cela me met le message d'erreur. 
![Capture d’écran 2020-01-29 à 10 13 11](https://user-images.githubusercontent.com/10072454/73343010-1263d100-4280-11ea-9c8d-10f95fef58df.png)
![Capture d’écran 2020-01-29 à 10 13 16](https://user-images.githubusercontent.com/10072454/73343015-142d9480-4280-11ea-9d37-af7da57f823b.png)
Et, pour le coup, quand il faut aller à la pêche dans CONTENU pour retrouver le post, ça prend du temps car les posts apparaissent par ordre de création !

**Comment by Fchallier** [comment]
Erreur avec le module Geofield Map, l'API google n'est pas pris en compte : #385 
Field map désactivé. 

L'enregistrement des actualités fonctionne à nouveau.
