### ISSUE TITLE
Suppression de google Maps

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#385]
La plupart du temps, il est impossible de charger Google Maps correctement sur les pages agenda. Du coup, je supprimerais bien cette fonctionnalité qui n'est pas graphiquement très heureuse quand ça bug... Ton avis ?
Auras-tu un moment dans les jours-semaines à venir pour qu'on fasse un petit point sur le site du Rouergue ?

![Capture d’écran 2020-01-29 à 10 39 05](https://user-images.githubusercontent.com/10072454/73345130-d29ee880-4283-11ea-867e-8fe502279c24.png)

**Comment by Fchallier** [comment]
En fait le modul de Map génère l'erreur #384 
Pourtant j'ai mis à jour l'ensemble des modules, bien renseignée la Clée de l'API de Google map, mais rien n'y fait, ça ne fonctionne pas... 

J'ai donc pour le moment désactivé le système de Map, à la place j'affiche l'adresse au format texte. 

Je regarde pour trouver autre module qui pourrait fonctionner.

**Comment by Rouergue** [comment]
Je trouve que c'est moins clair de mettre l'adresse en haut à droite ; ça vient un peu en concurrence avec la liste des autres événements de l'agenda. Est-ce qu'on ne pourrait pas laisser l'adresse là où elle était et juste remonter la colonne agenda à droite pour que ça ne fasse pas vide ? 

![Capture d’écran 2020-01-29 à 13 57 49](https://user-images.githubusercontent.com/10072454/73358927-f839eb00-429f-11ea-86e8-4b4ffd930477.png)

**Comment by Fchallier** [comment]
Pas de soucis  !

**Comment by Rouergue** [comment]
Super, merci !
