### ISSUE TITLE
Application FileZilla qui plante

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#386]
Et du coup, impossible de mettre en ligne sur le serveur les nouvelles couvs ! 

![Capture d’écran 2020-01-29 à 14 15 12](https://user-images.githubusercontent.com/10072454/73359774-e0fbfd00-42a1-11ea-9a0d-a091f9bec9da.png)

![Capture d’écran 2020-01-29 à 14 15 21](https://user-images.githubusercontent.com/10072454/73359777-e22d2a00-42a1-11ea-9b5c-7d43ec182a55.png)

**Comment by Rouergue** [comment]
Présentement, peux-tu mettre la couv ci-jointe sur le serveur, stp ?
Merci !

![9782812619502](https://user-images.githubusercontent.com/10072454/73359815-f709bd80-42a1-11ea-9740-d78cb11b7287.jpg)

**Comment by Fchallier** [comment]
La couv est déjà sur le site. 
Peux-tu m'indiquer l'utilisateur SFTP utilisé dans FileMaker  ? C'est bien prodrouergue ?

**Comment by Rouergue** [comment]
Oui, la couv est sur le site parce que je viens de la mettre manuellement. Mais je pensais qu'il fallait que je la dépose également sur le serveur (via FileZilla) pour qu'elle apparaisse toujours, même lors du prochain dump... en attendant que la couv déf soit mise sur mistral !

Par contre, je ne peux pas te dire quel est l'utilisateur SFTP (dans FileZilla et pas FileMaker, non ?) car l'application ne s'ouvre plus !

**Comment by Fchallier** [comment]
Oui pardon FileZilla.  J'ai rajouté la couverture sur le serveur. 
Je viens de vérifier il y a eu seul utilisateur SFTP pour votre site.  On utilise donc le même. 

Peux-tu regarder pour mettre à jour l'application FileZilla  ?

**Comment by Rouergue** [comment]
Je ne vois pas où on peut faire la mise à jour de FileZilla. Faut-il que je télécharge une nouvelle version et que je réinstalle l'application ? En attendant, j'ai toujours le même message : 
![Capture d’écran 2020-02-03 à 16 38 35](https://user-images.githubusercontent.com/10072454/73666901-cbbd0f00-46a3-11ea-8765-47fb04330321.png)
Dans l'immédiat, peux-tu déposer sur le serveur la couv ci-dessous que je viens de mettre à jour, stp ? Merci !
![9782812619441](https://user-images.githubusercontent.com/10072454/73666965-e2fbfc80-46a3-11ea-95ba-992779332f1c.jpg)

**Comment by Rouergue** [comment]
C'est bon, je suis passée sur Cyberduck !
