### ISSUE TITLE
Assimilation de deux titres qui ne sont pas des mêmes auteurs !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#387]
Quid ?

UNE VIGNE BIO DANS MON JARDIN > auteurs : Sonja Schmid & Toni Schmid
LA VIGNE ET SES PLANTES COMPAGNES > auteurs : Yves Darricau & Léa Darricau

Pourtant, au lien suivant, ils se retrouvent sur la même page, sous l'intitulé "du même auteur"
https://www.lerouergue.com/catalogue/la-vigne-et-ses-plantes-compagnes

![Capture d’écran 2020-02-03 à 17 57 10](https://user-images.githubusercontent.com/10072454/73674028-f7de8d00-46af-11ea-8b1e-570e2f613eb0.png)

**Comment by Fchallier** [comment]
J'ai rajouté la condition "(Contributeurs) Élément Field collection : Communicable (= 1)" dans la vue "Catalogue - Livres du même Auteur". 

Il s'affichera donc uniquement les livres dont l'auteur ou le directeur d'ouvrage ou l’illustrateur est communicable.
