### ISSUE TITLE
Dépôt de fichiers sur le serveur

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#388]
En attendant que mon problème avec FileZilla soit résolu (j'ai envoyé un ticket au support Actes Sud), peux-tu mettre les couvs et photos auteurs ci-dessous sur le serveur Rouergue, stp ?
Merci beaucoup !

![9782812619878](https://user-images.githubusercontent.com/10072454/73829320-0c7f6a00-4803-11ea-9cd3-7b878aaf58a2.jpg)
![9782812619977](https://user-images.githubusercontent.com/10072454/73829322-0db09700-4803-11ea-81fa-59619b16cc1d.jpg)
![25917](https://user-images.githubusercontent.com/10072454/73829325-0e492d80-4803-11ea-8c38-0e66c64bfc15.jpg)
![9782812619748](https://user-images.githubusercontent.com/10072454/73829326-0e492d80-4803-11ea-8922-a7d84bceabce.jpg)
![26483](https://user-images.githubusercontent.com/10072454/73829328-0ee1c400-4803-11ea-8e0f-985e835ef1f3.jpg)

**Comment by Fchallier** [comment]
Peux-tu m'envoyer les éléments par Mail ?  Github renomme les fichiers déposés.
