### ISSUE TITLE
Pb de filtres dans la recherche

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#389]
Pourquoi, lorsque je fais une recherche à partir du champ en haut à droite (loupe), ça fonctionne et pas au niveau du grand champ "contenu" de la recherche générale ?

![Capture d’écran 2020-02-13 à 16 23 15](https://user-images.githubusercontent.com/10072454/74450171-f9613f80-4e7d-11ea-9299-799be6e07672.png)
![Capture d’écran 2020-02-13 à 16 23 22](https://user-images.githubusercontent.com/10072454/74450175-f9f9d600-4e7d-11ea-82c3-64ad257d2d4a.png)

**Comment by Fchallier** [comment]
je viens de ré-indexé l'ensemble du site et ça semble bien fonctionner. 

Il faut que je pense à rajouter cela au CronTab du serveur
