### ISSUE TITLE
Création d'un nouveau pays dans la liste sur l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#390]
Il faudrait rajouter LUXEMBOURG, stp : 
 
![Capture d’écran 2020-03-02 à 16 51 26](https://user-images.githubusercontent.com/10072454/75692946-99083580-5ca6-11ea-8dd7-7cd71c3fe346.png)

**Comment by Fchallier** [comment]
Hello, je viens de faire la mise à jour. 

Quand j'aurai fini l'update concernant vos univers, je regarderai comment remplacer ce champ par quelque chose plus pratique.
