### ISSUE TITLE
Titre qui ne remonte pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#394]
Alors que tout est bien validé dans mistral...

![Capture d’écran 2020-09-30 à 09 16 43](https://user-images.githubusercontent.com/10072454/94654726-c204ad80-02fd-11eb-8755-16cf224139f2.png)

**Comment by Fchallier** [comment]
Lorsque la migration sera réalisé sur le nouveau serveur, un crontab sera appliqué pour que les données Mistral soient ajouté tous les soirs.
