### ISSUE TITLE
URGENT : problème affichage photo auteur

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#396]
Bonjour François,
 
Le 21 septembre dernier, j’ai mis en ligne une nouvelle photo pour l’une de nos autrices, Marie-Sabine Roger. Et j’ai vérifié dans Cyberduck, le nouveau fichier a bien été téléchargé.  
 

 
![Unknown](https://user-images.githubusercontent.com/10072454/95308410-2689b480-088a-11eb-8a59-817cc2338ecd.png)
![Unknown](https://user-images.githubusercontent.com/10072454/95308413-27224b00-088a-11eb-8008-c648fffcec81.jpeg)

Or, quand on va sur le site, c’est l’ancienne photo qui apparaît toujours, malgré les caches vidés et ce, quelques soient les navigateurs.
Quid ? J’ai l’impression que la mise à jour du serveur hier soir a aplati la nouvelle photo.
 
![Unknown-1](https://user-images.githubusercontent.com/10072454/95308451-3608fd80-088a-11eb-8ebf-83393b90031c.png)
![Unknown-2](https://user-images.githubusercontent.com/10072454/95308568-5f298e00-088a-11eb-86e3-6e4c29bc9989.png)

C’est d’autant plus ennuyeux que le © n’est pas le même pour les deux photos !
Peux-tu voir d’où ça vient et faire le correctif, stp ?
Merci par avance pour ton aide !

**Comment by Fchallier** [comment]
Je viens de lancer la reconstruction de l'ensemble du cache des images sur le site et ça semble fonctionner. 

Je me note de rajouter cette fonction à chaque mise à jour sur le nouveau serveur.
