### ISSUE TITLE
Changement de l'ordre d'apparition des sous-collections

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#397]
Au niveau du menu pour les romans jeunesse :

![Capture d’écran 2020-10-22 à 15 08 40](https://user-images.githubusercontent.com/10072454/96876532-dcebbd00-1478-11eb-829d-abad5d20edf7.png)

**Comment by Rouergue** [comment]
+ idem pour les romans ados :

![Capture d’écran 2020-10-22 à 15 13 37](https://user-images.githubusercontent.com/10072454/96876923-4f5c9d00-1479-11eb-838d-e04a608b0f75.png)

Cf. mail du 3/12/19 avec l'arborescence détaillée.

![Capture d’écran 2020-10-22 à 15 13 42](https://user-images.githubusercontent.com/10072454/96877006-656a5d80-1479-11eb-9c61-7ea346612ff5.png)

**Comment by Fchallier** [comment]
Updated
