### ISSUE TITLE
Sous-collections qui n'apparaissent pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#398]
Dans la rubrique "Romans 6-11 ans" des Romans Jeunesse, il manque les deux sous-groupes "dacodac" et "boomerang".

![Capture d’écran 2020-10-22 à 15 15 50](https://user-images.githubusercontent.com/10072454/96877338-ca25b800-1479-11eb-9f70-c125c3cebfd5.png)

tic-tac / à la petite semaine / zig zag sont bien "fondues" dans la collection dacodac mais celle-ci doit encore clairement apparaître, ainsi que la coll. boomerang :

![Capture d’écran 2020-10-22 à 15 16 03](https://user-images.githubusercontent.com/10072454/96877310-c5f99a80-1479-11eb-9ffa-b2cf8311250c.png)

**Comment by Fchallier** [comment]
Quand je me suis connecté à l'instant c'est vrai qu'il n'y avait pas les deux sous-univers de romans 6-11 ans. 

J'ai vidé le cache et ça semble bien fonctionner. 

Faut-il afficher  les univers tic-tac / à la petite semaine / zig zag ?

**Comment by Rouergue** [comment]
Non, c'est parfait ainsi.
Merci beaucoup !
