### ISSUE TITLE
Changement de l'interface admin pour l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#399]
Est-ce normal que l’interface de modification (dans l’agenda par exemple) ait complétement changé ?
La saisie semble inclure du langage html...

![Unknown](https://user-images.githubusercontent.com/10072454/97876755-8d30af80-1d1c-11eb-8746-f35de5771fd9.png)
![Capture d’écran 2020-11-02 à 14 49 47](https://user-images.githubusercontent.com/10072454/97876770-928dfa00-1d1c-11eb-9f5b-501ad0965c36.png)

**Comment by Fchallier** [comment]
Je viens d'appliquer un modification ça devrait fonctionner.

**Comment by Rouergue** [comment]
Oui, ça a l'air de fonctionner, merci !
