### ISSUE TITLE
Problème de polices sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#400]
qui ne correspond pas à ce qu'on avait avant...

![Capture d’écran 2020-11-02 à 15 10 18](https://user-images.githubusercontent.com/10072454/97877586-aede6680-1d1d-11eb-951d-fcb2150706d6.png)

**Comment by Fchallier** [comment]
Je n'ai pas ce bug de mon côté, tu me diras si cela se produit toujours chez toi ?

**Comment by Rouergue** [comment]
C'est parti au moment où tu as fait les derniers rectificatifs post-changement de serveur !
