### ISSUE TITLE
Auteurs et titres qui ne sont pas automatiquement saisissables dans la liste pour l'agenda

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#401]
Si on n'a pas le Node correspondant, on ne peut pas les retrouver juste en tapant les premières lettres.

![Capture d’écran 2020-11-02 à 15 10 01](https://user-images.githubusercontent.com/10072454/97877855-14caee00-1d1e-11eb-811e-44b4ba817337.png)

**Comment by Fchallier** [comment]
La solution apporté dans le ticket #399  devrait résoudre le ticket suivant
