### ISSUE TITLE
Titre qui n'apparaît pas dans la bibliographie d'un auteur car la fiche livre ne fait pas remonter son nom

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#402]
La fiche de _Bonheur fantôme_ est bien présente sur le site (https://www.lerouergue.com/catalogue/bonheur-fantome) mais ce titre n’apparaît pas dans la biblio d’Anne Percin parce que la fiche livre, pour une raison qui m’échappe, n’a pas fait remonter le nom de l’autrice. 

![Unknown](https://user-images.githubusercontent.com/10072454/98128710-863ea400-1eb8-11eb-89b3-078a53c95a34.png)

**Comment by Rouergue** [comment]
En fait, je crois que j’ai trouvé toute seule : l’autrice n’était pas cochée « communicable » sur la fiche Mistral.
C’est maintenant chose faite ; peux-tu me confirmer que le changement sera bien pris en compte à la prochaine mise à jour du serveur ? Merci !

**Comment by Fchallier** [comment]
C'était bien ça  ;)
