### ISSUE TITLE
Groupe ID et Contributor field requis

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#403]
Alors que j'ai juste voulu rajouter une vidéo sur une fiche livre, je ne peux plus enregistrer la fiche car j'ai le message d'erreur "Groupe ID requis et Contributor field". Quid ?

![Capture d’écran 2020-11-12 à 09 40 47](https://user-images.githubusercontent.com/10072454/98916240-3456d900-24cb-11eb-85c0-9ae265331d1e.png)

**Comment by Fchallier** [comment]
Je viens de faire une petite mise à jour, ça devrait fonctionner.

**Comment by Rouergue** [comment]
Ça fonctionne pour le groupe ID mais un message me réclame encore le "contributor fied". Je n'ai pu enregistrer la fiche que parce que j'ai supprimé manuellement le champ "contributor" qui était vide. Est-ce normal ?

![Capture d’écran 2020-11-12 à 11 50 23](https://user-images.githubusercontent.com/10072454/98952631-f625dd80-24fb-11eb-84c7-0db755974793.png)

![Capture d’écran 2020-11-12 à 11 50 28](https://user-images.githubusercontent.com/10072454/98952638-f8883780-24fb-11eb-9747-08449cefd855.png)

**Comment by Rouergue** [comment]
Ça le fait à chaque fois que je veux modifier une fiche déjà existante

![Capture d’écran 2020-11-12 à 15 54 08](https://user-images.githubusercontent.com/10072454/98955663-726df000-24ff-11eb-8f7e-5b682ff31a43.png)

**Comment by Fchallier** [comment]
Je viens d'appliquer une petite modification tu me diras si ça fonctionne à nouveau ?

**Comment by Rouergue** [comment]
Oui, ça a l'air de fonctionner, merci !
