### ISSUE TITLE
Pourquoi le contributeur n'apparaît pas ?

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#404]
![Capture d’écran 2020-11-23 à 10 01 27](https://user-images.githubusercontent.com/10072454/99944303-ecf60580-2d72-11eb-9c97-1aad09c8b261.png)

**Comment by Rouergue** [comment]
idem

![Uploading Capture d’écran 2020-11-23 à 10.04.08.png…]()

**Comment by Rouergue** [comment]
idem pour celui-ci (alors qu'il est remonté depuis longtemps sur le site). C'est comme si tous les titres qui doivent paraître dans plus d'un mois ne peuvent pas afficher le contributeur...

![Capture d’écran 2020-11-23 à 10 19 10](https://user-images.githubusercontent.com/10072454/99945726-6f7fc480-2d75-11eb-9b6a-4f40e52af1bc.png)

**Comment by Fchallier** [comment]
La dernière mise à jour semble avoir corrigé le problème.  Je rajoute un ticket pour que les mises à jour soient lancées tous les soirs de la semaine.
