### ISSUE TITLE
URGENT : modifications non prises en compte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#405]
Toutes les modifications que j'ai faites sur le site hier (dont l'ajout de 4 couvertures) n'ont pas été prises en compte. Ce matin, à nouveau, les couvs sont indiquées manquantes. 

![Capture d’écran 2020-11-25 à 09 26 26](https://user-images.githubusercontent.com/10072454/100201567-7f77df80-2f00-11eb-90de-9e082ec9aec2.png)

**Comment by Fchallier** [comment]
Tu as déposer les couvertures dans le dossier prévu à cet effet  ? Avec cyberduck  ? 

Si tu ajoutes manuellement les couvertures via le site elles sont écrasé lors des mise à jours.

**Comment by Rouergue** [comment]
Oui, je les avais bien déposées dans cyberduck, comme d'habitude.

![Capture d’écran 2020-11-25 à 10 28 35](https://user-images.githubusercontent.com/10072454/100208443-05982400-2f09-11eb-9775-58e259489804.png)

![Capture d’écran 2020-11-25 à 10 28 21](https://user-images.githubusercontent.com/10072454/100208454-07fa7e00-2f09-11eb-8646-7b2f034aae71.png)

**Comment by Fchallier** [comment]
Ha mince mais tu n'es pas sur le bon serveur... je t'avais envoyé les identifiants  ? 

Tu me diras

**Comment by Rouergue** [comment]
Effectivement, j'étais sur l'ancien serveur ! J'avais oublié que la migration du site impactait aussi cyberduck... J'ai donc rentré les nouveaux codes et réimporté les visuels et ça a l'air bon. Par contre, ça fait quand même de drôles de choses : "empreinte inconnue" et "transfert incomplet" dans un premier temps (j'ai dû re-télécharger une 2e fois les images une à une).

![Capture d’écran 2020-11-25 à 10 44 22](https://user-images.githubusercontent.com/10072454/100211584-9a505100-2f0c-11eb-87bd-09445a3ec6f8.png)

![Capture d’écran 2020-11-25 à 10 52 14](https://user-images.githubusercontent.com/10072454/100211595-9cb2ab00-2f0c-11eb-8401-23ee11e4f170.png)

**Comment by Fchallier** [comment]
Pour "empreinte inconnue" il faut toujours autoriser. Pour le transfert incomplet cela peut venir peut-être du réseau...  

Je viens de lancer à nouveau la mise à jour et ça semble fonctionner.

**Comment by Rouergue** [comment]
Super, merci beaucoup !
