### ISSUE TITLE
URGENT : rubrique vide !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#407]
La rubrique des romans 6 - 11 ans est vide ! On devrait y retrouver dedans tous les titres des coll. dacodac, boomerang, zig zag, tic-tac et à la petite semaine. 

![Capture d’écran 2020-11-25 à 16 10 34](https://user-images.githubusercontent.com/10072454/100246186-24161380-2f39-11eb-9764-083f157e1bf1.png)

Par ailleurs, est-il possible de mettre les rubriques dans l'ordre suivant :

Romans Jeunesse
- romans 6-11 ans (et non pas "dès 6 ans")
- romans ados
- poches jeunesse

![Capture d’écran 2020-11-25 à 16 09 52](https://user-images.githubusercontent.com/10072454/100246218-2bd5b800-2f39-11eb-8ad1-41ea57b4b46e.png)

**Comment by Fchallier** [comment]
La configuration du menu et des univers avaient sauté... Et j'ai vraiment du mal à comprendre la raison... 

Je viens de reconfigurer entièrement le menu et la taxonomie Univers ça semble avoir corrigé le problème.

Tu me diras,

**Comment by Rouergue** [comment]
C'est tout bon, merci beaucoup !
