### ISSUE TITLE
Liens rompus...

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#408]
... certainement au moment du changement de serveur. Cf. ci-dessous le message d'un de nos auteurs : 

![Capture d’écran 2020-11-30 à 09 22 41](https://user-images.githubusercontent.com/10072454/100585303-a6ae2280-32ed-11eb-8774-999d7bbd024a.png)

Effectivement, tous les liens que j'ai mis (il y a longtemps) au niveau de la fiche article ne fonctionnent plus :

![Capture d’écran 2020-11-30 à 09 23 36](https://user-images.githubusercontent.com/10072454/100585431-dfe69280-32ed-11eb-956b-da941233df49.png)

![Capture d’écran 2020-11-30 à 09 20 41](https://user-images.githubusercontent.com/10072454/100585446-e70da080-32ed-11eb-8bd7-56342afd3ee0.png)

![Capture d’écran 2020-11-30 à 09 21 20](https://user-images.githubusercontent.com/10072454/100585458-eb39be00-32ed-11eb-9d32-595acc6dcf61.png)

Est-ce que cela signifie que tous les liens vers des docs importés initialement mis sur le premier serveur n'ont pas été basculés et que d'autres liens ont été rompus (au niveau de la Fabrique, notamment) ?

**Comment by Fchallier** [comment]
Bonjour Mathilde,  

Je viens de regarder et effectivement les fichiers avec cette extension n'ont pas été importés. Je viens d'en importer une partie, je regarde pour le reste des dossiers. bien à toi,

**Comment by Fchallier** [comment]
Je viens de faire le tour et l'ensemble des fichiers semblent bien être présent. 
Bien à toi,

**Comment by Rouergue** [comment]
Merci beaucoup !
