### ISSUE TITLE
Pb de police sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#409]
On ne retrouve pas la police habituelle...

![Capture d’écran 2020-11-30 à 15 08 35](https://user-images.githubusercontent.com/10072454/100619853-fa386480-331d-11eb-81a1-c0680f3ccf65.png)

![Capture d’écran 2020-11-30 à 15 08 31](https://user-images.githubusercontent.com/10072454/100619857-fc022800-331d-11eb-92aa-847d5a027203.png)

**Comment by Fchallier** [comment]
Alors j'ai testé de mon côté et je n'arrives à reproduire l'erreur... Tu utilises un navigateur en particulier  ? 
![image](https://user-images.githubusercontent.com/9974750/100635763-30331400-3331-11eb-8b65-4b05d7ff9b17.png)

**Comment by Rouergue** [comment]
Oui, j'utilise essentiellement firefox et je pense que le pb vient de là car avec chrome et safari que je viens de tester, il n'y a pas le même problème de polices (j'aurais pu commencer par-là !). J'ai de plus en plus de bug avec firefox (dont l'impossibilité de me connecter à FB) et les vidages de préférences ou réparations n'y changent rien. Peut-être qu'il faut que je le réinstalle complètement ?

**Comment by Fchallier** [comment]
Ouai c'est étrange... car de mon côté j'utilise aussi Firefox et ça semble bien fonctionner.

Donc soit vérifier les mises à jour du navigateur soit réinstaller...

**Comment by Rouergue** [comment]
C'est bizarre, j'ai l'impression que je n'ai le pb de polices que en mode "admin" (quelque soit le navigateur) ! Quand je vais directement sur le site du Rouergue, ça ne le fait pas !!!

![Capture d’écran 2020-12-01 à 14 10 02](https://user-images.githubusercontent.com/10072454/100745014-f4568800-33de-11eb-9772-7a6a58630170.png)

![Capture d’écran 2020-12-01 à 11 41 54](https://user-images.githubusercontent.com/10072454/100745017-f587b500-33de-11eb-9b70-f50461d5dd9b.png)

**Comment by Fchallier** [comment]
#412
