### ISSUE TITLE
Ordre modifié pour le menu vertical

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#410]
L'ordre de menu en vertical ne respecte plus la hiérarchie initiale (cf. modèle et ordre sur le menu horizontal) :

![Capture d’écran 2020-12-08 à 14 51 03](https://user-images.githubusercontent.com/10072454/101613860-89bfd080-3a0c-11eb-8a41-872ed9e4884b.png)

![Capture d’écran 2020-12-08 à 14 50 51](https://user-images.githubusercontent.com/10072454/101613873-8c222a80-3a0c-11eb-89a5-bdb92768defe.png)

**Comment by Rouergue** [comment]
En fait, je me rends compte que l'ordre sur le menu horizontal n'est pas le bon non plus. Il faudrait mettre les rubriques dans l'ordre suivant (sur le menu horizontal et le menu vertical) :

Littérature
La brune
Rouergue noir
Nature & Jardin
Gastronomie
Loisirs créatifs
Art & Histoire
Régions
Albums jeunesse
Romans jeunesse
Epik (fantasy)
Livre pratique jeunesse
Graphisme & Illustrations
Numérique

Merci beaucoup !

**Comment by Rouergue** [comment]
Pourras-tu changer l'ordre des rubriques assez vite, stp ? L'arborescence actuelle (par ordre alpha) n'a aucun sens pour nous. 
Merci beaucoup !

**Comment by Fchallier** [comment]
Bonjour Mathilde et meilleurs vœux pour cette nouvelle année ! 

Je viens d'appliquer la correction sur le site. 

Bien à toi,
