### ISSUE TITLE
Propositions de résultats dans la recherche manquantes

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#412]
Je n'ai plus les propositions qui s'affichent comme avant (avec les petites vignettes) quand je tape les premières lettres d'un mot dans la recherche. 

![Capture d’écran 2020-12-15 à 18 15 47](https://user-images.githubusercontent.com/10072454/102250636-120a0e00-3f04-11eb-96a8-e916ada3eab3.png)

Et, de la même manière, il n'y a plus la mémoire des adresses déjà saisies au niveau de l'agenda. Ce serait bien pratique que je puisse retrouver tout ça ; cela me ferait gagner pas mal de temps !

**Comment by Fchallier** [comment]
Alors de mon côté je n'arrive pas à reproduire l'erreur...ça fonctionne sur l'ensemble des navigateurs. 

Peux-tu m'indique le navigateur que tu utilise et sa version  ?

**Comment by Rouergue** [comment]
Je suis en général sur firefox 84.0.2

![Capture d’écran 2021-01-28 à 17 28 56](https://user-images.githubusercontent.com/10072454/106168243-54bf3700-618e-11eb-80ae-ecccd2a3c152.png)

**Comment by Rouergue** [comment]
Mais j'ai des pbs de polices aussi, pour la partie admin

![Capture d’écran 2021-01-28 à 17 29 29](https://user-images.githubusercontent.com/10072454/106168323-6b658e00-618e-11eb-8686-de5b3b6262df.png)

... que je n'ai pas en version "publique"

![Capture d’écran 2021-01-28 à 17 30 04](https://user-images.githubusercontent.com/10072454/106168369-7c160400-618e-11eb-9fe5-f3f6025d0a7b.png)

C'est très étrange...

**Comment by Fchallier** [comment]
Ok j'ai compris  ! Tu n'es pas sur l'adresse  en HTTPS, j'ai l'impression que la redirection ne fonctionne pas ! 

Je regarde ça tout de suite.

Penses à bien te connecter via cette URL : https://www.lerouergue.com/
et pas http://www.lerouergue.com/

**Comment by Fchallier** [comment]
Mises à jour du fichier .htacces
`# uncomment the following:
   #1
   RewriteCond %{HTTP_HOST} .
   RewriteCond %{HTTP_HOST} !^www\. [NC]
   RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  
   # 2 Redirect to HTTPS
   RewriteCond %{HTTPS} off
   RewriteCond %{HTTP:X-Forwarded-Proto} !https
   RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
