### ISSUE TITLE
Changement de prix sur mistral non pris en compte sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#413]
Quid ? 

![Capture d’écran 2021-01-26 à 10 17 43](https://user-images.githubusercontent.com/10072454/105825381-d3b24500-5fbf-11eb-8ba2-42fd90502cdb.png)

![Capture d’écran 2021-01-26 à 10 18 04](https://user-images.githubusercontent.com/10072454/105825392-d7de6280-5fbf-11eb-9236-b8d6816e341a.png)

**Comment by Fchallier** [comment]
Alors là... Je viens de vérifier dans la base de donnée, le prix ressort bien à 12,80€
J'ai lancé plusieurs fois le système de mise à jour, mais c'est toujours l'ancien site qui remonte... 

J'ai l'impression que la requête ne prend pas les prix validés, mais le premier prix renseigné... Je regarde pour corriger cela.

**Comment by Fchallier** [comment]
C'est ok, il y avait une condition manquante dans la requête de l'import. 

`  $query->join('realprice','rp','rp.articleid=a.articleid');`
Modifié en 
`  $query->join('realprice','rp','rp.articleid=a.articleid AND rp.iscurrentprice=1');`
