### ISSUE TITLE
URGENT : titre qui ne remonte pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#414]
Alzira a confirmé hier le prix de CONSTRUIRE SON SOL dans mistral. Peux-tu relancer le dump pour que ce titre remonte sur le site (comme tous les autres titres prévus en février), stp ?
Merci !

![Capture d’écran 2021-01-28 à 13 52 20](https://user-images.githubusercontent.com/10072454/106141360-419d6e80-6170-11eb-9402-adb02c7cd02d.png)

**Comment by Fchallier** [comment]
La mise à jour est lancée, je te tiens au courant dès que c'est ok.

**Comment by Fchallier** [comment]
C'est ok  sur le site.

**Comment by Rouergue** [comment]
Super, merci beaucoup !

De : François Challier <notifications@github.com>
Répondre à : EditionsDuRouergue/lerouergue <reply@reply.github.com>
Date : jeudi 28 janvier 2021 à 15:25
À : EditionsDuRouergue/lerouergue <lerouergue@noreply.github.com>
Cc : Mathilde DAVIENNE <mathilde.davienne@lerouergue.com>, Author <author@noreply.github.com>
Objet : Re: [EditionsDuRouergue/lerouergue] URGENT : titre qui ne remonte pas (#414)


C'est ok sur le site.
