### ISSUE TITLE
URGENT : pb de mise à jour photo auteur

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#415]
J'ai changé la photo d'une autrice hier mais, ce matin, je me rends compte que l'ancienne photo (dont nous n'avons plus les droits) est toujours en ligne. Pourtant, j'ai bien mis sur nouveau fichier sur le serveur cyberduck. Est-ce parce que le dump n'a pas été fait ? 
Merci pour ton aide !

![Capture d’écran 2021-02-09 à 10 41 57](https://user-images.githubusercontent.com/10072454/107345296-b56e3e00-6ac3-11eb-9930-394ffc29a74a.png)

![Capture d’écran 2021-02-09 à 10 42 28](https://user-images.githubusercontent.com/10072454/107345314-b99a5b80-6ac3-11eb-82da-972284e21d45.png)

**Comment by Fchallier** [comment]
Hello  ! 

Cela vient du cache des images, il y a un cache sur l'ensemble des images pour améliorer les performances du site. 
Si tu rencontres ce genre de soucis, dans le menu admin  "Rouergue Admin" du a l'option "Vider le Cache des images" puis tu cliques sur Flush. 

Je viens de vider le cache des  images et la photo de l'auteur remonte ;) 


Bien à toi,

**Comment by Rouergue** [comment]
ok, merci.
Par contre, je n'ai pas l'option "vider le cache des images" dans admin. 
à chaque fois, je clique sur "vider tous les caches / pages et autres" mais ça ne fonctionne pas toujours !

![Capture d’écran 2021-02-09 à 11 02 06](https://user-images.githubusercontent.com/10072454/107347685-5eb63380-6ac6-11eb-94c3-8608cddf4750.png)

**Comment by Fchallier** [comment]
Quand tu passes ta souris sur "ROUERGUE ADMIN"  tu as le menu qui apparait  ? 

![screenshot-www lerouergue com-2021 02 09-11_07_15](https://user-images.githubusercontent.com/9974750/107348227-0a5f8380-6ac7-11eb-88a6-f80d36e81c63.png)

**Comment by Rouergue** [comment]
Oui, j'ai le menu qui apparaît... mais pas avec les mêmes options !

![Capture d’écran 2021-02-09 à 12 06 27](https://user-images.githubusercontent.com/10072454/107355088-4ac2ff80-6acf-11eb-82fc-a1ae0c860022.png)

**Comment by Rouergue** [comment]
Il en manque une !

**Comment by Fchallier** [comment]
Je viens de modifier les droits tu me diras

**Comment by Rouergue** [comment]
ça marche, merci !
Il faut donc que je clique dessus après une mise à jour puis sur FLUSH, c'est bien ça ?

**Comment by Fchallier** [comment]
En fait tu peux lancer l'opération quand tu veux. Lors d'une mise à jour l’opération est lancé automatiquement, mais si tu constates qu'un visuel n'est pas à jour ou que tu viens de déposer un nouveau visuel n'hésites pas à le cliquer sur Flush.
