### ISSUE TITLE
Visuel disparu

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#416]
Pourquoi la couv que j'ai mise en ligne la semaine dernière (et déposée sur le serveur) a disparu ?

![Capture d’écran 2021-02-10 à 15 58 03](https://user-images.githubusercontent.com/10072454/107527143-d795b800-6bb8-11eb-9554-3d0bc8005a9d.png)

Il s'agit du titre LA SOURCIÈRE (9782812621734)

**Comment by Fchallier** [comment]
Je ne retrouve pas le visuel dans dossier dans sur le serveur... 

Peut-tu renvoyer la couverture uniquement sur le serveur et je relance une mise à jour tout de suite.

**Comment by Rouergue** [comment]
Je n'arrive plus à rentrer dans cyberduck et les codes que j'avais ne semblent plus être les bons... Est-ce que je suis repartie sur une ancienne version ?

![Capture d’écran 2021-02-10 à 16 55 15](https://user-images.githubusercontent.com/10072454/107535206-d36d9880-6bc0-11eb-8b54-ab7ec90e1fd1.png)


Sinon, peux-tu me renvoyer les derniers, stp ?
(c'est étrange, ces derniers jours, je n'avais aucun pb pour me connecter...)

**Comment by Fchallier** [comment]
Alors c'est bien les identifiants... Il doit y avoir un soucis avec Cyberduck probablement. 

Je viens de renvoyer les couverture sur le serveur. ça devrait être bon d'ici 15 minutes.

**Comment by Rouergue** [comment]
Ok, merci. J'ai pas mal de souci de connexion aujourd'hui. Je bosse chez moi et ma livebox a lâché à midi. Depuis, je suis en partage de co à partir de mon portable. Je ne sais pas si c'est lié... Le dépanneur vient demain matin !

**Comment by Rouergue** [comment]
Du coup, pourrais-tu mettre sur le serveur les deux couvs suivantes + la photo auteur que j'ai mises à jour aujourd'hui, stp ?

![9782812621734](https://user-images.githubusercontent.com/10072454/107538853-ade28e00-6bc4-11eb-8c1a-119fff101b0d.jpg)
![9782812619625](https://user-images.githubusercontent.com/10072454/107538859-af13bb00-6bc4-11eb-9276-68d499f63e87.jpg)
![26155](https://user-images.githubusercontent.com/10072454/107538868-b0dd7e80-6bc4-11eb-8105-633a46e09a34.jpg)

**Comment by Fchallier** [comment]
La photo de l'auteur c'est **Dave Goulson** avec l'Id contributeur  : 26155 ? 

GitHub supprime les nom des fichiers...

**Comment by Rouergue** [comment]
ah oui, c'est bien ça, merci !

**Comment by Fchallier** [comment]
ça me semble à jour ;)
