### ISSUE TITLE
URGENT : lancement de mise à jour

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#417]
Alzira vient de valider le prix d'un titre qui était en stand-by. Peux-tu relancer ce matin une mise à jour du serveur pour que le livre remonte rapidement sur le site, stp ?

![Capture d’écran 2021-02-16 à 09 54 50](https://user-images.githubusercontent.com/10072454/108040101-2fab3f00-703d-11eb-9e05-4f94d801b83c.png)

**Comment by Fchallier** [comment]
Hello,  

Je viens de lancer la mise à jour et le titre semble remonter.

Pour info je suis sur le point de finir un système de mise à jour automatique. L'idée serait de lancer au minimum un fois par jour la mise à jour du site, avec import de couvertures.
