### ISSUE TITLE
URGENT : titre qui a disparu de la circulation !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#418]
Il s'agit du JARDIN JUNGLE (9782812619625) à paraître le 10/03/21 qui était bien en ligne sur le site et qui n'y ait pluuuuuuus !

![Capture d’écran 2021-03-04 à 10 38 33](https://user-images.githubusercontent.com/10072454/109943727-c92d4e80-7cd5-11eb-8faa-0fa6068126b7.png)

**Comment by Fchallier** [comment]
Celui-ci : https://www.lerouergue.com/catalogue/le-jardin-jungle ? 

Par contre oui il ne remonte pas dans la page catalogue... Mais il remonte bien dans https://www.lerouergue.com/catalogue/nature-jardin

**Comment by Fchallier** [comment]
Il doit y avoir un probablement avec la view, je regarde ça

**Comment by Rouergue** [comment]
oui, il s'agit bien de ce titre. C'est étrange qu'il ne remonte pas à tous les niveaux... (surtout que c'était le cas précédemment !). Tu me tiens au courant ?

**Comment by Rouergue** [comment]
Et, ce qui est très bizarre, c'est que la fiche est remontée incomplète. J'avais précédemment ajouté une vidéo + un feuilletage issuu et tout a sauté ! Bon. je les remets, du coup.

**Comment by Rouergue** [comment]
Et il a aussi sauté du bandeau des nouveautés alors qu'il y était bien !

![Capture d’écran 2021-03-04 à 11 01 33](https://user-images.githubusercontent.com/10072454/109946900-0a732d80-7cd9-11eb-8b94-d013a9321372.png)

**Comment by Fchallier** [comment]
J'ai l'impression que le titre remonte en page 2 du catalogue.  Je n'ai rien modifié au niveau de la view... 

J'ai pas trop d'explications à ce comportement...

**Comment by Fchallier** [comment]
Par contre si la fiche remonte incomplète, cela veut peut-être dire que le titre a été supprimé entre deux mises à jour. Si un titre ne rentre plus dans les critères de la requête SQL alors celui-ci est supprimer lors de la mise à jour. 

Je vois dans mistral qu'une correction a été réaliser au niveau du prix le  3 mars 2021. Cela vient peut-être de là.

**Comment by Fchallier** [comment]
Je viens de constater que plusieurs données ont disparu... Je passe le site en mode construction afin de faire remonter un backup de la base de données

**Comment by Fchallier** [comment]
Le site n'est toujours pas en ligne... J'ai un gros problème avec la base de données. 

Je te tiens au courants dès que c'est ok.

**Comment by Fchallier** [comment]
Mathilde,  Désolé pour la gène occasionné, le site est resté inactif pendant quelques heures. 

J'ai été obligé d'utiliser un dump du site du 2 mars dans la nuits Donc les quelques opérations que tu as réalisées entre le 3 et aujourd’hui on probablement disparu...  C'était la seule solution pour partir sur une base propre du site. 

Je continue de chercher pourquoi il y a eu autant de soucis. bien à toi,

**Comment by Rouergue** [comment]
Aaaargh ! C'est justement une semaine où j'avais fait beaucoup d'ajouts et de modifs sur le site (couvs, auteurs, agenda, vidéos... et même une Fabrique qui a disparu 😥 !). Bon. As-tu moyen d'avoir une liste des changements que j'avais fait, histoire que je n'en oublie pas au passage, stp ?

**Comment by Fchallier** [comment]
Je suis vraiment désolé pour cela  ! et non je n'ai pas le moyen de te communiquer les changements... 

Par contre je vais relacer le système de mise à jour avant la fin de journée. Il faudrait ne rien ajouter sur le site pour le moment afin de bien vérifier que tout fonctionne correctement et ne pas répéter les opérations en cas de perte de données.

**Comment by Rouergue** [comment]
Ok, ça veut dire que je ne touche pas au site aujourd'hui alors. J'attendrai demain pour remettre en ligne les posts et éléments disparus. Tu pourras me faire signe quand ce sera bon, stp ? On peut se faire un point par tél. ou par teams demain matin si tu veux.

**Comment by Fchallier** [comment]
Mathilde,  
Je viens de lancer le système de mise à jour, les titres semblent bien remonter et il n'y a pas de doublon ou de pertes. 

J'ai désactivé temporairement les mises à jour automatique car c'est probablement celles-ci qui ont surchargé notre serveur et générer des problèmes. 

Désolé encore pour gêne occasionnée, on peut s'appeler demain si besoin.
