### ISSUE TITLE
Pb affichage et remontées des auteurs

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#420]
Sais-tu pourquoi certains auteurs notés non communicables sur mistral remontent quand même sur le site ?
Pour les cas cités par Nathalie (cf. mail), je viens de supprimer manuellement la fiche mais ce n’est pas la première fois que ça arrive. C’est bizarre car ils ne remontaient pas comme ça auparavant. Est-ce dû au changement de serveur ?

Certains auteurs sont même en double (pour un même ID) 

![Capture d’écran 2021-03-04 à 17 06 32](https://user-images.githubusercontent.com/10072454/109993964-2264a480-7d0d-11eb-9b13-0e663ba2f034.png)

Quand on veut supprimer une fiche, le cartouche suivant s'affiche

![Capture d’écran 2021-03-04 à 17 07 12](https://user-images.githubusercontent.com/10072454/109994044-34dede00-7d0d-11eb-9098-b336ac3de276.png)
(il faut mettre un "." dans la case prénom pour pouvoir supprimer la fiche ensuite).

De drôles de choses apparaissent au niveau de l'affichage de la rubrique et certaines tuiles sont manquantes

![Capture d’écran 2021-03-04 à 17 08 24](https://user-images.githubusercontent.com/10072454/109994156-52ac4300-7d0d-11eb-99cd-01cc4ff5ef86.png)

![Capture d’écran 2021-03-04 à 17 08 33](https://user-images.githubusercontent.com/10072454/109994163-53dd7000-7d0d-11eb-9ad7-7dd76b1a191b.png)

**Comment by Rouergue** [comment]
Au secooooooours !

J'ai voulu rajouter une photo sur une fiche auteur et je me suis rendu compte que le prénom a disparu et que le nom + prénom se retrouve à la place du Titre ??? Qu'est ce qui se passe ?

![Capture d’écran 2021-03-04 à 17 22 11](https://user-images.githubusercontent.com/10072454/109995171-58565880-7d0e-11eb-9b2e-56e349c2b5b4.png)

Je n'ose plus rien toucher ; ça a l'air de planter complètement !

**Comment by Rouergue** [comment]
pour pouvoir sauvegarder cette fiche, j'ai quand même rentré le prénom à la main mais il y a quand même de sérieux problèmes !

**Comment by Fchallier** [comment]
Mathilde, il ne faut pas modifier à la main les éléments importés depuis la base Mistral ! (fiche auteur / fiche livre)  ça peut par la suite bloquer le système de mise à jour... 

Si tu souhaites mettre à jour une couverture il faut la déposer en SFTP dans le dossier cover-images et respecter la règle de nommage **gendcode.jpg**

Si tu souhaites mettre à jour une photo d'auteur il faut la déposer en SFTP dans le dossier contributor-picture, et respecter la règle de nommage **idcontributeur.jp**

Concernant la fiche auteur je viens d'enlever l'option pour rendre obligatoire le nom et le prénom. Mais cela ne change rien car **il important de ne jamais plus modifier une fiche auteur ou alors en cas d’extrême urgence !** 


Pour le "PAS DE VALEUR" je viens de rajouter une condition dans la view des auteurs. C'est corrigé. 
`**Critères de filtrage**
Contenu : Published status (Oui)  ET (AND)
Contenu : Type (= Contributor)  ET (AND)
Contenu : Nom de tri (non vide)`

**Comment by Fchallier** [comment]
Dans le filtrage de la lettre "L" je n'ai pas les même résultats que toi... 
![Uploading screenshot-www.lerouergue.com-2021.03.04-17_52_58.png…]()

**Comment by Fchallier** [comment]
Pour le moment je laisse comme cela, Si c'est ok pour toi on regarde cela ensemble dès demain après la mise à jour de cette nuit ?

**Comment by Rouergue** [comment]
D'habitude, je ne modifie jamais les fiches à la main. Mais je croyais que lorsqu'il n'y avait aucune photo auteur, on pouvait la uploader sur le site, tout en la mettant sur le serveur SFTP. Je ne serai pas là demain car je ne travaille pas le vendredi mais on peut faire un point là-dessus ensemble dès lundi matin, si tu es dispo ? 
Merci et bonne fin de semaine.
