### ISSUE TITLE
Non prise en compte des derniers fichiers envoyés sur le serveur hier

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#422]
Par exemple, j'ai déposé hier sur le serveur l'image suivante (dessin), or ce matin, c'est toujours la photo précédente qui apparaît en ligne (sachant que j'ai vidé les caches).

![78363](https://user-images.githubusercontent.com/10072454/110598219-ccb35080-8181-11eb-86aa-c04e362cd559.jpg)

![Capture d’écran 2021-03-10 à 09 18 26](https://user-images.githubusercontent.com/10072454/110598237-d046d780-8181-11eb-8c57-23822f0d2874.png)

**Comment by Fchallier** [comment]
Mathilde,  

Je suis actuellement dans le train en direction de Paris.  

Je regarde ça dès que j'arrive.

**Comment by Rouergue** [comment]
Pas plus de changement ce matin.
Et toujours aucune trace sur le site des 3 fichiers ci-dessous déposés sur le serveur hier et avant-hier.

![78363](https://user-images.githubusercontent.com/10072454/110757975-46177580-824c-11eb-84d9-96ec078e5986.jpg)
![11022](https://user-images.githubusercontent.com/10072454/110757988-4b74c000-824c-11eb-905c-497c9784666e.jpg)
![9782812622021](https://user-images.githubusercontent.com/10072454/110757999-4dd71a00-824c-11eb-819e-8417cf5fef06.jpg)
