### ISSUE TITLE
URGENT : pages auteurs absentes et titres nouveautés disparus !!!

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#426]
C'est très embêtant car nous sommes en train de sponsoriser un post FB qui renvoie vers la page de Peter May ! Et le titre Quarantaine a même disparu... Au secouuuuuurs ! Visiblement, il manque toutes les nouveautés dans le catalogue. 

![Capture d’écran 2021-03-16 à 10 52 07](https://user-images.githubusercontent.com/10072454/111289695-b146ba80-8645-11eb-90f2-4b3bcedd86e6.png)

**Comment by Fchallier** [comment]
L'import de la BDD vient de se terminer. Ça te semble à jour  ?

**Comment by Rouergue** [comment]
Oui, à peu près. Sauf les deux dernières couvs ci-dessous que j'ai déposées sur le serveur hier et qui ne sont donc pas remontées. 

![Capture d’écran 2021-03-16 à 13 43 31](https://user-images.githubusercontent.com/10072454/111310840-d0514680-865d-11eb-8f90-8513d2331df9.png)
![9782812621864](https://user-images.githubusercontent.com/10072454/111310859-d3e4cd80-865d-11eb-803a-0342843a4bf8.jpg)
![9782812621963](https://user-images.githubusercontent.com/10072454/111310860-d3e4cd80-865d-11eb-841a-7547cb0b2e1d.jpg)

Côté rubrique auteurs, il y a encore de drôles de choses qui se baladent...

![Capture d’écran 2021-03-16 à 13 43 54](https://user-images.githubusercontent.com/10072454/111310873-d810eb00-865d-11eb-8482-3255dd286c7f.png)

**Comment by Fchallier** [comment]
![screenshot-www lerouergue com-2021 03 16-14_10_13](https://user-images.githubusercontent.com/9974750/111314230-7c486100-8661-11eb-8f17-b9fa46e777d9.png)

De mon côté ça remonte bien... pour le reste du sites c'est ok  ?  Pas top de perte de contenu  ?

Je regarde pour les auteurs

**Comment by Rouergue** [comment]
Ah oui, ça y est, les deux couvs sont bien remontées. Ça devait être un pb de cache. Pour le reste, j'ai l'impression que c'est tout bon ! Merci beaucoooooup !
