### ISSUE TITLE
auteur en double (et qui n'apparaît pas dans le catalogue des auteurs)

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#428]
Quand je fais une recherche sur Laurent COLSON, le résultat m'annonce deux fiches (?). Par ailleurs, je ne retrouve pas cet auteur dans la rubrique AUTEURS par ordre alpha. 

![Capture d’écran 2021-03-23 à 15 27 41](https://user-images.githubusercontent.com/10072454/112162578-78ca5200-8bec-11eb-9833-24a97d1db6cc.png)

![Capture d’écran 2021-03-23 à 15 27 13](https://user-images.githubusercontent.com/10072454/112162602-7cf66f80-8bec-11eb-9973-7bbcfff8eafa.png)

**Comment by Fchallier** [comment]
Bon alors c'est un peu délicat... Je viens de regarder et il y a effectivement un grand nombre de doublon...

Sur les fiches des auteurs tu ne renseigne rien de plus que ce qui est importé de Mistral ? 

Je vais voir pour supprimer l'ensemble des auteur et les réimporter....

**Comment by Rouergue** [comment]
Ah non, je ne touche plus à rien maintenant, depuis que tu m'as dit de ne plus le faire !

**Comment by Fchallier** [comment]
Ok, je vais faire un backup de votre BDD et je réalise après l'opération.

**Comment by Rouergue** [comment]
Est-ce que je peux rentrer des choses dans l'agenda ou vaut-il mieux attendre que tu aies fini ?

**Comment by Fchallier** [comment]
Oui oui pas de soucis,

**Comment by Fchallier** [comment]
RollBack de l'ensemble des contributeurs. 

Suppression des doublons. 

Migration des contributeurs. 

Migration de la relation Article -> Contributeur. 

Indexation des nouveaux éléments dans le système de recherche.

Test d'une nouvelle migration des contributeur : ok pas de doublons

Ajout des contributeur dans tes dernières actualités. 

RAS

Ticket liés : #427 #426 #424 #423 #421 #422

**Comment by Fchallier** [comment]
Je penses qu'on est bon au niveau des auteurs. ;)
