### ISSUE TITLE
Fichiers envoyés dans cyberduck non pris en compte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#430]
J'ai envoyé des photos auteurs sur le site la semaine dernière mais elles n'apparaissent toujours pas, 5 jours après !

![Capture d’écran 2021-04-12 à 11 53 32](https://user-images.githubusercontent.com/10072454/114376373-dca9c000-9b85-11eb-8e6e-9a8cd2eb4ead.png)

![Capture d’écran 2021-04-12 à 11 56 58](https://user-images.githubusercontent.com/10072454/114376730-33af9500-9b86-11eb-914e-e89108f4f52b.png)

(et j'ai vidé tous les caches). Que se passe-t-il ? Honnêtement, ça fonctionnait mieux quand je pouvais mettre moi-même manuellement les photos sur le site 😬 !

**Comment by Rouergue** [comment]
Toujours rien ce matin... 
Ci-dessous les deux fichiers envoyés le 08/04 sur le serveur et qui ne remontent pas sur le site. 
Peux-tu les mettre manuellement, stp ? Et voir pourquoi ça ne fonctionne pas quand je dépose les fichiers sur le serveur (sans les uploader sur le site en amont) ? Car j'en ai d'autres à venir...
Merci beaucoup !

![27063](https://user-images.githubusercontent.com/10072454/114517852-04a92a00-9c3f-11eb-96bf-88a704870f9b.jpg)

![78355](https://user-images.githubusercontent.com/10072454/114517878-08d54780-9c3f-11eb-9c7b-07afd59ad4ff.jpg)

**Comment by Rouergue** [comment]
Et voici un nouveau portrait auteur à mettre sur le site, stp :

![26963](https://user-images.githubusercontent.com/10072454/114521514-c7df3200-9c42-11eb-81e6-1ca977bd10a8.jpg)

Merci !

**Comment by Fchallier** [comment]
Bonjour Mathilde,  

J'ai désactivé les mises à jour automatique le temps de trouver une solution pour ne pas surcharger notre serveur. C'est pour cela que les données ne sont pas remontées. 

Je viens de lancer une mise à jour et ça semble ok. Auteurs à jour et sans doublon.

**Comment by Rouergue** [comment]
Ok, merci. Par contre, est-ce normal que, pour Damien Ribeiro, l'ancienne photo s'affiche au lieu de la nouvelle (en n&b) ?

![Capture d’écran 2021-04-13 à 11 04 58](https://user-images.githubusercontent.com/10072454/114527288-1a6f1d00-9c48-11eb-8e49-8bc429fb7d48.png)

![26963](https://user-images.githubusercontent.com/10072454/114527297-1d6a0d80-9c48-11eb-8f81-dbb34b6cf56f.jpg)

**Comment by Fchallier** [comment]
un petit flush des images et ça semble être bon.

**Comment by Rouergue** [comment]
cool, merci beaucoup !
