### ISSUE TITLE
Livres qui ne remontent pas sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#432]
exemple, LA ROUTE DE NESS (office du 05/05) et dont le prix est bien validé dans mistral

![Capture d’écran 2021-04-28 à 09 49 06](https://user-images.githubusercontent.com/10072454/116366898-0fe78280-a807-11eb-92bb-653ae505cc57.png)

**Comment by Rouergue** [comment]
idem pour tous les titres de mai 2021 en jeunesse

**Comment by Rouergue** [comment]
Help ! C'est vraiment très handicapant ces livres qui ne remontent pas... Je dois faire des liens vers des bandeaux actu, événements et autres et les livres seront en librairie la semaine prochaine ! Que se passe-t-il ?

**Comment by Fchallier** [comment]
Hier j'ai lancer la mise à jour, mais les titres ne remontent pas... Je regarde au niveau de la requête SQl.

**Comment by Fchallier** [comment]
Je viens de faire plusieurs tests,et l’élément qui bloque est le prix.  

Peux-vérifier que dans Olea et mistral que le prix est bien renseigné comme pour le titre 'Les bougnats de l'Aubrac' qui lui remonte bien  ? 

J'ai apparemment pas accès à vos titres.

**Comment by Rouergue** [comment]
Je ne comprends pas parce que le prix déf est bien validé sur mistral et olea. Cf. exemple ci-joint pour LA ROUTE DE NESS (9782812620911).

![Capture d’écran 2021-04-29 à 14 45 15](https://user-images.githubusercontent.com/10072454/116552900-d9d6fb00-a8f9-11eb-8991-ece3fd23f100.png)

![Capture d’écran 2021-04-29 à 14 46 05](https://user-images.githubusercontent.com/10072454/116552903-db082800-a8f9-11eb-8e98-6a93a0afc543.png)

Est-ce que ce ne serait pas plutôt lié au tirage qui n'est pas toujours validé ?

**Comment by Fchallier** [comment]
Il me semble que les deux sont liés. Et la requête utilise bien la table PriceAndTirage pour avoir le prix réel validé. 

Penses-tu qu'il soit possible de valider le tirage  et que je lance une nouvelle fois la mis à à jour ?  Car pour "Les bougnats de l'Aubrac" le tirage est bien validé non ? 

Si ça ne fonctionne toujours pas, je ferai par de cela à Charles.

**Comment by Rouergue** [comment]
Ce qui est bizarre, c'est que pour LA ROUTE DE NESS, le tirage n'est pas validé dans mistral mais il l'est bien dans olea.

![Capture d’écran 2021-04-29 à 15 17 24](https://user-images.githubusercontent.com/10072454/116558323-97b0b800-a8ff-11eb-8cdd-bb88690e649c.png)

Et le prix déf et tirage déf sont bien validés dans mistral ET olea pour MESSAGÈRE DE L'OMBRE (poche) et pourtant il ne remonte pas sur le site (mev le 05/05)

![Capture d’écran 2021-04-29 à 15 17 00](https://user-images.githubusercontent.com/10072454/116558419-b4e58680-a8ff-11eb-9618-73ade0b104f6.png)

**Comment by Rouergue** [comment]
Quant aux BOUGNATS, il remonte alors que c'est un titre prévu en juin. Et il manque plein d'autres livres également prévus en juin. Je ne comprends plus riiiiiiien !

**Comment by Fchallier** [comment]
J'envoie un message au support d'Actes Sud, ça me dépasse un peu.

**Comment by Rouergue** [comment]
Ce matin, un seul livre remonte : JOURNAL D'UN CHIEN DE CAMPAGNE, office du 02/06. Alors même que les titres de mai ne sont toujours pas remontés...

![Capture d’écran 2021-05-06 à 09 18 45](https://user-images.githubusercontent.com/10072454/117257642-69296480-ae4c-11eb-9f4e-2fcf6ffaf70c.png)

**Comment by Fchallier** [comment]
Je remarque qu'il manque le titre "Journal d'un chien de campagne" !!! 
Après quelques tests sur la requête SQL il semble que ça bloque au niveau du prix... tu peux vérifier que tout est OK niveau Olea en comparant avec le titre "Les Gagneuses" par exemple ?

**Comment by Fchallier** [comment]
![Screenshot_2021-06-01 Produit](https://user-images.githubusercontent.com/9974750/120333559-1b3f3980-c2f0-11eb-822f-99f1c8b2ce7c.png)

**Comment by Rouergue** [comment]
ok, je demande à Alzira de valider les prix sur Olea et Mistral et je te tiens au courant.

**Comment by Rouergue** [comment]
Alzira a validé le prix dans olea et mistral mais pourtant, le livre ne remonte toujours pas sur le site ! Why ?

![Capture d’écran 2021-06-02 à 17 18 01](https://user-images.githubusercontent.com/10072454/120506750-80fdf500-c3c6-11eb-8521-9c93ff3fa326.png)

![Capture d’écran 2021-06-02 à 17 17 26](https://user-images.githubusercontent.com/10072454/120506752-822f2200-c3c6-11eb-8256-c90f5c548e0c.png)

**Comment by Fchallier** [comment]
Les mises à jours sont lancé tous les jours de 11h à 13h sur la base de donné Mistral de la veille. 

Après que le prix soit validé, le titre semble bien remonter.
