### ISSUE TITLE
Recherche qui ne fonctionne pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#434]
Le livre LE PROCESSUS ne se retrouve pas à partir de la barre de recherche.
Est-ce parce que le champ texte est vide ?

![Capture d’écran 2021-05-06 à 11 15 40](https://user-images.githubusercontent.com/10072454/117273978-ebba2000-ae5c-11eb-8cdf-5abd4909294a.png)

**Comment by Rouergue** [comment]
La recherche ne fonctionne toujours paaaaaaas !

![Capture d’écran 2021-05-19 à 09 18 46](https://user-images.githubusercontent.com/10072454/118771826-4737d500-b883-11eb-9c33-5c621acfd335.png)

**Comment by Fchallier** [comment]
Reconstruction de la recherche tous les jours à 13h
