### ISSUE TITLE
Couv qui ne remonte pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#436]
Alors que j'ai déposé le fichier (ci-joint) sur le serveur il y a 4 jours. Quid ?

![Capture d’écran 2021-05-10 à 11 23 55](https://user-images.githubusercontent.com/10072454/117637624-44056080-b182-11eb-8a68-706acc0c72be.png)

![9782812622052](https://user-images.githubusercontent.com/10072454/117637635-47005100-b182-11eb-922c-40eeef79d643.jpg)

(j'ai vidé tous les caches)

**Comment by Fchallier** [comment]
Je viens de rajouter des scripts pour lancer les mises à jour automatiquement tous les jours à 13h. Il faudra faire attention s'il n'y a pas de perte de données comme la dernière fois.

**Comment by Rouergue** [comment]
La mise à jour a-t-elle bien eu lieu aujourd'hui à 13 h ? Car ce matin, j'ai mis sur le serveur (via cyberduck) une nouvelle photo auteur qui ne remonte toujours pas apparemment...

![14340](https://user-images.githubusercontent.com/10072454/120197308-1c556580-c221-11eb-91fa-64cd733f0fd6.jpg)

=  Claudie GALLEN

**Comment by Rouergue** [comment]
![Capture d’écran 2021-05-31 à 15 02 21](https://user-images.githubusercontent.com/10072454/120197421-37c07080-c221-11eb-8f04-d70b3c5ccc97.png)

**Comment by Rouergue** [comment]
Toujours rien ce matin...

**Comment by Fchallier** [comment]
C'est ok maintenant. 
Mise à jour lancé automatiquement de 11h30 à 13h, pour que les photos d'auteurs remontent il faut déposer les fichiers avec 11h.
