### ISSUE TITLE
Projets annulés qui remontent

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#437]
Faut-il que je les supprime manuellement ?

![Capture d’écran 2021-05-11 à 10 18 04](https://user-images.githubusercontent.com/10072454/117782773-3c0cf580-b242-11eb-9842-6225cab00a34.png)

**Comment by Fchallier** [comment]
Bonjour Mathilde,  

Je vois que tu as supprimé les titres c'est top ! 

Je vais configurer à nouveau la requête, pour voir s'il est possible d'éviter cela. 

Bien à toi,

**Comment by Fchallier** [comment]
Ah c'est la dernière page, ok ! 

Je regarde ça  !

**Comment by Fchallier** [comment]
C'est ok pour la plupart et je rajoute un condition dans le requête pour exclure les statuts numéros 5
