### ISSUE TITLE
URGENT : textes qui ne remontent toujours pas !

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#438]
Alors que la petite phrase et la 4e de couv sont bien renseignées dans olea et mistral. Quid ?

![Capture d’écran 2021-05-17 à 11 12 57](https://user-images.githubusercontent.com/10072454/118464325-04e68a80-b701-11eb-9d38-8dc3169c01b9.png)

![Capture d’écran 2021-05-17 à 11 13 24](https://user-images.githubusercontent.com/10072454/118464347-0adc6b80-b701-11eb-8f3f-f39dd907574f.png)

![Capture d’écran 2021-05-17 à 11 13 28](https://user-images.githubusercontent.com/10072454/118464351-0ca62f00-b701-11eb-8368-d403873400aa.png)

**Comment by Rouergue** [comment]
idem

![Capture d’écran 2021-05-17 à 11 14 53](https://user-images.githubusercontent.com/10072454/118464421-1f206880-b701-11eb-9a6d-9c6cc51b1968.png)

**Comment by Rouergue** [comment]
Les textes sont apparemment remontés ce matin, cool ! 
Par contre, pour l'exemple ci-dessous, l'auteur n'apparaît toujours pas...

![Capture d’écran 2021-05-18 à 09 01 03](https://user-images.githubusercontent.com/10072454/118606401-a6c8ae80-b7b7-11eb-863e-188188fcb544.png)

**Comment by Rouergue** [comment]
Certains textes (pour les albums, notamment) ne remontent toujours pas, alors que la 4e est bien renseignée dans Olea et mistral. Exemple pour PREMIER BONJOUR (et j'ai vidé les caches).

![Capture d’écran 2021-05-20 à 09 41 38](https://user-images.githubusercontent.com/10072454/118939210-b975eb80-b94f-11eb-807e-e0b42898c0aa.png)

![Capture d’écran 2021-05-20 à 09 44 00](https://user-images.githubusercontent.com/10072454/118939402-ecb87a80-b94f-11eb-990d-98a5bba36c4f.png)

**Comment by Fchallier** [comment]
Bonjour Mathilde, 

Un message pour te confirmer que j'ai bien vue l’ensemble de tes tickets. 

Concernant les textes de quatrième de couverture il y avait un souci au niveau d'Olea -> Mistral. 
Hier, Frédéric a bien corrigé le souci et je suis en train de lancer une mise à jour sur votre site. 

Pour les autres tickets, j'ai des différences de données entre la base réduite Mistral qu'on utilise pour votre site et la bas réduite qu'on utilise pour Actes Sud et Payot & Rivages. 

Je vais reprendre l'ensemble des requêtes SQl de votre votre module pour le connecter à notre base. Cela va prendre un peu de temps, mais j'espère qu'a partir de demain ça sera réglé. 

Je suis actuellement à paris, je te tiens au courant quand c'est corrigé. 

Bien à toi,

**Comment by Fchallier** [comment]
Les textes remontent maintenant correctement, mais il y a toujours un petit bug au niveau de la quatrième de couverture. 
Une balise HTML vide est renseignée à la place du point. 

Je viens d'ouvrir à nouveau un ticket.
