### ISSUE TITLE
Visuel changé sur mistral et non mis à jour sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#440]
Suite à un pb de coupe dans Sirocco, Myriam Bos a modifié le visuel dans Mistral (couv avec un bord tournant partout). Or c'est toujours la mauvaise couv qui apparaît sur notre site. Les mises à jour de Mistral n'aplatissent-elles pas les fichiers précédents sur notre site ? Ci-joint, pour info, le détail des échanges avec Myriam à ce sujet.

[pb sirocco.pdf](https://github.com/EditionsDuRouergue/lerouergue/files/6506788/pb.sirocco.pdf)

![Capture d’écran 2021-05-19 à 09 32 43](https://user-images.githubusercontent.com/10072454/118774268-ef4e9d80-b885-11eb-9524-c14e484d63c1.png)

![Capture d’écran 2021-05-19 à 09 32 07](https://user-images.githubusercontent.com/10072454/118774274-f1186100-b885-11eb-9612-816c26ee1d18.png)

**Comment by Fchallier** [comment]
C'est ok non  ?  la bonne couverture est bien remonté  ?

**Comment by Rouergue** [comment]
Oui c'est bon, merci !
