### ISSUE TITLE
La recherche ne trouve pas les auteurs

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#443]
Exemple : 

![Capture d’écran 2021-06-07 à 10 36 03](https://user-images.githubusercontent.com/10072454/120986085-83709e00-c77c-11eb-9e41-cfdbf82c660f.png)

![Capture d’écran 2021-06-07 à 10 36 17](https://user-images.githubusercontent.com/10072454/120986097-866b8e80-c77c-11eb-82c4-bc84145634cd.png)

Faut-il respecter la casse (majuscules / minuscules) ?
(cela n'a pas l'air de mieux fonctionner...)

**Comment by Fchallier** [comment]
Je lance une reconstruction de la recherche et je viens d'appliquer une réindexation du contenu du site toutes les trois heures.

**Comment by Rouergue** [comment]
ok, merci !
