### ISSUE TITLE
Titres d'août toujours notés en juillet

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#445]
![Capture d’écran 2021-06-22 à 09 34 14](https://user-images.githubusercontent.com/10072454/122883059-1abd2000-d33d-11eb-9ddf-96155caa4786.png)

![Capture d’écran 2021-06-22 à 09 35 06](https://user-images.githubusercontent.com/10072454/122883103-24df1e80-d33d-11eb-9869-b1d729de7ef0.png)

**Comment by Rouergue** [comment]
Idem pour le titre jeunesse qui vient de remonter (et qui devrait être sur août)

![Capture d’écran 2021-06-24 à 09 56 16](https://user-images.githubusercontent.com/10072454/123224988-93091a00-d4d2-11eb-9f63-90a9a11dc782.png)

**Comment by Fchallier** [comment]
Je viens d'appliquer un correctif dans le code de migration ça semble bien fonctionner.

**Comment by Rouergue** [comment]
Super, merci !
