### ISSUE TITLE
URGENT : problème d'affichage après rajout d'une vidéo

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#446]
La vidéo rentre dans la partie biblio...

![Capture d’écran 2021-07-05 à 10 16 44](https://user-images.githubusercontent.com/10072454/124439813-2b788780-dd7a-11eb-8d05-a7b9dca69a1b.png)

**Comment by Fchallier** [comment]
Il y avait un petit souci dans le code HTML qui tu as copié. 

Ton code : 
`<p><iframe src="https://e.issuu.com/embed.html?backgroundColor=%23f2f2f2&amp;d=revenir_fils_extrait&amp;doAutoflipPages=true&amp;hideIssuuLogo=true&amp;u=rouergue" style="position:absolute;border:none;width:100%;height:100%;left:0;right:0;top:0;bottom:0;"></iframe><br />
<br /><p>`

Correction : 

`<div style="position:relative;padding-top:max(60%,326px);height:0;width:100%"><iframe src="https://e.issuu.com/embed.html?backgroundColor=%23f2f2f2&amp;d=revenir_fils_extrait&amp;doAutoflipPages=true&amp;hideIssuuLogo=true&amp;u=rouergue" style="position:absolute;border:none;width:100%;height:100%;left:0;right:0;top:0;bottom:0;"></iframe></div>`

Je viens de le corriger.

**Comment by Rouergue** [comment]
Ok, merci.
Il y a quand même des problèmes d'affichage au niveau du back office, avec des blocs qui se superposent et, surtout, de grandes plages vides entre deux lignes de texte ou image. Ce n'est pas très pratique à l'usage...

![Capture d’écran 2021-07-05 à 10 52 42](https://user-images.githubusercontent.com/10072454/124444795-41d51200-dd7f-11eb-800d-10f0b4540191.png)

**Comment by Fchallier** [comment]
Malheureusement je peux pas faire grand-chose à ce niveau. 

Par contre quand tu as plusieurs élément il serait préférable de les séparer dans deux champs différents. Le champ "Embed vidéos - liseuses" est un champ multiple. 

Je te laisse regarder comment j'ai fait sur la fiche du livre : []( https://www.lerouergue.com/node/29685/edit)
