### ISSUE TITLE
Visuels non pris en compte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#447]
Est-ce normal que les visuels que j'ai mis sur le serveur via cyberduck hier ne s'affichent pas encore sur le site ? Je croyais que la mise à jour se faisait tous les soirs ?

![Capture d’écran 2021-07-06 à 09 37 18](https://user-images.githubusercontent.com/10072454/124561212-ecac0580-de3d-11eb-9e3e-badf02b6cd99.png)

**Comment by Fchallier** [comment]
Oui c'est normal, la mise à jour est programmé tous les jours de 11h  à 13h  ;)

**Comment by Rouergue** [comment]
Ah ok, désolée, je me suis emmêlée les pinceaux !
