### ISSUE TITLE
Signe & non pris en compte

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#448]
Correctement saisi dans Olea, le signe "&" n'apparaît pas correctement sur le site et fait apparaître les balises html :

![Capture d’écran 2021-08-03 à 12 45 22](https://user-images.githubusercontent.com/10072454/128003231-cdbe8b05-5eb2-418f-ba8c-4f048c980478.png)

![Capture d’écran 2021-08-03 à 12 45 29](https://user-images.githubusercontent.com/10072454/128003243-e524942a-4ffd-4c2b-9bc5-8943b073d718.png)

**Comment by Rouergue** [comment]
Et sur la fiche livre du site, le nom de l'auteur (Terre & Humanisme) n'apparaît pas...

![Capture d’écran 2021-08-16 à 10 40 49](https://user-images.githubusercontent.com/10072454/129536052-27ca26d4-237d-49d5-a687-936fed3873a3.png)

**Comment by Rouergue** [comment]
De mon côté, il n'y a plus de hiéroglyphes mais "Et" (au lieu de "&")

![Capture d’écran 2021-10-13 à 15 33 31](https://user-images.githubusercontent.com/10072454/137142991-4447524f-b014-4d02-8fcf-95b3665c9f5c.png)

**Comment by Fchallier** [comment]
Il me semble que j'avais déjà réalisé un mail au support d'Actes Sud pour corriger cela, mais le problème semble être revenu... 
Il faudrait faire à nouveau un mail au support en leurs indiquant que les données d'Olea ne remontent pas correctement vers Mistral, notamment les certains caractères compris dans les quatrièmes de couverture. 

Exemple avec le titre que tu m'as indiqué.

**Comment by Rouergue** [comment]
Je viens de renvoyer un ticket au support AS. Affaire à suivre...

**Comment by Rouergue** [comment]
Bonjour Mathilde,

le problème a été identifié et corrigé, à la fois au niveau de la synchronisation entre Olea et Mistral (et par extension nos sites vitrines) ainsi qu'au niveau de l'envoi des flux de référencement vers les plateformes externe.

Pour test, nous avons mis à jour l'article cité en exemple afin qu'il soit renvoyé vers Mistral et vers les plateformes de référencement. Le '&' dans la petite phrase est désormais bien transcrit correctement, y compris sur le site du Rouergue.

Les quelques autres articles concernés par le même problème seront renvoyés dans les flux de synchronisations / référencement de ce soir.

Bien à toi,

Charles
