### ISSUE TITLE
URGENT : résumé qui a disparu !!!

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#450]
Help ! En voulant remonter la ligne de code correspondant à l'extrait à feuilleter, cela a supprimé tout ce qui était au-dessus : vidéo, résumé du livre, etc. 

![Capture d’écran 2021-09-13 à 14 22 22](https://user-images.githubusercontent.com/10072454/133082689-f0b5b12c-216d-454d-8c20-229256ca5dcf.png)

![Capture d’écran 2021-09-13 à 14 22 47](https://user-images.githubusercontent.com/10072454/133082705-39238683-c9e6-452f-98d3-a26458870032.png)

**Comment by Fchallier** [comment]
Salut Mathilde,  

Il y avait un petit soucis au niveau du copié/collé de l'extrait... J'ai repris le code de "Marchands de mort subite" et j'ai changé l'url pour afficher la bonne liseuse.

Il faut bien prendre l'ensemble du code proposé par Issuu. 

Bien à toi,

**Comment by Rouergue** [comment]
Merci pour ta rapidité !
Il faut que je fasse gaffe car je crois que ce n'est pas la première fois que ça m'arrive ! Je n'ai pas de problème au moment de l'importation du code issuu de l'extrait, c'est plus tard, au moment de l'ajout de la vidéo et en voulant supprimer les sauts de ligne intempestifs au niveau du back office, que je dois supprimer des lignes importantes sans le vouloir... Promis, je ferai attention la prochaine fois !
