### ISSUE TITLE
Titres épuisés du catalogue qui remontent sans visuels

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#452]
C'est le cas pour les premiers titres publiés dans les années 1990. Cf. en fin de liste sur le catalogue du site.

![Capture d’écran 2021-09-21 à 17 19 23](https://user-images.githubusercontent.com/10072454/134301890-1e9f6a69-7985-4d44-99dd-cda4880ec070.png)

**Comment by Fchallier** [comment]
Revoir de la requête SQL de la migration des articles : 

- Vérifier avec l'ancienne requête  : Statut de l'article ( épuisé, interdit à la vente, etc... ) 
-

**Comment by Fchallier** [comment]
J'avais également rajouté un condition au niveau de l'import. 

Nous importons l'ensemble des titres sauf ceux qui sont interdits à la vente et les projets abandonnée.
