### ISSUE TITLE
Photos auteurs non communicables qui remontent

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#453]
Y compris pour des titres très anciens dont le stock est à 0.
![Capture d’écran 2021-09-23 à 14 58 19](https://user-images.githubusercontent.com/10072454/134875164-1efbe5ec-0981-40fb-925e-71487d0ba31d.png)
![Capture d’écran 2021-09-23 à 14 58 24](https://user-images.githubusercontent.com/10072454/134875192-bd1083b4-5e9f-4d0a-8949-c9ded46f8293.png)
![Capture d’écran 2021-09-23 à 14 59 08](https://user-images.githubusercontent.com/10072454/134875195-951cc52e-ad8f-4e4d-9748-435ec78ec177.png)

**Comment by Fchallier** [comment]
Le point suivant est corrigé non  ?

**Comment by Rouergue** [comment]
Oui, tout à fait, merci !
Je prendrai un temps cet aprèm pour faire le tour (et le ménage) dans les tickets restés en suspens et/ou obsolètes !
