### ISSUE TITLE
JARDIN JUNGLE n'apparaît pas dans le catalogue

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#456]
JARDIN JUNGLE > Rouergue Litté / Écologie / sous-dépt. 2 = vide (à créer dans drupal)

![Capture d’écran 2021-10-13 à 15 38 39](https://user-images.githubusercontent.com/10072454/137143943-ed52f709-c1b8-4745-8bae-7d1a8c6a6330.png)

**Comment by Fchallier** [comment]
Alors le nouveau Mapping serait  	 Rouergue Littérature - 493 | Ecologie - 1149  (Mistral) -> Nature & Jardin > Écologie (Drupal)
