### ISSUE TITLE
Mise en place de la rubrique Vidéos sur le site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#458]
1. Ajout d'un bouton supplémentaire dans les menus du haut, entre "agenda" et "fabrique"

![Unknown](https://user-images.githubusercontent.com/10072454/138249819-77e019ef-977f-4ac9-aac4-b998f8b8e3e6.png)

2. Le lien renverrait ensuite sur une page semblable à celle qui récapitule les posts de la Fabrique (avec les vidéos par ordre chronologique inversé, du plus récent au plus ancien).

![Unknown-1](https://user-images.githubusercontent.com/10072454/138249978-a0b6a23f-f3bf-4c94-8732-61695275bcc2.png)

3. Sur la page accueil du site, une « bande-vidéos » avec les dernières vidéos en date (ou plutôt, si possible, une sélection ciblée), sur le même principe que la « bande-agenda » (avec un bouton en bas à droite "voir toutes les vidéos").

![Unknown-2](https://user-images.githubusercontent.com/10072454/138250225-4fc7c2c8-8ace-484c-a9cd-02bf50af6786.png)

Je suis à ta dispo si tu as besoin de précisions !

**Comment by Fchallier** [comment]
Bonjour Mathilde,  

Comme indiqué la semaine dernière j'ai commencé à avancé sur ce sujet. 

Pour le moment  : 

- [ ] Création d'un nouveau type de contenu 'Vidéos' avec ces champs
- [ ] Création des différent displays
- [ ] Création de la vue https://www.lerouergue.com/videos

Il reste à faire  : 

- [ ] Création de la vue pour la page d'accueil
- [ ] Création de la vue pour gérer l'ordre de l'affichage
- [ ] Ajout du lien vidéos dans le menu Principal

**Comment by Rouergue** [comment]
Super 👍

**Comment by Fchallier** [comment]
Petite question, tu souhaites que le bloc apparaisse à quel niveau sur la page d'accueil  ? En dessous d'Agenda ?

**Comment by Rouergue** [comment]
Oui, entre l'Agenda et la Fabrique, stp ? Est-ce que c'est possible de mettre en place une sélection ciblée (sur le même principe que la « bande-agenda » avec un bouton en bas à droite "voir toutes les vidéos") ou bien seules les dernières vidéos mises en ligne apparaîtront sur ce bandeau ?

**Comment by Fchallier** [comment]
Bonjour Mathilde,  

Désolé je galère à trouver le moyen de positionner le bloc au bon endroit.  Le thème du site est construit différemment que ce que j'ai l'habitude de faire... 

Pour la sélection ciblée, la vue est normalement déjà en place, tu peux retrouver cela via  le menu admin (ROUERGUE ADMIN -> Tri bloc Vidéo) :  https://www.lerouergue.com/admin/tri-videos

**Comment by Rouergue** [comment]
Bonjour François,
Après réflexion, je me disais qu'on pouvait peut-être se passer d'avoir une bande "vidéos" sur la page accueil dans l'immédiat. Je pense d'ailleurs que ce n'est pas forcément une bonne idée si ça oblige à beaucoup scroller pour atteindre le bas de la page. J'ai peur que plus personne n'accède à la rubrique "fabrique". Bref, peut-être que, dans un premier temps tu peux juste mettre en place le nom de la rubrique en haut avec un lien qui renvoie vers la page que tu as déjà réalisée. Qu'en penses-tu ?

![138249819-77e019ef-977f-4ac9-aac4-b998f8b8e3e6](https://user-images.githubusercontent.com/10072454/162234063-cacb23bb-6711-4810-89c1-e9af1d8b562e.png)

**Comment by Fchallier** [comment]
Ah oui pour information, le contenu vidéo se compose des champs suivants : 

- D'un titre
- D'une vignette avec les mêmes dimensions que la fabrique
- Un champs texte "Code Embed vidéo" ou ici tu dois cliquer sur "Source" et copier coller ton code embed de Viméo, Youtube ou autre

**Comment by Rouergue** [comment]
Oui, je peux maintenant ajouter des vidéos. Par contre, la page récap' n'arrive pas à se rafraîchir et je ne peux donc pas changer l'ordre des vidéos que je viens d'importer.

![Capture d’écran 2022-04-07 à 18 48 32](https://user-images.githubusercontent.com/10072454/162255507-748ae24b-4a70-4ada-a116-6dd814b036d5.png)

**Comment by Rouergue** [comment]
Et, du coup, je ne peux pas donc vérifier la mise en ligne que j'ai faite puisque les nouvelles vidéos ne s'affichent pas.

![Capture d’écran 2022-04-07 à 18 45 15](https://user-images.githubusercontent.com/10072454/162255656-c6093c36-9f12-441e-a551-1e5fb6278242.png)

Je suis en congés à partir de ce soir, de retour le lundi 25 avril. En attendant, si tu vois que ça cafouille et que ce que j'ai mis en ligne ne fonctionne pas où s'affiche mal, est-ce que tu peux suspendre cette rubrique jusqu'à mon retour, stp ? Je regarderai ça plus en détail début mai.

En tous cas, c'est bien cool d'avoir cette rubrique supplémentaire, merci !
Je me demandais juste si c'était possible d'ajouter un champ avec (en petit) une ou plusieurs vignettes des livres auxquelle la vidéo se rattache à chaque fois ? Est-ce que c'est long et compliqué à mettre en place ?

**Comment by Rouergue** [comment]
Je viens de voir que les nouvelles vignettes se sont enfin affichées dans le récap'. Mais par contre, je ne vois pas le bouton pour changer l'ordre d'apparition...

**Comment by Fchallier** [comment]
Il devait y avoir un souci hier avec le cache du site...je vais vérifier cela plus en détail quand même. 

Pour réorganiser les vignettes tu as normalement accès dans la partie admin à la page suivante  : https://www.lerouergue.com/admin/tri-videos

Sinon c'est dans ton menu admin
![capture_menu_admin_rouergue](https://user-images.githubusercontent.com/9974750/162388718-a46cbd5e-f66d-4794-889c-bc34b769d55e.jpg)

Et sans soucis pour rajouter les couverture qui sont associées à la vidéo. Je regarde pour mettre cela en place avant ton retour. 

Bien à toi,

**Comment by Rouergue** [comment]
Par ailleurs, quel est la taille exacte du bloc pour les vidéos que je dois importer ? Serait-il possible qu'elles se mettent automatiquement à la même largeur par exemple, pour qu'il y ait une homogénéisation entre toutes ? 

![Capture d’écran 2022-04-29 à 18 05 43](https://user-images.githubusercontent.com/10072454/165983933-ce8ab942-e21f-4b7b-8539-6e5dbef830e4.png)

![Capture d’écran 2022-04-29 à 18 05 34](https://user-images.githubusercontent.com/10072454/165983940-abfd1bef-e21a-4066-abc1-d94a833ddca8.png)

**Comment by Rouergue** [comment]
Autre question (j'en profite) : y aurait-il un moyen de récupérer automatiquement ou facilement la vignette vidéo (sélection proposée comme dans youtube ou vimeo) ?

**Comment by Rouergue** [comment]
Enfin, serait-t-il envisageable à terme (pour un développement futur !) de prévoir une hiérarchisation ou une possibilité de filtre / classement des vidéos (comme des posts de la Fabrique) par collection ou par date ? 
Je te propose qu'on se fasse une visio la semaine prochaine (mercredi 4 mai ?) pour faire un petit point sur toutes ces questions... D'ici-là, bon week-end !

**Comment by Fchallier** [comment]
- [ ] Les nouvelles vidéos ajoutées seront automatiquement misent en première position. Il sera possible ensuite de les repositionner
- [ ]  Modification de l'affichage dans la page de tri afin que cela soit un peu plus facile à ordonner
- [ ] Momification de la page Vidéos  afin de respecter l'ordre

**Comment by Rouergue** [comment]
Ok, merci. Mais lorsque je viens de mettre une vidéo en ligne dans cette rubrique, celle-ci n'apparaît pas immédiatement sur la page récap' et quand je veux vider le cache, un message d'erreur s'affiche.

![Capture d’écran 2022-07-26 à 17 49 17](https://user-images.githubusercontent.com/10072454/181052087-00afbd41-6369-4c71-81a6-d00949255d53.png)

**Comment by Rouergue** [comment]
Pour un classement par catalogue, pourrait-on imaginer quelque chose comme ce qui est fait sur Vimeo ?

![Capture d’écran 2022-07-27 à 16 55 15](https://user-images.githubusercontent.com/10072454/181279880-c02c8e88-64eb-41b6-840e-8c3945088f80.png)
![Capture d’écran 2022-07-27 à 16 55 20](https://user-images.githubusercontent.com/10072454/181279893-68bc59dd-7acc-4c84-b168-7f0ce69b6b46.png)

**Comment by Rouergue** [comment]
Dans l'idéal, voici les champs dont j'aurais besoin pour chaque vidéo :

- titre
- auteur
- type (liste déroulante avec possibilité de la compléter > interview / reportage / teaser / tuto / feuilletage animé / recette / galerie / présentation / extrait / bande-annonce / entretien / rétrospective / podcast / lecture / émission / replay / portrait / boîte à questions)
- date
- catalogue (comme sur le découpage VIMEO ci-dessus, à savoir : Littérature La brune / Polars Rouergue Noir / Beaux-livres et témoignages / Romans jeunesse / Albums jeunesse)

Tu penses que ce serait possible sans que ce soit trop long à mettre en place ?
Ce qui serait cool, c'est de pouvoir ensuite faire des filtres / classements par date, catalogue, type, auteur... (mais peut-être que j'en demande trop, là 😬 !)

**Comment by Fchallier** [comment]
- [ ] Ajout Auteur 
- [ ] Ajout taxonomie TYPE
- [ ] Ajout taxonomie Catalogue
- [ ] Ajout un système de filtre (mixit up)

**Comment by Fchallier** [comment]
L'ensemble des nouveaux champs sont ajoutés pour les vidéos. 

Il restera simplement à les afficher sur les page Vidéos et mettre en place le système de filtre.

**Comment by Rouergue** [comment]
Ok, merci. Est-il possible de mettre un 2e champ "auteur" ? Certains livres illustrés ont plusieurs auteurs (c'est le cas pour _La biodynamie_ qui a deux auteurs) et les albums ont en général un auteur et un illustrateur.

![Capture d’écran 2022-07-28 à 14 10 28](https://user-images.githubusercontent.com/10072454/181502042-afb0bab9-5ea8-4329-a40d-76c97ef7e5d8.png)

**Comment by Rouergue** [comment]
Il manque le "n" dans la liste déroulante à "présentation".
![Capture d’écran 2022-07-28 à 14 48 13](https://user-images.githubusercontent.com/10072454/181508909-892fe014-ca22-4fdd-bec2-2fefd1eb900b.png)

**Comment by Rouergue** [comment]
Et pourrais-tu rajouter "spot" dans la liste déroulante, stp ?

**Comment by Rouergue** [comment]
Certaines vidéos que je mets à jour (notamment avec changement de vignette) ne s'affichent plus correctement ensuite sur la page récap', y compris sur chrome.

![Capture d’écran 2022-07-28 à 15 05 16](https://user-images.githubusercontent.com/10072454/181512284-5ec49578-fb41-47d5-9715-8ad35b9b709b.png)

Est-ce parce qu'il faut un temps de "digestion" pour la prise en charge des nouveaux visuels ? Lorsque je vide le cache des images (dans firefox), ça ne change rien...

**Comment by Rouergue** [comment]
Je vois aussi que, sur chrome, le type, catalogue et auteur s'affichent déjà (et pas sur firefox). Est-ce possible de ne garder que le titre et éventuellement le type (reportage, teaser, etc.) en-dessous en attendant de revoir la mise en forme à la rentrée ?

**Comment by Rouergue** [comment]
Changement à l'instant : le type, catalogue et auteur s'affichent également sur firefox maintenant !

**Comment by Fchallier** [comment]
- [ ] Ajout de "spot"
- [ ] Ajout du "n"
- [ ] Ajout d'un champs multiple pour les auteurs

**Comment by Fchallier** [comment]
Concernant l'affichage des catégories et des auteurs, il est nécessaire de mettre en place quelques règle en CSS je finalise cela d'ici demain.

**Comment by Rouergue** [comment]
Ok, super ! Merci pour tout.
Au niveau du nom de l'auteur, sera-t-il possible de l'afficher dans l'ordre Prénom + Nom ?

![Capture d’écran 2022-07-28 à 15 45 25](https://user-images.githubusercontent.com/10072454/181520803-a9ec7c4d-0363-45cd-8b07-e07e9de17f08.png)

**Comment by Rouergue** [comment]
Dans l'interface, serait-il possible de rajouter un 2e champ "Code Embed Vidéo" pour ajouter des liens vers d'autres vidéos sur le même titre ou le même auteur ? Quand j'essaie d'ajouter ces mentions (avec liens) en-dessous du code des vidéos importées, ça cafouille ! J'essaie d'ajouter des espaces dans le code (<p>&nbsp;</p>) mais soit le saut de ligne est trop petit, soit il est trop grand, soit ça fait sauter le lien. Bref, je galère pas mal (il faut dire que je ne suis pas très douée en langage html).

![Capture d’écran 2022-07-28 à 16 01 15](https://user-images.githubusercontent.com/10072454/181524924-8dc6858e-b6b4-45f9-8062-862a5778e42b.png)

![Capture d’écran 2022-07-28 à 16 04 11](https://user-images.githubusercontent.com/10072454/181525016-4cfe41e7-86ba-4db5-81e0-d43bfd1b0ba7.png)

![Capture d’écran 2022-07-28 à 16 04 16](https://user-images.githubusercontent.com/10072454/181525028-24eac6bb-6eb4-4b78-a541-067547ea262f.png)

**Comment by Rouergue** [comment]
Pour le bouton du bas, je le mettrais en un peu plus petit si possible, en reprenant le orange du site.

![Capture d’écran 2022-07-28 à 16 16 33](https://user-images.githubusercontent.com/10072454/181532301-13aa07d8-ce62-4c9c-b12b-d3838d701de5.png)

Au niveau du texte, est-ce qu'on pourrait mettre plutôt "Découvrez l'ensemble de nos vidéos en cliquant ici" sans forcément reprendre le logo de Vimeo ? Ou bien tu penses au contraire que c'est bien de citer Vimeo ?

![Capture d’écran 2022-07-28 à 16 15 51](https://user-images.githubusercontent.com/10072454/181534918-1bf0832a-7019-4d0f-bbc9-a91f9a98c820.png)

Et, je pense que je vais avoir quand même pas mal de vidéos par catalogue (sans aller jusqu'à 250 !) car certaines vidéos pour des livres du fonds sont importantes pour l'image de la maison. Du coup, je me demande s'il ne faudrait pas mettre (en plus ou à la place du bouton tout en bas) une mention simple en haut à droite du genre "voir toutes nos vidéos" et renvoyant également vers la page récap' vimeo. Ton avis ?

![Capture d’écran 2022-07-28 à 16 21 07](https://user-images.githubusercontent.com/10072454/181539480-4fe1fd04-0944-4a7b-93dc-2a6be4efd652.png)

**Comment by Rouergue** [comment]
Juste pour info :

![Capture d’écran 2022-07-28 à 18 00 17](https://user-images.githubusercontent.com/10072454/181584463-6cc4471e-813b-4bd0-b3b0-a988a107d615.png)

**Comment by Fchallier** [comment]
- [ ] Tri des Actualités -> Tri des Vidéos 
- [ ] Ajout d'un lien "voir toutes nos vidéos" en haut à droite
- [ ] Mise à jour de votre éditeur de Texte, mais cela ne corrige pas le problème d'espace. Car le code d'intégration de Vimeo contient des balises avec des grosses marges....

**Comment by Fchallier** [comment]
- [ ] Modification du champs Embed en champs multiple, afin de pouvoir ajouter du texte en dessous de vidéos

**Comment by Fchallier** [comment]
- [ ] Mise à jour effectué pour les nom des auteurs

**Comment by Rouergue** [comment]
Nickel, merci pour tout ça !
J'ai remarqué que la police de l'interface utilisateur avait changé de police. Est-ce dû à la mise à jour de l'éditeur de Texte que tu as faite ? Est-ce possible de revenir à une police plus simple comme avant avec moins d'empattement ? Cela ne change rien à l'affichage final pour l'internaute mais c'est plus confort pour moi que la police soit identique à la version en ligne (tu vas dire que je chipote...).

![Capture d’écran 2022-08-01 à 12 19 51](https://user-images.githubusercontent.com/10072454/182127972-1ea87332-f984-4926-8252-85e468123264.png)

![Capture d’écran 2022-08-01 à 09 55 18](https://user-images.githubusercontent.com/10072454/182128103-bcd3d9e3-bcd6-4e21-8878-a6fdeee028bb.png)

**Comment by Rouergue** [comment]
À propos de : "Modification du champs Embed en champs multiple, afin de pouvoir ajouter du texte en dessous de vidéos"
Le 2e champs Embed n'apparaît que sur le mode "modification" d'une fiche déjà créée mais n'apparaît pas au moment de la création d'une nouvelle fiche.

![Capture d’écran 2022-08-01 à 14 44 12](https://user-images.githubusercontent.com/10072454/182150915-5ee01ca8-ba6e-4a71-a0f7-b0da8baaae28.png)

![Capture d’écran 2022-08-01 à 14 42 49](https://user-images.githubusercontent.com/10072454/182150935-4b7b2ebb-a984-4a43-9b03-af7475ad3b72.png)

**Comment by Fchallier** [comment]
Concernant le problème du second champs embed, normalement tu un bouton en dessous "Ajouter un autre élément" et normalement lors du clic cela ajoute un nouveau champs. 
![Screenshot 2022-09-13 at 11-07-23 Créer Vidéos rouergue](https://user-images.githubusercontent.com/9974750/189882233-f0f338f8-1ac8-4b76-b16b-9a0664514de3.png)

Et pour le design de l'éditeur c'est normalement corrigé ;)
