### ISSUE TITLE
Bouton des livres numériques renvoyant vers la Place des libraires

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#459]
À partir du bouton "disponible aussi en numérique", serait-il possible de renvoyer les internautes vers le site de Place des libraires (comme pour Actes Sud) à la place du renvoi actuel vers Eden ? 

![Capture d’écran 2021-11-24 à 14 44 04](https://user-images.githubusercontent.com/10072454/143249703-fdfcf9cc-9a39-49c3-924c-66721e11fde0.png)

**Comment by Fchallier** [comment]
Pas de soucis, je viens de faire la mise à jour sur le site. 

**(Modification de la vue lien_eden)**
