### ISSUE TITLE
couleurs ternes sur les bandeaux actu

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#460]
C'est étrange, la couleur des bandeaux une fois uploadés devient terne. Et, du coup, l'ensemble des bandeaux actus sont un peu fadasses. Sais-tu d'où ça peut venir ? La différence sur l'exemple ci-dessous n'est pas très flagrante mais c'est parfois plus marqué.

![Capture d’écran 2021-12-01 à 09 10 10](https://user-images.githubusercontent.com/10072454/144197195-261e1339-32ad-4ba6-9eb0-8b3a97d354ab.png)

**Comment by Fchallier** [comment]
Alors personnellement, je ne vois pas trop de différence....Mais cela vient peut-être du calibrage de mon écran.

Par contre, je sais qu'il y a sur votre site un module qui réduit la qualité des images affichés, pour améliorer les performances du site. Je peux le désactiver si tu veux ?

**Comment by Rouergue** [comment]
Est-ce que ça ne risque pas de ramer un peu et de rallonger l'ouverture des pages ? On peut toujours essayer si ce n'est pas trop long à faire pour toi et aviser ensuite !

**Comment by Fchallier** [comment]
J'ai passé la qualité des images à 100% il ne devrait plus y avoir de perte de qualité.

**Comment by Rouergue** [comment]
Ok. Mais j'ai l'impression que ça a fait bouger certaines couleurs de couvs qui, pour le coup, sont devenues ternes. Exemple pour _Vortex_ sur le bandeau des nouveautés.
![Capture d’écran 2022-07-27 à 14 59 53](https://user-images.githubusercontent.com/10072454/181253096-93d5e590-a8d2-49ba-9a25-86bb51e822d7.png)

Ci-dessous la qualité réelle de la couv :
![vortex](https://user-images.githubusercontent.com/10072454/181253342-3c021dd6-c4bb-4fea-85f9-10c8c51a340d.jpg)

**Comment by Fchallier** [comment]
La couv importé sur votre site est la suivante  : https://www.lerouergue.com/sites/default/files/catalog/cover-images/9782812623738.jpg

Je pense que celle que tu as envoyée a été écrasée cette nuit par celle archivé dans Mistral. Il me semble que ce sont les mêmes couleurs...

![Screenshot 2022-07-27 at 15-12-36 Mistral - Actes Sud](https://user-images.githubusercontent.com/9974750/181255602-831a9f4f-4435-429d-bb0c-bb133cfce460.png)
 
Un petit message à prévoir à Rémy TRINQUIER, car c'est également cette couverture qui sera envoyé aux sites marchands !

**Comment by Fchallier** [comment]
Et lui indiquer aussi d'un peu mieux la découper, il me semble voir une marge blanche sur le droite :)

**Comment by Rouergue** [comment]
Ok, on s'en occupe. Je pense que le problème vient du fait que la couv est en pantone et que Sirocco a eu du mal à la digérer ! On va demander au graphiste d'envoyer à Rémy une couv BAT factice en RVB.

**Comment by Rouergue** [comment]
La mise à jour a bien été faite par Rémy sur Mistral mais la bonne couv ne remonte pas plus sur le site, malgré plusieurs mises à jour du serveur.

![Capture d’écran 2022-08-01 à 09 38 49](https://user-images.githubusercontent.com/10072454/182098016-688007af-06b5-4477-a52e-83572e072f2f.png)


![Capture d’écran 2022-08-01 à 09 38 36](https://user-images.githubusercontent.com/10072454/182097993-b91ca1ed-6fa4-4714-b975-b61cae8230a2.png)

**Comment by Rouergue** [comment]
Apparemment, ça vient de se mettre à jour. C'est donc tout bon !
