### ISSUE TITLE
Nom des villes en capitales

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#461]
Sur les fiches auteurs, le nom des villes dans le récap' de l'agenda de l'auteur ne se met pas automatiquement en CAPITALES (alors que c'est ok dans les récap' de l'agenda par mois) quand on les saisit en bas-de-casse dans le formulaire.

![Capture d’écran 2021-12-13 à 10 24 10](https://user-images.githubusercontent.com/10072454/145796983-a323c79c-2c5e-4a6d-98a5-87a02fc25a98.png)

![Capture d’écran 2021-12-13 à 11 35 08](https://user-images.githubusercontent.com/10072454/145797027-bb119af9-f694-4a9f-b01a-3bac81e961ee.png)

**Comment by Fchallier** [comment]
Ajout d'une proprité CSS dans la champ Contenu : Adresse - Localité (c&#039;est-à-dire Ville) de la vue : structure/views/view/events/edit/agenda_author_block
