### ISSUE TITLE
Cadre noir autour des vidéos

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#463]
Un cadre noir est apparu autour de toutes les vidéos. Ce n'est d'autant pas esthétique que, certaines fois, la dimension des vidéos ne correspond pas exactement aux dimensions de l'espace prévu pour celles-ci. Ce n'est pas gênant quand le cadre est transparent mais ça se voit quand le filet noir s'affiche !

![Capture d’écran 2022-02-23 à 14 48 10](https://user-images.githubusercontent.com/10072454/155332159-fe36bc08-c086-4744-8ef7-ccf0fa3ef715.png)

![Capture d’écran 2022-02-23 à 14 51 11](https://user-images.githubusercontent.com/10072454/155332564-bf07bb36-3042-4400-a566-d7c3c54212d3.png)

**Comment by Rouergue** [comment]
Je viens d'intégrer de nouvelles vidéos mais il y a toujours le même problème de cadre noir inesthétique autour...

![Capture d’écran 2022-03-03 à 16 30 12](https://user-images.githubusercontent.com/10072454/156596599-194718c5-05f8-42d2-89ed-fa064efbdc7c.png)

**Comment by Fchallier** [comment]
Je viens d'appliquer une correctif ;)
