### ISSUE TITLE
Problème d'affichage de couverture

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#464]
Uniquement sur la page livre... car la vignette de couv s'affiche bien au niveau du récap' des vignettes dans l'onglet CATALOGUE ou dans la biblio de l'auteur. Quid ?

![Capture d’écran 2022-04-04 à 09 49 45](https://user-images.githubusercontent.com/10072454/161498471-c06bfb82-8fdc-44df-85f3-a17268cea8be.png)

![Capture d’écran 2022-04-04 à 09 49 40](https://user-images.githubusercontent.com/10072454/161498499-115f9e69-4e60-4c12-9d6c-29cc015614fe.png)

![Capture d’écran 2022-04-04 à 09 51 29](https://user-images.githubusercontent.com/10072454/161498607-e355584e-5a8a-4930-a759-894250ef51e7.png)

**Comment by Rouergue** [comment]
Aaaargh... Maintenant, la mauvaise version se retrouve partout !

![Capture d’écran 2022-04-05 à 12 13 59](https://user-images.githubusercontent.com/10072454/161732199-f85c1f84-d581-42f8-a9dd-b6092ba69151.png)

![Capture d’écran 2022-04-05 à 12 13 53](https://user-images.githubusercontent.com/10072454/161732214-44a1ea93-facf-4b52-be46-c3288c035a12.png)

**Comment by Rouergue** [comment]
Je viens de rebalancer la bonne couv (ci-jointe) sur le serveur cyberduck en espérant que cette fois-ci ça fonctionnera !

![9782812623578](https://user-images.githubusercontent.com/10072454/161732632-9bd5ae8d-66ff-4ad7-83df-46415ed9654c.jpg)

**Comment by Fchallier** [comment]
C'est ok suite au message à Remy et Myriam, ça sera définitivement la bonne couverture qui remontera. 
J'ai lancé la mise à jour ce matin et c'est OK.  (pour info le système de mise à jour Site/Mistral se lance tout les matin à partir de 11h.)

Bien à toi,
