### ISSUE TITLE
Ajouter la possibilité de lister les Prix littéraires obtenus à partir de la recherche

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#468]
Quand on recherche par exemple "Prix Sorcières", ce serait cool que les résultats affichent tous les titres qui ont obtenu le Prix Sorcières. Or, actuellement, les résultats ne répertorient que les fiches dont le mot "Sorcières" apparaît dans le corps du texte. 

![Capture d’écran 2022-05-04 à 14 49 35](https://user-images.githubusercontent.com/10072454/166684927-ad37dbbe-d46c-4dcc-acf1-36d3ba650496.png)

Pourrait-on faire en sorte que la recherche s'applique à tous les champs, pas seulement le champ "Petite phrase" (pour les fiches livres) ou "Biographie" (pour les fiches auteurs) mais aussi les champs "Embed video - liseuse" et "Citations presse" dans laquelle je mentionne en général les Prix littéraires ?

![Capture d’écran 2022-05-04 à 14 56 49](https://user-images.githubusercontent.com/10072454/166685683-b2aa1ccc-1751-40e0-925d-aaa2ed4d1148.png)

**Comment by Fchallier** [comment]
J'ai cherché pendant un petit moment.... mais étant donné que nous utilisons l'autocomplétion, il n'est possible de chercher uniquement sur les titres de l’élément. 
Donc en gros, soit sur le titre du livre, soit sur le titre de l'actualité, le nom de l'auteur (qui correspond au titre dans drupal)...

Il faudrait revoir complétement le système de recherche à ce niveau, et c'est pas vraiment simple.

**Comment by Rouergue** [comment]
Bon bah, on laisse tomber, alors !
