### ISSUE TITLE
Traduction qui remonte au niveau de la bibliographie auteur

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#469]
Julia Kerninon, par ailleurs autrice chez nous, a traduit THORNHILL et, du coup, ce livre remonte dans sa bibliographie. Est-il possible de ne pas faire remonter les livres des traducteurs dans leur bibliographie lorsqu'ils ont, en parallèle, une fiche auteur sur le site car ils ont publié en tant qu'auteur ? 

![Unknown](https://user-images.githubusercontent.com/10072454/176433443-710d6559-35a2-4589-9c53-d1bf27adfb74.png)

![Unknown-1](https://user-images.githubusercontent.com/10072454/176433449-46577556-4cef-4634-8cd8-94b0293cc223.png)

![Capture d’écran 2022-06-29 à 14 13 45](https://user-images.githubusercontent.com/10072454/176433572-d0630e79-29f2-4677-8c3e-fcd06852996b.png)

**Comment by Fchallier** [comment]
Sans soucis, je viens de modifier cela, seront affiché uniquement les titres où le contributeur est soit Auteur, illustrateur ou Photographe. Et également si celui-ci est communicable. 
![Screenshot 2022-06-29 at 17-30-19 Structure rouergue](https://user-images.githubusercontent.com/9974750/176476758-9f44fba6-adb9-4fb6-a8c2-a8b600358c52.png)

**Comment by Rouergue** [comment]
Super, merci !
