### ISSUE TITLE
Ajout du format des livres

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#470]
Est-il possible de rajouter le format des livres sous la pagination sur les fiches livres comme sur le modèle ci-dessous ? 

![exemple](https://user-images.githubusercontent.com/10072454/176683045-83a27c78-4480-428f-8e14-a00e0d09079f.png)

**Comment by Fchallier** [comment]
- [ ] Modification du module de migration afin d'importer le format
- [ ] Modification de l'affichage d'une fiche livre afin que le format soit bel et bien affiché

**Comment by Rouergue** [comment]
Thanks !
