### ISSUE TITLE
Titre dont le prix a été validé et qui ne remonte pas

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#471]
Est-ce normal ? Il s'agit de VORTEX. Le prix a pourtant bien été validé dans mistral...

![Capture d’écran 2022-07-13 à 14 31 20](https://user-images.githubusercontent.com/10072454/178734046-b35b79f6-f2d6-48df-909e-6c4e01afbcad.png)

C'est un livre prévu à l'office du 31 août, en même temps que "Merci pour la tendresse" qui, lui, remonte bien.

**Comment by Rouergue** [comment]
Toujours rien en vu ce matin...
Ci-dessous la couv du livre qui devrait apparaître. Quid ?

![Capture d’écran 2022-07-19 à 09 11 14](https://user-images.githubusercontent.com/10072454/179688749-b5ffba29-b3ce-4b28-8749-1c821d2bc70d.png)

**Comment by Fchallier** [comment]
Il y avait un souci au niveau du système de migration.  Les commandes n'étaient plus reconnues... 
Je viens de relancer à la main le système ça semble bien fonctionner et le titre semble également bien remonter.

**Comment by Rouergue** [comment]
cool, merci !
