### ISSUE TITLE
Présentation de la page récap' des vidéos

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#474]
• Remonter, si possible la mention "voir toutes nos vidéos", à aligner sur le nom de la rubrique.
• Ne laisser que le titre et auteur en-dessous de la vignette.
• Passer le type de vidéo en haut à gauche de la vignette + le catalogue (en plus petit), justifié en haut à droite.

![page récap vidéos](https://user-images.githubusercontent.com/10072454/187721534-6017510d-9dbf-4e4d-8ae6-fd2de174f13c.png)

**Comment by Rouergue** [comment]
Et, pour le bas de page, j'ai retrouvé la demande ci-dessous, perdue dans le fil de nos échanges et que je te remets ici. 

![Capture d’écran 2022-08-31 à 17 07 54](https://user-images.githubusercontent.com/10072454/187721607-4f4d859a-2ec6-4388-94fd-725c26db44bf.png)

**Comment by Fchallier** [comment]
Je viens de faire quelques ajustements, tu me diras si cela te convient ? 
Par contre ça ne sera pas possible de "Remonter, si possible la mention "voir toutes nos vidéos", à aligner sur le nom de la rubrique." 
Ce sont deux différents bloc différents.

**Comment by Rouergue** [comment]
Ok, merci pour tes modifs. Pour la mention à remonter, ce n'est pas grave. 
Pour les mentions titre + auteur, est-ce que c'est possible de remonter un peu le nom de l'auteur (comme pour _In carna,_ dans l'exemple ci-dessous) et de ne laisser qu'une ligne pour le titre ? Je m'arrangerai pour que les titres ne dépassent pas une ligne !

![Capture d’écran 2022-09-01 à 13 59 19](https://user-images.githubusercontent.com/10072454/187908971-df9c4c2e-6544-41a2-8188-a067e456a1ce.png)

**Comment by Fchallier** [comment]
Je viens de réduire un peu l'espace, c'est bon pour toi  ?

**Comment by Rouergue** [comment]
👍  Thanks !
