### ISSUE TITLE
Ajout d'un lien vers le livre et les auteurs, dans la page vidéo

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#476]
Un peu sur le même modèle qu'on trouve sur les pages événements dans l'agenda.

![page vidéo](https://user-images.githubusercontent.com/10072454/187726091-13dc50a3-36ce-4b93-99bf-e6d2c170c08b.png)

**Comment by Fchallier** [comment]
Bonjour Mathilde, 

Désolé je n'avais pas répondu au ticket suivant, mais j'ai rajouté la fonctionnalité sur les fiches vidéos.  

Mais il y a un petit bug au niveau de l'affichage, je corrige ça au plus vite  ;)

**Comment by Rouergue** [comment]
Merci beaucoup, François. 
Est-ce que c'est possible de mettre un peu plus d'espace entre la vidéo et le nom de l'auteur + livre, stp ?
Merci et bonne journée !

![Capture d’écran 2022-10-12 à 10 21 38](https://user-images.githubusercontent.com/10072454/195290252-a6e2c11a-623e-4429-a60d-727a01ca0e37.png)

**Comment by Fchallier** [comment]
C'est ok je viens d'ajouter un espace en dessous de la vidéo.
