### ISSUE TITLE
Problème d'affichage sur notre site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#478]
La couverture "bave", alors que l'image est bonne sur Mistral. Quid ?

![Capture d’écran 2022-10-10 à 09 28 35](https://user-images.githubusercontent.com/10072454/194817027-cec4e8d8-12c9-42bd-b0ea-235bdd65e459.png)

![Capture d’écran 2022-10-10 à 09 30 00](https://user-images.githubusercontent.com/10072454/194817032-c23fe9fd-0c25-4ea5-956a-92c1da43a443.png)

**Comment by Fchallier** [comment]
Une nouvelle découpe a été réalisé depuis non  ? Voici la couverture qui est déposé depuis la découpe de Mistral : 
![9782812623929](https://user-images.githubusercontent.com/9974750/197506026-f8387143-2dce-45ae-8177-dde5acd6e4f8.jpg)

**Comment by Rouergue** [comment]
Oui, apparemment la couv a été mise à jour sur mistral depuis. 
C'est donc tout bon !
