### ISSUE TITLE
Ajout de pages insta et FB dans le footer

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#479]
Nous avons deux pages supplémentaires sur les réseaux sociaux :

https://www.instagram.com/rouergue_nature/
https://www.facebook.com/profile.php?id=100086161397046

Pourrais-tu ajouter des boutons dans le footer comme sur le modèle ci-dessous, stp ?

![new footer](https://user-images.githubusercontent.com/10072454/195284746-19d60048-a929-4e34-ad93-2cf307f1f046.jpg)

(les pages initialement nommées "adulte" deviennent "littérature"). 

Merci beaucoup !

**Comment by Fchallier** [comment]
C'est normalement normalement ok

**Comment by Rouergue** [comment]
👍
