### ISSUE TITLE
Nombre de pages erroné sur notre site

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#480]
Apparemment la pagination est synchronisée avec la pagination provisoire de Mistral et non pas la pagination définitive.

![Capture d’écran 2022-10-20 à 17 03 25](https://user-images.githubusercontent.com/10072454/196986191-961f0022-b402-45cb-8544-4512dd00ac5b.png)

![Capture d’écran 2022-10-20 à 17 00 40](https://user-images.githubusercontent.com/10072454/196986159-770fbff5-a898-46e1-b452-d519e0a5fbe4.png)

**Comment by Fchallier** [comment]
Nous avons réalisé récemment une mise à jour de sécurité sur notre serveur. 

Et les commandes de mise à jour Mistral/Olea ne fonctionnaient plus... c'est corrigé et je viens de lancer la mise à jour.

**Comment by Rouergue** [comment]
Ok, merci !
