### ISSUE TITLE
Ordre des vidéos

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#481]
Pourquoi l'affichage des vidéos dans la rubrique dédiée ne respecte pas le tri vidéo réalisé manuellement ? 

![Capture d’écran 2022-10-24 à 10 08 32](https://user-images.githubusercontent.com/10072454/197478472-9dc68e74-b459-42a1-8a18-c1b15ca88a65.png)

![Capture d’écran 2022-10-24 à 10 08 46](https://user-images.githubusercontent.com/10072454/197478527-77a03c48-3200-4ce4-9c0c-5bc1e440913e.png)

**Comment by Fchallier** [comment]
Un petit souci au niveau du cache de la vue. Il y avait une heure de configuré au niveau du cache de la vue.
Je viens de supprimer cette option pour cette page. 

Bien à toi,

**Comment by Rouergue** [comment]
Merci !

**Comment by Rouergue** [comment]
Les dernières vidéos ajoutées s'affichent tout en bas de la page. Ne devraient-elles pas se retrouver pas défaut en haut ? 

![Capture d’écran 2023-01-11 à 16 10 05](https://user-images.githubusercontent.com/10072454/211841988-6568761f-b71f-48ef-811a-e832a6e6c294.png)

Pour info, les dernières vidéos mises en ligne sont :

![Capture d’écran 2023-01-11 à 16 10 45](https://user-images.githubusercontent.com/10072454/211842144-b873b20e-7a97-4822-8819-8120cbae5667.png)

**Comment by Fchallier** [comment]
Malheureusement, il est nécessaire d'enregistrer l'ordre des vidéos sur la page de tri [https://www.lerouergue.com/admin/tri-videos](url)  après voir ajouter les nouvelles vidéos afin que l'ordre soit bien pris en compte.

Mais je regarde s'il est possible d'améliorer cela.

**Comment by Rouergue** [comment]
Ok. Je pensais qu'on pouvait effectivement trier manuellement mais que, si on ne le faisait pas, les nouvelles vidéos s'affichaient automatiquement en haut par défaut.

**Comment by Rouergue** [comment]
Bien réenregistrer dans la partie admin le tri vidéo (même sans avoir déplacé des vidéos).
