### ISSUE TITLE
Forcer l'affichage d'un titre ancien en haut de la rubrique nouveauté

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#483]
Tout d'abord, bonne année, François et tous mes vœux pour 2023 !

Je souhaiterais savoir s'il est possible de faire remonter, chronologiquement, dans le haut de la liste des nouveautés, deux albums dont la couverture a changé, qui sont remis en vente (et en avant) mais qui n'ont pas eu de changement d'ISBN (ce qui explique pourquoi ils ne remontent pas vraiment comme "nouveauté").

Ai-je la possibilité de le faire manuellement en "forçant" la date ? Peut-être à partir des options de bas de page ? Je t'avoue que je ne sais pas trop comment faire...

![Capture d’écran 2023-01-05 à 16 20 28](https://user-images.githubusercontent.com/10072454/210818938-5126e975-5803-4919-b534-8c89f4882011.png)

Exemple pour NEW YORK EN PYJAMARAMA dont la première édition a été faire en octobre 2011 mais qui est remis en vente le 1er février 2023. 

![Capture d’écran 2023-01-05 à 16 20 37](https://user-images.githubusercontent.com/10072454/210819260-d3521164-1f88-433f-a2d3-0b4e606b5521.png)

![Capture d’écran 2023-01-05 à 16 20 45](https://user-images.githubusercontent.com/10072454/210819304-01051fa7-1a95-4d99-bf5e-9f42ab19a6b1.png)

**Comment by Fchallier** [comment]
Bonjour Mathilde !  Bonne année et meilleurs vœux également  ! 

Alors concernant le ticket suivant, celui-ci va à l'encontre de ce qui a été prévue au départ. Je suis  un peu remonté dans les anciens tickets ^^ 

Alors j'ai rapidement regardé dans la base de données et il y a peut-être un solution. C'est qu'à la place d’utiliser la date de parution il faudrait utiliser la date de mise en vente du programme commercial.

Après, toutes les nouvelles réimpressions remonteront automatiquement en tant que nouveauté.

Il ne sera pas possible de forcer manuellement cela, comme indiqué dans ton message, car à chaque nouvelle mise à jour, la de sera également mise à jour. 

Si tu es disponible demain matin, je te passe un rapide coup de file pour voir cela ensemble. 

Bien à toi,

**Comment by Rouergue** [comment]
Je ne travaille pas le vendredi mais on peut s'appeler lundi prochain si tu es dispo pour voir ça ensemble. 
Car il faut qu'on réfléchisse bien ; je ne suis pas sûre que ce soit une bonne idée d'utiliser la date de parution à la place de date de première mise en vente car, effectivement, cela va faire remonter toutes les réimp' et je ne crois pas que ce soit souhaitable... Il faudrait que je puisse en parler avec le reste de l'équipe.
Le cas présent reste assez rare puisque, en principe, dès qu'il y a une nouvelle édition avec changement de couv et de prix, il y a changement d'ISBN. Je ne sais pas pourquoi ça n'a pas été le cas ici. J'imagine que c'est par peur de perdre des commandes sur les éditions précédentes...
Affaire à suivre !

**Comment by Rouergue** [comment]
Bonjour François,
Je te confirme que nous n'allons pas changer l'algorithme pour la remontée des nouveautés : on reste donc bien sur la date de parution initiale (pour éviter que ne remontent en nouveautés toutes les réimpressions & co). Tant pis pour les nouvelles éditions des albums en question, j'ai un peu feinté en les mettant en avant via un bandeau actu sur la page d'accueil !

**Comment by Fchallier** [comment]
Mince pardon, je ne t'ai pas appelé hier ! 

Ok c'est noté pour la remonté des réimpressions, et la solution que tu as trouvé est probablement la meilleure si on souhaite éviter de faire remonter des titres non désirés en page catalogue.
