### ISSUE TITLE
Supprimer un champ "Embed vidéos-liseuses"

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#484]
J'ai créé un champ supplémentaire que je voudrais supprimer mais je n'ai pas de bouton pour le faire ! En outre, les éléments que j'ai effacés dans le champ (= embed d'une vidéo) apparaissent toujours en 4e position sur la page du livre. Peux-tu supprimer ce champ, stp et éventuellement rajouter un bouton pour que je puisse faire les suppressions moi-même si besoin est à l'avenir ?

![Capture d’écran 2023-01-19 à 15 33 41](https://user-images.githubusercontent.com/10072454/213470316-540ba839-b4f2-4113-9fc8-d8605513a1a3.png)

![Capture d’écran 2023-01-19 à 15 33 29](https://user-images.githubusercontent.com/10072454/213470431-480a085d-e814-479e-b9a9-5c387252d645.png)

![Capture d’écran 2023-01-19 à 15 38 18](https://user-images.githubusercontent.com/10072454/213470882-e07b8232-97bc-45bb-b567-ad719fd68685.png)

**Comment by Rouergue** [comment]
C'est bizarre parce que je n'avais aucun affichage du contenu ; le bloc était vide (et même en faisant un pomme + A pour tout sélectionner et supprimer, ça n'avait aucun effet). 
En tous cas, merci pour la suppression !

**Comment by Fchallier** [comment]
Ha oui, pardon !  Pour t'assurer qu'il n'y a plus rien dans le bloc, il est préférable de cliquer sur le bouton "source"

**Comment by Rouergue** [comment]
Oui, j'ai l'impression que c'est ce que j'ai fait, en essayant avec et sans passer par l'onglet "Source" mais peut-être que j'ai cafouillé à un endroit ;-) !
