### ISSUE TITLE
Changement des url pour les réseaux sociaux

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#485]
Nos pages instagram ont été renommées / redirigées vers de nouveaux url. Peux-tu faire les changements au niveau des liens dans le footer, stp ? Je n'ai a priori pas la main pour le faire...

Instagram littérature : https://www.instagram.com/editions_du_rouergue_litte/
Instagram nature : https://www.instagram.com/editions_du_rouergue_nature/
Instagram jeunesse : https://www.instagram.com/editions_du_rouergue_jeunesse/

Thanks !

**Comment by Fchallier** [comment]
Pas de soucis, je viens de mettre à jour le bloc ;) 
Bien à toi,
