### ISSUE TITLE
Workshop : peut-on faire des liens avec youtube

### ISSUE THREAD

**Issue by Rouergue** [EditionsDuRouergue/lerouergue#85]
ou bien faut-il forcément passer par vimeo ?

![capture d ecran 2015-01-06 a 16 53 18](https://cloud.githubusercontent.com/assets/10072454/5631164/978db33c-95c4-11e4-9be8-71b79d600009.png)

**Comment by zakxxi** [comment]
Ce n'est pas prévu étant donné que nous avons choisi la plateforme VIMEO pour la vidéos, mais c'est techniquement possible en dev supplémentaire.
